### ISSUE TITLE
New Connected Service tool should allow for update of an existing service interface.

### ISSUE THREAD

**Issue by wsnell** [dotnet/wcf#2402] opened 2017-11-20 23:24 UTC
New Connected Service tool (15.5 Preview 2) should allow you to see and update of an existing service interface (if it changes), just like the previous tool does on the full frame work.  Otherwise you have to delete and then regenerate.  I prefer the menu item that you had before as it is safer and clearer.
Thanks
-Wes

**Comment by zhenlan** [comment] 2017-11-21 07:23
@wsnell we are working in progress on this feature. In the meanwhile, please use an workaround discussed in #1753.

Duplicate of #1753

**Closed by zhenlan** 2017-11-21 07:23 UTC
