### ISSUE TITLE
Error on reference WSDL Service

### ISSUE THREAD

**Issue by miltoncamara** [dotnet/wcf#2214] opened 2017-08-21 13:23 UTC
When I try to reference a WSDL Service (http://webservices.sabre.com/wsdl/tpfc/OTA_VehAvailRateLLS2.4.1RQ.wsdl), I'm getting the following error:

```
Importing web service metadata ...
Number of services found: 1
Restoring NuGet packages ...
Building solution ...
Scaffolding service reference code ...
Error:Error: There was a validation error on a schema generated during export:
    Source: 
    Line: 2 Column: 3
   Validation Error: The global attribute 'http://www.w3.org/XML/1998/namespace:lang' has already been declared.


Error:Error: There was a validation error on a schema generated during export:
    Source: 
    Line: 3 Column: 3
   Validation Error: The global attribute 'http://www.w3.org/XML/1998/namespace:space' has already been declared.


Error:Error: There was a validation error on a schema generated during export:
    Source: 
    Line: 11 Column: 3
   Validation Error: The global attribute 'http://www.w3.org/XML/1998/namespace:base' has already been declared.


Error:Error: There was a validation error on a schema generated during export:
    Source: 
    Line: 13 Column: 3
   Validation Error: The attributeGroup 'http://www.w3.org/XML/1998/namespace:specialAttrs' has already been declared.


Error:An unknown error occurred while invoking the service metadata component.
Failed to generate service reference.
```

**Comment by hongdai** [comment] 2017-08-21 17:35
@miltoncamara  This is a duplicate of issue #1892. We are currently evaluating a fix.

You can probably workaround it by using .Net framework "Add Service Reference" to generate the reference code, then copy the code to your project and add service model package references needed.

**Comment by hongdai** [comment] 2017-08-22 23:41
@miltoncamara  I ignored the validation errors and generated Reference.cs for .Net Core. Could you give it a try to verify the generated client can invoke the service successfully? This will help us to decide whether the validation errors can be ignored.
 
Thanks,
Hong Dai
[Reference.zip](https://github.com/dotnet/wcf/files/1243725/Reference.zip)

**Closed** 2017-08-25 20:40 UTC

**Comment by dmitry-pavlov** [comment] 2018-05-31 10:33
I am still getting the error "**Failed adding Microsoft WCF Web Service Reference Provider to the project**" while trying to add WCF reference to https://webservice.nada.com/vehicles/secure/securelogin.asmx?WSDL 

Visual Studio Community 2017 - version 15.8.0 Preview 1.1

```
[31.05.2018 13:19:20.277] Adding Microsoft WCF Web Service Reference Provider to the project.
[31.05.2018 13:19:20.279] Importing web service metadata ...
[31.05.2018 13:19:20.401] Number of service endpoints found: 2
[31.05.2018 13:19:20.464] Scaffolding service reference code ...
[31.05.2018 13:19:25.183] Error:An unknown error occurred while invoking the service metadata component.
Failed to generate service reference.
[31.05.2018 13:19:25.216] Done.
[31.05.2018 13:19:25.234] Failed adding Microsoft WCF Web Service Reference Provider to the project.
```

Any thoughts how to fix / workaround this?

**Comment by dmitry-pavlov** [comment] 2018-05-31 12:35
**Workaround**

As adding Microsoft WCF Web Service Reference using WSDL does not work for ASP.NET Core project you can add new .NET Standard class library project targeted to Standard 2.0 and add service reference to it:

- Right click on project
- Select `Add` -> `Connected Service`
- In `Connected Services` window select `Microsoft WCF Web Service Reference Provider` 
- Specify WSDL details as described [here](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide) 
- Add new library reference to your ASP.NET Core web application (targeted to .NET Core 2.1)

**NOTE**: This (impossibility to add WCF service directly to ASP.NET Core project) should be explicitly mentioned in the [documentation](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide).
