### ISSUE TITLE
WCF Service in .Net Core 2 application

### ISSUE THREAD

**Issue by sajidsikander123** [dotnet/wcf#2366] opened 2017-11-07 15:37 UTC
I am trying to add a WCF Service in an application using the 'Connected Services' option but it gives an error saying 
Error:
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.0.5' was not found.' 

I have a .Net Core 2 already running. Is it I need to downgrade to 1.0.5 to use this one.

**Comment by zhenlan** [comment] 2017-11-07 17:46
@sajidsikander123 this issue has been fixed in VS 2017 Update **15.5 preview**. Please refer to #2340 for details where you can find a workaround if you are using an earlier update of VS 2017.

Duplicate of #2340

**Closed** 2017-11-09 01:45 UTC
Labels: tooling

**Comment by COLEplusTEN** [comment] 2018-01-10 22:21
I'm still seeing this same error on 15.5.3.
