### ISSUE TITLE
Can't generate proxy using WSDL file with "the service at the folowing uri does not have any valid endpoints" error (add support for 0-EP services)

### ISSUE THREAD

**Issue by caxepok** [dotnet/wcf#2238] opened 2017-08-25 20:31 UTC
But this wsdl working via svcutil and for full framework project.
wsdl file [soap.zip](https://github.com/dotnet/wcf/files/1252944/soap.zip)

**Comment by hongdai** [comment] 2017-08-25 20:35
@caxepok Sorry to hear you are running into the issue. We will use the attached wsdl to repro locally and investigate the root cause.

Thanks,
Hong Dai

**Comment by rajput81** [comment] 2017-08-29 05:44
Hi, I am facing the same issue when generating proxy using WCF Connected Service for Visual Studio 2017. Both of my wsdl works via svcutil and using Add service ref wizard in Studio 2015. Please look at it urgently..

**Comment by hongdai** [comment] 2017-08-29 16:31
@rajput81 The root cause of your issue might not be the same as @caxepok . Could you open a new issue and provide a repro? 

Thanks,
Hong Dai

**Comment by hongdai** [comment] 2017-08-29 16:51
@caxepok I see importing binding errors via svcutil.exe, and there is no output.config file generated. Have you verified the generated code by svcutil can invoke the service successfully?

Thanks,
Hong Dai

**Comment by rajput81** [comment] 2017-08-30 09:04
Hi Hong Dai, issue created #2254 and the wsdl schemas attached. Cheers

**Comment by xmlparser** [comment] 2017-08-30 13:52
@hongdai, Hi. I am able to generate out.cs file using svcutil.exe and via Visual Studio - Add Service Reference

**Comment by hongdai** [comment] 2017-08-30 18:11
@xmlparser I assume you have the same wsdl files as @caxepok .

My question is can you use the generated out.cs file to make a call to the service successfully? svcutil.exe sometimes generate code even though there are no valid endpoints. 

Thanks,
Hong Dai

**Comment by qinxiaowen** [comment] 2017-09-04 06:58
i have the same problem

**Comment by hongdai** [comment] 2017-09-05 15:17
@qinxiaowen Could you please open a new issue for the issue you are running into? The root cause for the error message "the service at the folowing uri does not have any valid endpoints" could be very different.

Thanks,
Hong Dai

**Comment by qinxiaowen** [comment] 2017-09-05 16:38
@hongdai ok

**Comment by hongdai** [comment] 2017-09-08 17:30
@caxepok Could you please answer my question posted some time ago?
"I see importing binding errors via svcutil.exe, and there is no output.config file generated. Have you verified the generated code by svcutil can invoke the service successfully?

We will assume this is a issue in the service if no further response.

Thanks,
Hong Dai

**Comment by xmlparser** [comment] 2017-09-13 10:21
@hongdai hi. yes, of course, we use this wsdl in production on full framework.

**Comment by hongdai** [comment] 2017-09-13 16:50
@xmlparser Could you confirm you have the same wsdl files as @caxepok? 

It's impossible to make the service call without output.config(service endpoint defined). On full framework, you might have added some code on the client side in addition to generated code. Could you take a look your full framework client code?

Thanks,
Hong Dai

**Comment by xmlparser** [comment] 2017-09-15 06:46
@xmlparser oh, actually I'm one guy :)

**Comment by hongdai** [comment] 2017-09-29 17:33
@xmlparser  Could you answer below question:

It's impossible to make the service call without output.config(service endpoint defined). On full framework, you might have added some endpoint configurations in the output.config manually. Could you check it?

Thanks,
Hong

**Comment by caxepok** [comment] 2017-10-01 19:27
@hongdai We are not using output.cfg because configuring endpoints in runtime.

**Comment by hongdai** [comment] 2017-10-02 15:55
@caxepok Thanks for confirming it! .NET Core WCF connected service tool does not use configuration and we do not generate code if no endpoints are defined in the wsdl files.

We will evaluate the support to allow users specify endpoints in runtime.
Thanks,
Hong Dai

**Comment by mlacouture** [comment] 2017-12-05 19:22
This has been fixed in[ Visual Studio 2017 15.5](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes#WCFTools). 

thank you for helping us deliver a better Visual Studio!

**Closed by mlacouture** 2017-12-05 19:22 UTC
Labels: Community, feature request, tooling
