### ISSUE TITLE
Empty client generated - Unable to add service reference: "Warning: The optional WSDL extension element 'body' from namespace 'http://schemas.xmlsoap.org/wsdl/soap/' was not handled."

### ISSUE THREAD

**Issue by wojtst** [dotnet/wcf#2591] opened 2018-02-22 11:56 UTC
Hello,
I am trying to generate a proxy using the extension "Microsoft WCF Web Service Reference Provider" in Visual Studio 2017 for .NET Core 2.0 project.
The WSDL I am trying to add works in .NET framework projects (by Add web reference), but in .NET Core this is no available.

This is the WSDL that I am trying to add https://publisher.flexnetoperations.com/axis/services/PubWS?wsdl

The result is an empty service, without any methods 

There is a log what I am receiving after adding

![2](https://user-images.githubusercontent.com/2332075/36537197-bfb92040-17cf-11e8-9124-34d860f6f688.png)

![1](https://user-images.githubusercontent.com/2332075/36537171-a3b21cee-17cf-11e8-8ea4-e3075b197d4a.png)

Thank you

**Comment by mlacouture** [comment] 2018-03-26 18:17
Hi @wojtst 
This is to acknowledge that this issue is on our radar. Thank you for reporting it.

**Comment by mlacouture** [comment] 2018-07-09 21:56
Hi @wojtst 
We finally had a chance to look into this, but we have not been able to reproduce the issue.  The generated proxy code contains a client class (PubWSClient) as expected.  What version of Visual Studio 2017 are you using? Alternatively, you can try the [dotnet-svcutil tool](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide) which was released recently.
thanks,

**Comment by mlacouture** [comment] 2018-07-09 22:15
Wait, on a second look and now understand what you mean, the client doesn't have methods for the service operations.  Let us investigate a bit more ...

**Comment by mlacouture** [comment] 2018-07-10 22:10
Update: we have investigated and identified the problem.  This issue has the same root as #2765. We will consider providing a fix for future release.

**Comment by mlacouture** [comment] 2018-08-24 21:35
Hi @elmojo 
Are you able to share your service URL or provide the service WSDL to us?
thanks,

**Comment by elmojo** [comment] 2018-08-24 21:41
It's internal but let me check with security.

**Comment by elmojo** [comment] 2018-08-24 21:46
Here you go.

[b-one-authentication.wsdl.txt](https://github.com/dotnet/wcf/files/2319980/b-one-authentication.wsdl.txt)

**Comment by mlacouture** [comment] 2018-08-25 01:55
Thank you @elmojo for providing the wsdl.  I'm seeing other error messages while processing the WSDL which generate a genuine warning that looks like the one that originated this issue but I think you are experiencing a different problem (based on the provided wsdl):

_Attempting to load metadata from 'd:\dd\temp\GitHub2519\b-one-authentication.wsdl'.
Warning: Fault named WSAuthenticationException in operation checkUserIdentity cannot be imported. Unsupported WSDL, the fault message part must reference an element. This fault message does not reference an element. If you have edit access to the WSDL document, you can fix the problem by referencing a schema element using the 'element' attribute.

Warning: The optional WSDL extension element 'body' from namespace 'http://schemas.xmlsoap.org/wsdl/soap/' was not handled._

**Comment by elmojo** [comment] 2018-08-27 02:00
So are you saying the WSDL isn't valid?

I ran that WSDL through a couple of WSDL analyzers and they all said it was a valid WSDL.  It appears the document I uploaded was a little corrupted some how.  I will upload a newer version.
[b-one-authentication.wsdl.txt](https://github.com/dotnet/wcf/files/2322148/b-one-authentication.wsdl.txt)

**Comment by elmojo** [comment] 2018-08-27 13:35
Attached is the file detailing the errors I am getting when trying to generate the proxy service from the WSDL within VS2017.  It is the same error over and over again; the one stated in the title of this issue: The optional WSDL extension element 'body' from namespace 'http://schemas.xmlsoap.org/wsdl/soap/' was not handled.

Also, I was able to successfully use SoapUI to test this SOAP service and it didn't have a problem with the WSDL.
[wsdl-errors.txt](https://github.com/dotnet/wcf/files/2324025/wsdl-errors.txt)

**Comment by elmojo** [comment] 2018-08-28 14:49
I hand corrected the WSDL and reran the svcutil and was able to get a proper proxy built.  Thanks for the feedback.

**Comment by mlacouture** [comment] 2018-08-28 16:59
Hi @elmojo, thank you for the update and I'm glad you got your problem resolved.

**Comment by ozbekenes** [comment] 2018-11-23 06:55
I want to share the error  when I want to add web service.net core console application.
Errors appear in the attached image, when I want to add the service. After removing attributes that caused the error from wsdl
manually, I can implement service properly. After adding web service,
XML Parsing Error errors are arising when I want to call the method.
I realized that the cause of this error was due to an field defined as bool and I could solve the problem by doing this field nullable bool.
In .net framework, I just add web reference in one step and I started using the service.


![image](https://user-images.githubusercontent.com/41689889/48930863-356c5580-ef04-11e8-87a4-dbdaed1e12b5.png)

**Comment by dasetser** [comment] 2019-02-15 00:14
Reclosing this. It looks like it was reopened due to a misunderstanding in the conversation of 3145. Since the problem with dotnet-svcutil has been solved and you're just running into a runtime issue now it makes sense to only have one open issue. I'll also follow up on why 3145 is not currently assigned to anyone.

**Closed by dasetser** 2019-02-15 00:14 UTC
Labels: bug, tooling

**Comment by sanchapereira** [comment] 2019-03-19 23:01
Using the `dotnet-svcutil tool` v2 this happens when using `--serializer DataContractSerializer`, with other serializer options it works fine.

**Comment by Tjeerd-menno** [comment] 2019-08-20 04:57
With the `dotnet-svcutil tool v2.0.1` I'm getting the same error when using DataContractSerializer.

WSDL files (open standard) are in here: https://www.edustandaard.nl/app/uploads/2019/01/ECK-DT2.0-services-v2.2p1.zip

### repro steps
Just unzip somewhere, cd to the wsdl folder and run the command below.

```bash
dotnet-svcutil ECK-DT2-OrderService-v2.2.wsdl ECK-DT2-SpecifyService-v2.2.wsdl ECK-DT2-ActivationCodeService-v2.2.wsdl ..\xsd\*.xsd -tf netcoreapp2.2 -n "*, EduStandaardProxy.Infrastructure.Generated" -o EduStandaardServices -ser DataContractSerializer
```

**Comment by shutyaev** [comment] 2019-08-20 07:08
Getting the same problem with DataContractSerializer (we need it because we can use Lists instead of arrays):

> dotnet-svcutil -ser DataContractSerializer -ct 'System.Collections.Generic.List`1' http://webservices.sabre.com/wsdl/tpfc/OTA_CancelLLS2.0.2RQ.wsdl

dotnet-svcutil version is 2.0.1

**Comment by dasetser** [comment] 2019-08-21 19:05
@Tjeerd-menno and @shutyaev This behavior means that dotnet-svcutil isn't able to generate the proxy correctly using DataContractSerializer and falls back to XmlSerializer. This is usually because the service is using something that DataContractSerializer does not support. DataContractSerializer supports less of the XML Schema definition language (XSD) standard than XmlSerializer (you can see some information about what it does and does not support [here](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/data-contract-schema-reference)), so our default behavior is to fall back to XmlSerializer when we run into problems with DataContractSerializer.

It looks like both of the wsdls you provided have similar behavior with svcutil.exe, so this looks like it's a limitation of DataContractSerializer rather than a bug in dotnet-svcutil.
