### ISSUE TITLE
Support WebSockets on Linux

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#625] opened 2015-12-11 13:56 UTC
WebSockets does not yet work on Linux because the implementation of WebSockets.Client is currently only a stub.  Issue https://github.com/dotnet/corefx/issues/2486 tracks implementing it.  Once fixed, we need to remove [ActiveIssue] from any tests assigned to this current issue.

**Comment by roncain** [comment] 2015-12-11 14:05
Note: this issue is referenced in several [ActiveIssue] attributes in tests.  Please don't close it without also modifying those [ActiveIssues].

**Comment by mconnew** [comment] 2016-07-11 22:57
This is blocked by dotnet/corefx#9985. The tests appear to succeed, the issue is with closing the WebSocket.

**Closed** 2016-07-26 20:01 UTC
Labels: 2 - In Progress, Known Issue 1.0.0, Linux, not yet supported, tracking
