### ISSUE TITLE
System.PlatformNotSupportedException: Compiling JScript/CSharp scripts is not supported

### ISSUE THREAD

**Issue by nosson** [dotnet/wcf#2219] opened 2017-08-22 10:32 UTC
Hi,

I am using a WSDL file ([wsdl.zip](https://github.com/dotnet/wcf/files/1241683/wsdl.zip)) provided by Salesforce.com. When trying to logon to the service using the below code, it threw a System.PlatformNotSupportedException saying "Compiling JScript/CSharp scripts is not supported"

`
var salesforceClient = new SoapClient();
salesforceClient.loginAsync(null, username, password).Wait();
`

Here is the stack trace.
`
InnerException	{System.PlatformNotSupportedException: Compiling JScript/CSharp scripts is not supported
   at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location)
   at System.Xml.Serialization.XmlSerializer.GetSerializersFromCache(XmlMapping[] mappings, Type type)
   at System.Xml.Serialization.XmlSerializer.FromMappings(XmlMapping[] mappings, Type type)
   at System.ServiceModel.Description.XmlSerializerOperationBehavior.Reflector.SerializerGenerationContext.GenerateSerializers()
   at System.ServiceModel.Description.XmlSerializerOperationBehavior.Reflector.SerializerGenerationContext.GetSerializer(Int32 handle)
   at System.ServiceModel.Dispatcher.XmlSerializerOperationFormatter.AddHeadersToMessage(Message message, MessageDescription messageDescription, Object[] parameters, Boolean isRequest)
   at System.ServiceModel.Dispatcher.OperationFormatter.SerializeRequest(MessageVersion messageVersion, Object[] parameters)
   at System.ServiceModel.Dispatcher.ProxyOperationRuntime.BeforeRequest(ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.PrepareCall(ProxyOperationRuntime operation, Boolean oneway, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.Begin()
   at System.ServiceModel.Channels.ServiceChannel.BeginCall(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, TimeSpan timeout, AsyncCallback callback, Object asyncState)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.CreateGenericTask(ServiceChannel channel, ProxyOperationRuntime operation, Object[] inputParameters)}	System.Exception {System.PlatformNotSupportedException}
`

Is this really something that is not supported by the tool yet?

Thanks,
Son

**Comment by shmao** [comment] 2017-08-22 17:44
Hi Son, I tried the repro and could repro the issue on my machine. For now it seems to be a bug with the XmlSerializer generation using RefEmit. I need to investigate the issue further to understand the root cause.

XmlSerializer has a special mode in which the serializer would use reflection instead of RefEmit to do serialization. I wondered if the app would work in that mode. If you are willing to give it a try, you can enable the mode by using the code below at the app's startup,

```c#
static void Main(string[] args)
{
    MethodInfo method = typeof(XmlSerializer).GetMethod(SerializationModeSetterName, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);
    method.Invoke(null, new object[] { 1 });

    // Your code goes here
}
```

Note that, using reflection to enable the mode is subject to future changes.

**Comment by nosson** [comment] 2017-08-23 04:31
That workaround works, shmao (just found out that the method name was "set_Mode"). Thank you very much.

**Comment by shmao** [comment] 2017-08-23 16:42
@nosson Thanks for the confirmation. Glad you figured out the method name (I meant to change the name to the actual value, but I forgot).

**Comment by shmao** [comment] 2017-09-11 22:09
I understood the root cause of the issue. One of the types generated by WCF Connected Service was wrong, see below.

```C#
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("columns", typeof(ListViewRecordColumn), IsNullable=false)]
        public ListViewRecordColumn[][] records
        {
            get
            {
                return this.recordsField;
            }
            set
            {
                this.recordsField = value;
            }
        }
```

The property is a 2-dimensional array, but the `XmlArrayItemAttribute` speicifed the item type as `typeof(ListViewRecordColumn)`. To work around the issue, we can change the item type to `typeof(ListViewRecordColumn[])`.

The issue is a duplicate of https://github.com/dotnet/wcf/issues/1274. Resolved the issue as duplicate.

**Comment by petervestergaard** [comment] 2017-11-10 12:00
I am also experiencing this issue.

WSDL:
<schema ........>
	<complexType name="DrivInfID">
		<sequence>
			<element minOccurs="0" maxOccurs="unbounded" name="DriverInformation" type="string"/>
		</sequence>
	</complexType>
	<complexType name="CreateCustomer">
		<sequence>
			<element minOccurs="0" maxOccurs="1" name="FirstName" type="string"/>
			<element minOccurs="0" maxOccurs="1" name="MiddleName" type="string"/>
			<element minOccurs="0" maxOccurs="1" name="LastName" type="string"/>
			<element minOccurs="1" maxOccurs="unbounded" name="DrivInfID" type="tns:DrivInfID"/>
		</sequence>
	</complexType>
	<element name="CreateCustomer" type="tns:CreateCustomer"/>
</schema>

Reference.cs

[System.Xml.Serialization.XmlArrayAttribute(Order=24)]
[System.Xml.Serialization.XmlArrayItemAttribute("DriverInformation", typeof(string), IsNullable=false)]
public string[][] DrivInfID
{
	get
	{
		return this.drivInfIDField;
	}
	set
	{
		this.drivInfIDField = value;
	}
}

regards
Peter

**Comment by ShaneRayCafe** [comment] 2018-01-20 04:46
I am also running into this issue trying to consume WSDL from https://www.sandbox.paypal.com/wsdl/PayPalSvc.wsdl using .NET Standard 2.0.  Two interfaces are generated `PayPalAPIInterface` and `PayPalAPIAAInterface`.  `PayPalAPIInterface` seems to work okay, However `PayPalAPIAAInterface` throws "Compiling JScript/CSharp scripts is not supported".  I tried the solution provided by @shmao -- it did get me a bit further.. I was able to read the xml using `IClientMessageInspector`.... before adding 
```
MethodInfo method = typeof(XmlSerializer).GetMethod("set_Mode", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);
    method.Invoke(null, new object[] { 1 });
```
it would not even enter the `AfterReceiveReply` method.
```
        public void AfterReceiveReply(ref Message reply, object correlationState)
        {
            var payPalMessage = reply.ToString();
        }
```

After adding that I could get to the `payPalMessage` string, but after that it would throw an exception trying to deserialize the response.  Also any request to the `PayPalAPIInterface` would throw deserialization exception after setting the `set_Mode`.  Any suggestions?

**Comment by gojimmypi** [comment] 2019-09-13 19:49
It is unfortunate that this issue is marked as closed (as well as https://github.com/dotnet/wcf/issues/1274 referred to as duplicate), as I encountered this problem today; but a **Big Thank You** to @shmao for the [workaround](https://github.com/dotnet/wcf/issues/2219#issuecomment-324100635), (above).

In my case, this Service Reference code that was generated from Vendor WSDL:

```
public System.Threading.Tasks.Task<bool> pingAsync(ServiceReferenceCompany.VendorLogin VendorLogin)
{
    return base.Channel.pingAsync(VendorLogin);
}

```
being called like this:

```
VendorSoapV1Client a = new VendorSoapV1Client(VendorSoapV1Client.EndpointConfiguration.VendorSoapV1SOAP, "https://vendor.contoso.com/Vendor/SoapV1/Service");
            
VendorLogin myLogin = new VendorLogin();
myLogin.Login = "username";
myLogin.Password = "password";

bool ok = await a.pingAsync(myLogin);
```

resulted in the `Compiling JScript/CSharp scripts is not supported` error on that `bool ok` line.

As described above, adding these lines using `System.Reflection` appears to have fixed the error for me:

```
MethodInfo method = typeof(XmlSerializer).GetMethod("set_Mode", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);
method.Invoke(null, new object[] { 1 });
```

**Comment by mconnew** [comment] 2019-09-17 19:44
This issue was closed as it is a duplicate of issue #1274 as mentioned in [this](https://github.com/dotnet/wcf/issues/2219#issuecomment-328673165) comment. That's the issue to post any follow-ups to. That issue was closed as we are prioritizing fixing regressions (it works on .NET Framework but not on .NET Core) and the issue existed on .NET Framework and has a workaround. I haven't read through details of either issue or your problem closely, just providing you some info as to why these issues were closed. Although a quick read through does seem like your issue might be different than this one and #1274 based on how you worked around it.

**Comment by nemantro** [comment] 2020-03-23 16:53
Hello,

I see that the issue is closed, but I wanted to add some investigation ideas.
In my case I'm still encountering this exception.
I disabled "Just My Code" when debugging wcf auto generated code (generated by the command line tool and in another test, using Visual Studio 2019) 
I find out there a serialization issue behind this. 

Here is the exception message I'm receiving. 
`System.Xml.Serialization.CodeGeneratorConversionException`

As of now, I still didn't find any fix or workaround for this issue.

~ Slim

**Comment by kuntalbose** [comment] 2020-05-10 05:41
Hi @shmao I am using Asp.net core 3.1 and try to consume web-service,  I tried with bellow code

svcutil.exe /t:code /d:C:\Users\XXXX\Desktop\SOAP\WebApplication1\WebApplication1  http://ws.jobdiva.com/axis2/services/BIData?wsdl

And its generate the code file ([BIData.zip](https://github.com/dotnet/docs/files/4605182/BIData.zip)) and required methods when when I call a method bellow error occurred

![image](https://user-images.githubusercontent.com/7402233/81491187-c4ac2b00-92a8-11ea-8604-61d9f6922dd2.png)

Can you please help me?whats going wrong

**Comment by vuchl** [comment] 2020-06-04 12:27
> The property is a 2-dimensional array, but the `XmlArrayItemAttribute` speicifed the item type as `typeof(ListViewRecordColumn)`. To work around the issue, we can change the item type to `typeof(ListViewRecordColumn[])`.
> 
> The issue is a duplicate of #1274. Resolved the issue as duplicate.

I searched the XSD file I had for `Type[][]` and fixed the corresponding `XmlArrayItemAttribute` from `typeof(Type)` to `typeof(Type[])` and also got it working! Thanks so much @shmao

**Comment by Catchops** [comment] 2021-01-26 16:57
> 
> 
> Hi Son, I tried the repro and could repro the issue on my machine. For now it seems to be a bug with the XmlSerializer generation using RefEmit. I need to investigate the issue further to understand the root cause.
> 
> XmlSerializer has a special mode in which the serializer would use reflection instead of RefEmit to do serialization. I wondered if the app would work in that mode. If you are willing to give it a try, you can enable the mode by using the code below at the app's startup,
> 
> ```cs
> static void Main(string[] args)
> {
>     MethodInfo method = typeof(XmlSerializer).GetMethod("set_Mode", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);
>     method.Invoke(null, new object[] { 1 });
> 
>     // Your code goes here
> }
> ```
> 
> Note that, using reflection to enable the mode is subject to future changes.

For anyone who is reading this - the Reflection code does indeed work as a workaround.  However, be very careful.  I put this into our code which fixed the issue with the .cs files being generated from the svcutil utility.  However, we had other code in our application where the Reflection changes caused harm to the XML serialization being done there.  In our case, code to make payments.  Therefore, make sure you do a thorough regression test on the application you are working in.

**Comment by ruza-kavanka** [comment] 2021-11-26 07:20
Hi all,
I have the same issue and changing webservice generated code as suggested by @shmao helped to solve it. 
However - this issue is quite old and my configuration is .Net Core 5, VS 2019 and the issue is still pending...

**Comment by mconnew** [comment] 2021-11-29 22:51
@StephenMolloy, @HongGit, I think it might be worth revisiting this. This was closed in preference of another issue, and that issue was closed as there was a workaround. From what I remember/can tell, the problem is there are certain .NET class definitions which when generating an XmlSerializer using Ref.Emit would result in an exception being thrown and it would fail to generate. On .NET Framework, this triggered a fallback code path where it would use the legacy code generation XmlSerializer implementation which would work. One example where I've seen this happen is that when using code generation, the compiler can take advantage of implicit type conversion and implicit type conversion operators which Ref.Emit can't (although that's not solved by the reflection based serializer either, it would be a lot easier to implement there). I think we should consider an option to fall back to the reflection based serializer implementation in Core, but opt-in only as @Catchops mentioned, there can be cases where it does the wrong thing so this should be explicit.

@HongGit, I think there's scope here for looking at what dotnet-svcutil produces from the WSDL as it seems like it might be interpreting it incorrectly. If modifying the generated classes makes something work, then we might have a bug that we can fix.

@Catchops, can you/did you open an issue about the reflection based serializer doing the wrong thing?

**Comment by adrianm64** [comment] 2021-12-09 15:17
I guess the problem is [the same as this xsd.exe bug](https://stackoverflow.com/a/66041350/157224)

**Comment by HongGit** [comment] 2022-02-15 22:30
@mconnew  closing this one as there are other items which will cover your concerns.

@adrianm64  this is not the same as the xsd.exe bug.

**Closed by HongGit** 2022-02-15 22:30 UTC
Labels: serialization

**Comment by dr-consit** [comment] 2022-02-16 10:54
@HongGit I'm not sure I understand. Which other item is currently tracking this issue?
I am currently having to manually modify the generated classes post-hoc. So I would really like to know which item to follow for an eventual solution to this issue.

**Comment by davidgvh** [comment] 2022-02-17 00:12
@HongGit, I too would like to know where this issue will be tracked.

**Comment by Misiu** [comment] 2023-01-05 08:53
I have a similar issue with .NET 7 and official Microsoft's schemas for Dynamics - https://learn.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/customize-dev/form-xml-schema?view=op-9-1
I downloaded the schemas from here: https://download.microsoft.com/download/B/9/7/B97655A4-4E46-4E51-BA0A-C669106D563F/Schemas.zip
Then I generated CS using XSD tool and when trying to create a XMLSerializer:
```var serializer = new XmlSerializer(typeof(FormType));```
I get this error:

> Compiling JScript/CSharp scripts is not supported

Stack trace:

>    at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location) in /_/src/libraries/System.Private.Xml/src/System/Xml/Serialization/Compilation.cs:line 86
>    at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace, String location) in /_/src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs:line 316
>    at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace) in /_/src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs:line 249
>    at Dyn365.Mapping.Profiles.FormContextProfile.GetFormXml(Form form) in E:\Tests\Dyn365\Mapping\Profiles\FormContextProfile.cs:line 23
>    at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__21.MoveNext() in /_/src/EFCore.Relational/Query/Internal/SplitQueryingEnumerable.cs:line 340


I think that the problem is probably this:

```
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class OrDisplayRuleType {

    private object[][] orField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("CommandClientTypeRule", typeof(CommandClientTypeRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("CrmClientTypeRule", typeof(CrmClientTypeRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("CrmOfflineAccessStateRule", typeof(CrmOfflineAccessStateRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("CrmOutlookClientTypeRule", typeof(CrmOutlookClientTypeRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("CrmOutlookClientVersionRule", typeof(CrmOutlookClientVersionRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("DeviceTypeRule", typeof(DeviceTypeRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("EntityPrivilegeRule", typeof(EntityPrivilegeRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("EntityPropertyRule", typeof(EntityPropertyRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("EntityRule", typeof(EntityRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("FeatureControlRule", typeof(FeatureControlRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("FormEntityContextRule", typeof(FormEntityContextRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("FormStateRule", typeof(FormStateRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("FormTypeRule", typeof(FormTypeRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("HideForTabletExperienceRule", typeof(HideForTabletExperienceRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("HideIfCurrentUserIsNotSystemAdministratorRule", typeof(HideIfCurrentUserIsNotSystemAdministratorRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("HideIfDelveNotAvailableRule", typeof(HideIfDelveNotAvailableRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("HideIfDisabledForMobileRule", typeof(HideIfDisabledForMobileRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("HideIfEmailIsApprovedByAdminBasedOnESPRule", typeof(HideIfEmailIsApprovedByAdminBasedOnESPRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("HideIfEmailIsApprovedByAdminRule", typeof(HideIfEmailIsApprovedByAdminType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("HideIfEmailSignatureNotEnabledRule", typeof(HideIfEmailSignatureNotEnabledRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("HideIfExportToExcelNotEnabledRule", typeof(HideIfExportToExcelNotEnabledRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("HideIfHybridSSSNotEnabledRule", typeof(HideIfHybridSSSNotEnabledRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("HideIfNetBreezeNotAvailableRule", typeof(HideIfNetBreezeNotAvailableRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("HideIfO365UserDoesNotHaveExchangeSubscriptionsRule", typeof(HideIfO365UserDoesNotHaveExchangeSubscriptionsRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("HideIfPowerBITileNotAvailableRule", typeof(HideIfPowerBITileNotAvailableRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("HideIfProcessActiveRule", typeof(HideIfProcessActiveRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("HideIfProcessInactiveRule", typeof(HideIfProcessInactiveRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("HideIfProcessUnificationIsDisabledRule", typeof(HideIfProcessUnificationIsDisabledRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("HideIfProductRecommendationsNotEnabledRule", typeof(HideIfProductRecommendationsNotEnabledType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("HideIfReverseHybridSSSNotEnabledRule", typeof(HideIfReverseHybridSSSNotEnabledRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("HideIfSSSTroubleshootingNotEnabledRule", typeof(HideIfSSSTroubleshootingNotEnabledRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("HideIfServiceMetadataAvailableRule", typeof(HideIfServiceMetadataAvailableRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("HideIfSharepointS2SConfigurationEnabledRule", typeof(HideIfSharepointS2SConfigurationEnabledRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("HideIfTestExchangeServerNotEnabledRule", typeof(HideIfTestExchangeServerNotEnabledRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("HideIfUserIsNotTenantAdminRule", typeof(HideIfUserIsNotTenantAdminType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("IsExportToExcelOnlineEnabledRule", typeof(IsExportToExcelOnlineEnabledRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("MiscellaneousPrivilegeRule", typeof(MiscellaneousPrivilegeRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("OptionSetRule", typeof(OptionSetRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("OrganizationSettingRule", typeof(OrganizationSettingRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("OutlookRenderTypeRule", typeof(OutlookRenderTypeRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("OutlookVersionRule", typeof(OutlookVersionRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("PageRule", typeof(PageRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ReferencingAttributeRequiredRule", typeof(ReferencingAttributeRequiredRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("RelationshipTypeRule", typeof(RelationshipTypeRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("SkuRule", typeof(SkuRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ValueRule", typeof(ValueRuleType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public object[][] Or
    {
        get
        {
            return this.orField;
        }
        set
        {
            this.orField = value;
        }
    }
}

but I'm not sure if I can replace `[][]` with a single `[]`.

Besides that are there any plans to fix this buggy behavior?
```

**Comment by maddinthegreat** [comment] 2023-04-21 16:45
That problem still exists, also deserializing color values from an XML file like:
#A3FFA07A
will throw an parsing exception!

Please fix this ugly workaround:

`MethodInfo method = typeof(XmlSerializer).GetMethod("set_Mode", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);
    method.Invoke(null, new object[] { 1 });`

**Comment by wegylexy** [comment] 2023-06-06 16:06
In my case, it is due to `[][]`.
For example:
```xml
<Root>
  <Lines>
    <Line>
      <!--<Name>Bug when omitted</Name>-->
      <Coords><X>1</X><Y>2</Y></Coords>
      <Coords><X>3</X><Y>4</Y></Coords>
    </Line>
  </Lines>
</Root>
```
What `xsd` would generate when `Line` only consists of `Coords` without `Name`:
```cs
public partial class Root
{
  public Coords[][] Lines { get; set; }
}
```
What I need to patch, as when `Line` consists of multiple types of elements:
```cs
public partial class Root
{
  public Line[] Lines { get; set; }
}
public partial class Line
{
  /* public string Name { get; set; } */
  public Coords[] Coords { get; set; }
}
```

**Comment by Dinuka-Aeronology** [comment] 2024-10-23 04:03
> I understood the root cause of the issue. One of the types generated by WCF Connected Service was wrong, see below.
> 
>         /// <remarks/>
>         [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
>         [System.Xml.Serialization.XmlArrayItemAttribute("columns", typeof(ListViewRecordColumn), IsNullable=false)]
>         public ListViewRecordColumn[][] records
>         {
>             get
>             {
>                 return this.recordsField;
>             }
>             set
>             {
>                 this.recordsField = value;
>             }
>         }
> The property is a 2-dimensional array, but the `XmlArrayItemAttribute` speicifed the item type as `typeof(ListViewRecordColumn)`. To work around the issue, we can change the item type to `typeof(ListViewRecordColumn[])`.
> 
> The issue is a duplicate of [#1274](https://github.com/dotnet/wcf/issues/1274). Resolved the issue as duplicate.

Thanks, This helps me to fix my issue
