### ISSUE TITLE
Update Connected Service

### ISSUE THREAD

**Issue by eiki25** [dotnet/wcf#2309] opened 2017-09-27 15:03 UTC
Please add Right click on Folder support to Update reference.
Only way seems to be to add Connected Service again with same name and replace "reference.cs"

**Comment by zhenlan** [comment] 2017-09-28 00:09
@eiki25 thanks for the feedback. Please upvote #1753 if it's important to you.

Duplicate of #1753

**Closed by zhenlan** 2017-09-28 00:09 UTC
