### ISSUE TITLE
operation time out exception after 30 seconds

### ISSUE THREAD

**Issue by lukaszkruszka** [dotnet/wcf#2417] opened 2017-12-01 09:07 UTC
I can not handle the AIF interface with Dynamics AX 2012 R3. Large amounts of data are returned in a long time. I set up the HttpBinding configure for 10 minutes but after 30 seconds I get an operation time out exception. 
I created identical scripts and launched under Core 2.0 and full framework 4.6.1. 
At full framework everything works.

**Comment by zhenlan** [comment] 2017-12-01 19:25
Duplicate of #2368

**Closed by zhenlan** 2017-12-01 19:25 UTC
