### ISSUE TITLE
Connecting a service fails if the project doesn't build

### ISSUE THREAD

**Issue by DaleKBurrell** [dotnet/wcf#2268] opened 2017-09-05 04:35 UTC
When attempting to connect a WFC service using this provider, it fails it the project doesn't build. This is rather annoying at the best of times, but becomes highly annoying if the reason it doesn't build is because one has removed the service reference in order to re-generate it - and of course then all the existing references to it prevent it from building.

**Comment by hongdai** [comment] 2017-09-05 17:48
@DaleKBurrell Thanks for your feedback! We will evaluate the support for updating service reference and what we can do to improve customer experience.

Thanks,
Hong Dai

**Comment by mlacouture** [comment] 2017-10-26 18:39
[Hi @DaleKBurrell 

thanks again for reporting this issue.  There are two parts in this issue: 1. unable to update a service reference, 2. unable to add service reference when the build is broken.

for the first, we already have a tracking issue #1753, and as per the second issue it is necessary for the project to be buildable for the tool to reuse existing types when generating the proxy code so this is by design.

I'm going to resolve this issue as a dup of #1753 for which we are considering a fix to be available in the next release of the tool.

**Comment by mlacouture** [comment] 2017-10-26 18:41
duplicate of #1753.

**Closed by mlacouture** 2017-10-26 18:41 UTC
Labels: Community, tooling
