### ISSUE TITLE
Validation Error: Multiple definition of element causes the content model to become ambiguous

### ISSUE THREAD

**Issue by aritsa** [dotnet/wcf#2234] opened 2017-08-25 05:29 UTC
![image](https://user-images.githubusercontent.com/31313039/29700593-5d0bca58-8966-11e7-9bf1-e3502f1753a6.png)

I'm trying to add a Java Webservice and fixed already some problems with the encoding. But this one error seems a bit odd. There are multiple definitions of the NatuerlichePerson element in the schemas but they should be using different namespaces. PersonDataSlim.xsd and PersonData_20_dt.xsd are both using that element (wsdl.zip).
[wsdl.zip](https://github.com/dotnet/wcf/files/1250915/wsdl.zip)

I tried to connect that same service with .net 4.62 and it worked. 
[ZregService.zip](https://github.com/dotnet/wcf/files/1250919/ZregService.zip)

Could it be that the port cannot create the same elements with different namespaces? In Java it normally also needs some jaxb definitions.

**Comment by hongdai** [comment] 2017-08-28 18:32
@aritsa Sorry to hear that you are running into a issue! We will investigate the root cause.

**Comment by hongdai** [comment] 2017-09-29 17:42
@aritsa The reason it generates proxy successfully with .net 4.62 is because they ignore the validation error.
Ideally the service should fix the validation errors, however we understand that many customers do not own the service and it might be feasible. We decided to ignore all validation errors for the .Net Core WCF Web Service Reference tool as well. The change will be in the VS15.5 preview1 release.

Thanks,
Hong Dai

**Comment by aritsa** [comment] 2017-10-02 12:06
So basically it's a validation error. Any chance to verbose it?
When is the preview due to release?

**Comment by hongdai** [comment] 2017-10-02 16:21
The update will be released soon. No actual date yet.

The verbose validation error was shown on the scaffolding UI that you copied.

**Comment by hongdai** [comment] 2017-10-13 22:06
The fix is released as part of VS 15.5.0 Preview 1. Please download it from https://www.visualstudio.com/en-us/news/releasenotes/vs2017-preview-relnotes.

**Closed by hongdai** 2017-10-13 22:06 UTC
Labels: Community, tooling
