### ISSUE TITLE
Wsdl Services not working 

### ISSUE THREAD

**Issue by ripek** [dotnet/wcf#3283] opened 2018-11-26 06:29 UTC
https://api.n11.com/ws/ProductService.wsdl
Adds the same service twice

![screenshot_1](https://user-images.githubusercontent.com/12428878/48996608-c0945800-f15d-11e8-9933-ce52bc6aa032.png)

**Comment by Lxiamail** [comment] 2018-11-26 20:55
@ripek Can you describe the steps that you did to reproduce the problem?

**Comment by murattdogan** [comment] 2018-12-20 09:49
When we refer to wsdl service .net core project. The wcf provider itself is creating async functions that are not in the wsdl service. Therefore, the system does not work. Or in wsdl the function of the names of the function by putting the value of the system by the new func and the service does not work

**Comment by murattdogan** [comment] 2018-12-20 09:54
, WS-Trust 1.3 . net core not working 
https://kpsbasvuru.nvi.gov.tr/Services/WsdlNoPolicy.ashx?Service=KisiSorgulaKisiBilgiServis

**Comment by dasetser** [comment] 2018-12-21 17:00
@ripek Sorry for the delayed response. Thanks for reporting this. I don't think it's actually adding the same service twice, it just looks that way. The wsdl for this service is doing something a bit strange, and has multiple elements with the same name. When the types are generated there's a conflict that is resolved by appending a 1. They are actually different types with distinct uses, and you have to use the correct one, even if the naming isn't helpful in distinguishing the difference. It looks like this is the same behavior as Add Service Reference, so it's been around for a while. I'm not sure how we could handle this better. We base the name off the the wsdl's name. So when a service uses a conflicting name like this it's going to end up confusing regardless of how we avoid the naming conflict.

@murattdogan Your problem seems to be unrelated to this issue. Can you please open a new issue with the details of what you're running into?

**Comment by dasetser** [comment] 2019-01-15 22:49
Closing since this doesn't look like a bug.

**Closed by dasetser** 2019-01-15 22:49 UTC
Labels: Community, tooling
