### ISSUE TITLE
MessageHeaderAttribute fields are not scaffolded as Request Properties/settable

### ISSUE THREAD

**Issue by rposener** [dotnet/wcf#2295] opened 2017-09-19 14:05 UTC
Hello,

I have an old WCF service I'm trying to consume using our new app.  The issue I'm running into is that we set some "session" type information in a Header that is not available.  The Generated Request types have all the BodyMembers, but do not have the MessageHeaderAttribute that needs to also be set.  It is interesting though that our Header class is scaffolded, but cannot be set on the client or included with the request.  I have not tried adding the attribute manually via a separate code file, but will try that next.  Kind of wondering if it will be sent if it's not included in the scaffolded request.    Any tips/ideas to work around this for the time being would be appreciated.

Thanks!

**Comment by hongdai** [comment] 2017-09-19 16:04
@rposener Could you generate client code using "Add Service Reference" for the full framework, and see if you can set the MessageHeader? 

It will be great if you provide a repro wsdl file to help identify the root cause.

Thanks,
Hong Dai

**Comment by rposener** [comment] 2017-09-19 17:20
@hongdai here is the WSDL.  It's the AuthenticationInformation details that are missing for exmplae on the GenerateReport method.

`<wsdl:definitions xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://www.praceng.com/webservices/perepgen" xmlns:s1="http://microsoft.com/wsdl/types/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://www.praceng.com/webservices/perepgen">...</wsdl:definitions>`

**Comment by rposener** [comment] 2017-09-19 17:33
I have tested, and just adding another file with the missing property with the Header Attribute set on the field does send the value properly.  Makes for a relatively easy work-around for anyone with this issue since the class is partial anyway.

**Comment by hongdai** [comment] 2017-09-27 18:18
@rposener Does your new app use 1.0/1.1 Target framework? We have only enabled MessageHeader in 2.0 as there are some known WCF runtime issue in 1.0/1.1? I can generate the AuthenticationInformation successfully using the 2.0 .NET Core VS projects.

Could you try to generate the code using a 2.0 .NET Core VS projects, then just copy the reference.cs to your 1.0/1.1 project. If you can invoke the service successfully, we can enable the MessageHeader support in 1.0/1.1 as well.

Thanks,
Hong

**Comment by hongdai** [comment] 2017-10-13 22:02
Closing it as it's available in 2.0 and no more feedbacks from the customer.

**Closed by hongdai** 2017-10-13 22:02 UTC
Labels: Community, tooling

**Comment by rposener** [comment] 2018-02-13 23:04
@hongdai - I just did this again  today using what I believe is latest/current framework in VS 2017 and it still does not generate.  For now I know that I can manually add the property and attribute on the partial class; however a simple ASP.NET MVC 5 app targeting .Net 4.5.2 and using the "Connected Services" property window in VS 2017 does not scaffold this correctly.

**Comment by hongdai** [comment] 2018-02-13 23:16
@rposener Please reopen this issue if you are still hitting it. It will be assigned to the right person for investigation.
