### ISSUE TITLE
System.ServiceModel.BasicHttpBinding throwing InvalidOperationException in dotnet core 2.0

### ISSUE THREAD

**Issue by mtf30rob** [dotnet/wcf#2261] opened 2017-09-01 10:17 UTC
Moving issue from corefx repo as requested here: https://github.com/dotnet/corefx/issues/23646

I am getting an invalid operation exception calling an external web service when setting the proxy settings on the BasicHttpBinding class. The error is:

When using a non-null Proxy, the WindowsProxyUsePolicy property must be set to WindowsProxyUsePolicy.UseCustomProxy. (Source: System.Net.Http.WinHttpHandler)

My code:
var binder1 = new BasicHttpBinding();
binder1.UseDefaultWebProxy = false;
binder1.ProxyAddress = proxyAddress;
...

Removing these two lines (so it uses the machines default proxy settings) results in a successful web service call. From Dudod's comments in https://github.com/dotnet/wcf/issues/1592 it seems it may be related to the WinHttpHandler implementation.

I'm using Visual Studio 2017 version 15.3.0, my dll is targeting netstandard2.0 and I am using version 2.0.0 of the sdk. I'm testing this code using xunit tests targeting netcoreapp2.0.

FYI if I switch the unit test target from netcoreapp2.0 to net461 the above code works. Also removing the binder1.UseDefaultWebProxy = false line fixes the issue when targeting netcoreapp2.0. However it breaks when targeting net461.

Here is a sample repo to highlight the issue (run DotNetCoreApp to see error): https://github.com/mtf30rob/BasicHttpBindingSample

The steps I have taken are:
Create a service reference in a full framework project.
Manually copy the Reference.cs to a dot net standard 2.0 dll
Reference the dot net standard dll in a dot net core 2.0 app

**Comment by mconnew** [comment] 2017-09-06 00:00
I've reopened the issue in corefx as this should work as WinHttpHandler is not using the default from HttpHandlerDefaults. Also WCF isn't using WinHttpHandler directly and is instead using HttpClientHandler. Having said that, we should probably explicitly set HttpClientHandler.UseProxy regardless. Taking another look at the WCF code, we do have some other issues around this which you aren't hitting. If you set `UseDefaultWebProxy = false` and don't specify the proxy, we should set HttpClientHandler.UseProxy to false and we don't. We also don't do anything with BypassProxyOnLocal, although I don't know if we can correctly support that without additional support from HttpClientHandler.

**Comment by mconnew** [comment] 2017-09-11 17:40
I've re-examined this and this is an issue with WCF's setting of flags on HttpClientHandler. The UseDefaultWebProxy is being used directly to set HttpClientHandler.UseProxy. If you want to use a proxy server, for now set UseDefaultWebProxy to true and set your proxy server on the ProxyAddress property and it will do what you require. I'll update this issue when we know which release the fix will apply to.

**Comment by mconnew** [comment] 2017-09-18 18:25
@mtf30rob, did the workaround work for you?

**Comment by jsharland** [comment] 2018-01-02 15:22
Hi @mconnew I am experiencing the same problem and have tried the work around suggested of setting the proxy address and setting UseDefaultWebProxy to true. I end up getting a timeout when trying to make the call, which is the same as if I don't change the settings at all and just use the defaults. I had a look at the gist you created about how to update the HttpClient's WinHttpHandler (https://gist.github.com/mconnew/0af8e688cedc32669a8e44a53fcbaa4a) to see if I could update the proxy settings that way but the _httpClientCache is only created upon a successful call to the service.

The code that I am using is: 
var client = new PremierInn.Booking2SoapClient();
((BasicHttpBinding)client.Endpoint.Binding).UseDefaultWebProxy = true;
((BasicHttpBinding)client.Endpoint.Binding).ProxyAddress = new Uri("http://myproxy");
var result = client.ProcessMessageAsync(xml).Result;


Is there any timeline on when this will be fixed as it is causing us quite a few issues as we are constantly integrating new Wcf services and need to create work arounds for each using HttpClient directly to send and receive SOAP requests.

**Comment by roden23** [comment] 2018-01-05 16:27
Hi, @mconnew. Having the same issue. Connecting from netcore 2.0 app via WCF Connected Service.
The workaround you suggest does not work.

My settings here:
`
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                result.UseDefaultWebProxy = true;
                result.ProxyAddress = new Uri("http://xxxx");
            `
Request timing out.

**Comment by tavisca-shitaljit** [comment] 2018-01-09 09:29
Hi @mconnew, when is the expected release date for the fixe?

**Comment by zhenlan** [comment] 2018-01-12 19:25
Duplicate of #1592

**Closed by zhenlan** 2018-01-12 19:25 UTC
Labels: Community, bug
