### ISSUE TITLE
Support for pregenerated serializers

### ISSUE THREAD

**Issue by atanasa** [dotnet/wcf#1510] opened 2016-09-07 15:32 UTC
This is a request for wcf clients to consume pregenerated serializers to improve start up performance.
An option is to support the serializers generated by the svcutil.

cc @zhenlan

**Comment by atanasa** [comment] 2016-12-12 10:01
There seem to be two problems with supporting this currently for serializers generated by svcutil:
- Compiling the code is failing due to missing types for XmlSerializerImplementation and others
- The code that integrates the serializers into WCF is missing - i.e. loads the assembly and retrieves the typed serializers.

I have so far workaround it by:
- The types are there for .Net Core, just not in the reference assembly. I workaround this by compiling against the implementation assembly for .Net Core (because my case is for running on .Net Core)
- To get WCF to use the serializer I forked WCF and implemented a simple patch that would consume the serializers if there are present. The mappings generated by the tool and the ones expected by WCF seems to be compatible.

For obvious reasons I would like to not have to do this. Looking at the current code for corefx it seems like the types are there for .Net Standard 2.0 (netstandard1.7).

**Can someone confirm that in .Net Standard 2.0:**
- The code generated for serializers by the current svcutil (for .Net Framework) would compile
- The serializers would be consumed by at least WCF
- The serializers would work with WCF without complicated changes (e.g. the mappings expected by WCF and the mappings generated by the svcutil are the same/compatible)?

Ideally a compatible svcutil would be better, but I assume that would take longer to appear.

**Comment by zhenlan** [comment] 2018-01-27 21:14
This work is tracked in #1345 now.

Duplicate of #1345

**Closed by zhenlan** 2018-01-27 21:14 UTC
Labels: tooling

**Comment by zhenlan** [comment] 2018-06-06 03:13
Just in case anyone running into this thread, we have a .NET CLI tool `dotnet-svcutil.xmlserializer` released today. Please see details and instructions in the [announcement](https://github.com/dotnet/wcf/issues/2927).
