### ISSUE TITLE
dotnet-svcutil Unable to add connected service referencing ONVIF (Error : An item with the same key has already been added. Key: CreatePullPoint)

### ISSUE THREAD

**Issue by ErosGuil** [dotnet/wcf#3103] opened 2018-08-09 12:19 UTC
I've tried to port a .Net Framework library to .Net standard 2.0.
This library makes use of the ONVIF web service. The WSDL files can be found here : https://www.onvif.org/profiles/specifications/

In Visual Studio 15.7.6, when i try to add a reference to "https://www.onvif.org/ver10/events/wsdl/event.wsdl", this error occurs : 

> Error : An item with the same key has already been added. Key: CreatePullPoint

So, i've tried to use the Dotnet svcutil tool 1.0.2,
`dotnet svcutil https://www.onvif.org/ver10/events/wsdl/event.wsdl`, but the same error occured.

What's going on?

**Comment by mlacouture** [comment] 2018-08-12 04:13
Hi @ErosGuil 
Thank you for reporting this issue.  I have confirmed this is a bug in our code and will consider a fix for the upcoming release of the tool.

**Comment by mlacouture** [comment] 2018-08-23 19:31
Hi @ErosGuil, investigating dup issue #3129 I just realized you may be able to work around this problem if you can't wait for the fix which will be available in the next release of the tool.  

The problem happens when the same name is used for a port type (contract) and a composite type, in your case the 'CreatePullPoint)'.  You may be able to work around it by changing the name of the port type (and associated usage) to 'ICreatePullPoint)' for instance.

hope this helps,

**Comment by jeremyVignelles** [comment] 2018-08-23 19:43
Thanks @mlacouture for the feedback.

How are we supposed to change the Port type? We can't change anything on ONVIF's side, so is there a magic option somewhere in the client side?

When is the next release expected to be shipped?

One last question : Could you try the tool against all the ONVIF's WSDL? I think its a good example of a complex real-life WCF. Maybe it would be nice to have those wsdl in some regression tests. What so you think about it?

**Comment by mlacouture** [comment] 2018-08-23 19:55
@jeremyVignelles , regarding the workaround, I was thinking about editing the downloaded WSDL file.  However, I didn't try it myself, it may not work ...

We are working hard on the next release, I can't commit on a day yet but it should be within a few weeks.

Regarding the regression tests, it is a good idea; however, because of security concerns among others, we can't use external services for our internal testing.

stay tuned ...

**Comment by jeremyVignelles** [comment] 2018-08-23 19:58
You can't connect to external services, but would you be able to download the .wsdl files and work offline?

**Comment by jeremyVignelles** [comment] 2018-08-23 20:44
The thing is : we need to rely on an Onvif service, and only for that, we are stuck on .net framework whereas all our other libraries are already .net core. We already tried to add reference in the past, without success, and we were told at that time that everything would be fixed with the next release.
Trying a few month later and finding other issues was quite frustrating, and we would like to avoid that situation again, hence the request.

**Comment by mlacouture** [comment] 2018-08-24 17:14
Yes, this is actually something we've been evaluating/considering doing … thank you for the suggestion, your input makes the case more compelling :).

**Comment by mlacouture** [comment] 2018-08-29 20:02
Hi @ErosGuil and @jeremyVignelles 
[dotnet-svcutil v1.0.3 ](https://www.nuget.org/packages/dotnet-svcutil/1.0.3)is now available and it contains a fix for this issue.
thanks,

**Closed by mlacouture** 2018-08-29 20:02 UTC
Labels: bug, tooling

**Comment by mlacouture** [comment] 2018-08-29 20:05
BTW @jeremyVignelles, we have regression tests for some issues related to Onvif services but we won't be able to add tests for all the Onvif services.  My suggestion is for you to test the services you are concerned about and if there's any issues report them to us.
