### ISSUE TITLE
dotnet-svcutil: Inconsistent class generation behavior of not referenced types

### ISSUE THREAD

**Issue by Serotonindude** [dotnet/wcf#4742] opened 2021-10-14 15:20 UTC
**Description**

Hi, 
I've got a problem with the dotnet-svcutil 2.0.3 (seems to be the same in 2.0.1). 

When I generate the classes using only the SignatureService.wsdl file, the not directly referenced type _DetailedSignatureReportType_ is generated as a class.
I need this class, as the IndividualReportType.Details member (which is of type _AnyType_, which is not directly related to _DetailedSignatureReportType_) MAY be of such a type or anything else, for details see oasis-dssx-1.0-profiles-vr-cd1.xsd.
On the otherhand, as soon as I add another WSDL (for example AuthSignatureService.wsdl) to be generated together with the SignatureService.wsdl, the _DetailedSignatureReportType_ is not generated anymore.

So I got some questions:
1. Are not referenced types supposed to be generated anyway? If not, I cannot find an option of the svcutil which would allow me to force the creation of such types. How would one go about this?
2. Whether the answer is yes or no, the result should be consistent?! Seems like a bug to me.

**Reproduction**
I've added a zip file with all the needed wsdl and xsd files and an additional README.txt file which also contains the parameters I've used. Just try to generate the conn/SignatureService.wsdl on its own and another time together with the AuthSignatureService.wsdl and then look for _DetailedSignatureReportType_ in the generated file.

**Expected behavior**
I'd expect the not directly referenced types to be generated as well in any case or if not, to have the option to include those.

Kind regards

[README.txt](https://github.com/dotnet/wcf/files/7347365/README.txt)
[svcutil issue.zip](https://github.com/dotnet/wcf/files/7347367/svcutil.issue.zip)

**Comment by Serotonindude** [comment] 2022-03-30 18:14
anything new about this one?

**Comment by HongGit** [comment] 2022-04-13 02:27
@imcarolwang please see if this is a regression

**Comment by imcarolwang** [comment] 2022-04-13 09:46
Hi @Serotonindude It turns out that the order of the input wsdl files matters for how the code is generated. So for the given repro parameter, when generating code for both WSDLs,  adjust inputs file list order by placing  line `conn/SignatureService.wsdl` before `conn/AuthSignatureService.wsdl`, then `DetailedSignatureReportType` can be generated.

**Comment by Serotonindude** [comment] 2022-04-13 11:12
> Hi @Serotonindude It turns out that the order of the input wsdl files matters for how the code is generated. So for the given repro parameter, when generating code for both WSDLs, adjust inputs file list order by placing line `conn/SignatureService.wsdl` before `conn/AuthSignatureService.wsdl`, then `DetailedSignatureReportType` can be generated.

hi @imcarolwang, sounds like a decent work around... will this be fixed to work in all circumstances?

**Comment by imcarolwang** [comment] 2022-04-14 09:38
Thank you for the response. Since this doesn't appear to be a regression issue comparing with Svcutil in .NetFramework and there's a workaround, this one got lower priority than other broader impacted issues. I'm closing it for now, feel free to reactivate or open a new issue if you have additional data or details that will help us appropriately reprioritize this issue.

**Closed by imcarolwang** 2022-04-14 09:38 UTC
