### ISSUE TITLE
System.InvalidOperationException: System.Xml.Linq.XElement cannot be used as: 'xml text'

### ISSUE THREAD

**Issue by aritsa** [dotnet/wcf#2332] opened 2017-10-06 05:54 UTC
Hi. Im running into the same problem as #2150 .

> System.InvalidOperationException: There was an error reflecting type 'ZregService.ManifestType'. ---> System.InvalidOperationException: There was an error reflecting property 'Reference'. ---> System.InvalidOperationException: There was an error reflecting type 'ZregService.ReferenceType'. ---> System.InvalidOperationException: There was an error reflecting property 'DigestMethod'. ---> System.InvalidOperationException: There was an error reflecting type 'ZregService.DigestMethodType'. ---> System.InvalidOperationException: There was an error reflecting property 'Any'. ---> System.InvalidOperationException: There was an error reflecting type 'System.Xml.Linq.XElement'. ---> System.InvalidOperationException: System.Xml.Linq.XElement cannot be used as: 'xml text'.
>    at System.Xml.Serialization.XmlReflectionImporter.CheckContext(TypeDesc typeDesc, ImportContext context)
>    at System.Xml.Serialization.XmlReflectionImporter.ImportSpecialMapping(Type type, TypeDesc typeDesc, String ns, ImportContext context, RecursionLimiter limiter)
>    at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
>    --- End of inner exception stack trace ---

Here is the wsdl
[wsdl.zip](https://github.com/dotnet/wcf/files/1361624/wsdl.zip)

And here is the generated reference
[Reference.zip](https://github.com/dotnet/wcf/files/1361626/Reference.zip)

Seems like it does  not like the System.Xml.Linq.XElement Any properties like in:

```

    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil","0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class DigestMethodType
    {
        
        private System.Xml.Linq.XElement[] anyField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm
        {
            get
            {
                return this.algorithmField;
            }
            set
            {
                this.algorithmField = value;
            }
        }
    }

```

**Comment by aritsa** [comment] 2017-10-06 06:34
Update:
Removing all 
```
public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
```
from the reference.cs made the service callable. But I guess that's not how it should work.

**Comment by RomanKernSW** [comment] 2017-10-06 06:50
remove every time manually after the proxy has been generated/updated? Its a workaround but not the solution of the problem

**Comment by aritsa** [comment] 2017-10-06 07:30
@RomanKernSW: i know. only a workaround. but i thought it might be useful to know if you cannot wait for a fix.

**Comment by hongdai** [comment] 2017-10-06 15:54
@aritsa Thanks for providing the reproduce wsdl! We will try to reproduce the issue locally and investigate the root cause.
-Hong Dai

**Comment by zhenlan** [comment] 2017-10-20 18:25
@shmao can you please sync with @hongdai and take a look?

**Comment by shmao** [comment] 2017-10-31 18:12
The code generated by Add Service Reference (ASR) code is different from the code generated by the connected service. The code generated by ASR uses `System.Xml.XmlElement` or `System.Xml.XmlNode` instead of `System.Xml.Linq.XElement`. And ASR code works. It might be a bug in the connected service.

Replacing all `System.Xml.Linq.XElement` with `System.Xml.XmlNode` in the generated code could be a workaround for this.

**Comment by ps2goat** [comment] 2019-01-15 15:55
I can confirm that svcutil version 1.0.4 generated a service class that used `XElement` instead of `XmlNode`.  I [wrongly] thought this was the new way of doing it in dotnet core 2, so I updated my code to match.  It broke with a reflection error: `there was a problem reflecting type <property>`, where property was of type `XElement`.

I updated the generated service to use XmlNode, and reverted my code changes back to XmlNode, and the service is working, again.  How long before this is fixed?  It's not going to impact me much, going forward, but the issue was confusing and this fix is not the best solution (e.g., "fix the generated code every time you regenerate it).

**Comment by dasetser** [comment] 2019-02-14 23:31
@ps2goat This is on our backlog to fix. The root cause is understood, but it uncovered a few other issues that we're investigating before we make a fix. I'll update this issue once we can make a fix for it.

**Comment by dasetser** [comment] 2019-07-29 19:14
This is fixed in dotnet-svcutil 2.0.1, which is now available. It's not fixed in the UI tool (WCF Web Service Reference Provider) yet, but we plan to update it in VS 2019 16.3.

**Closed by dasetser** 2019-07-29 19:14 UTC
Labels: DotNet-SvcUtil 2.0.1, bug, tooling

**Comment by cjbush** [comment] 2019-11-06 16:55
This fix wound up breaking me because I wrote my wrapper to use XElement. Is there a way to still generate the service reference using XElement in 16.3?

**Comment by dasetser** [comment] 2019-11-08 19:30
@cjbush I'm sorry this change broke you. There is not a way to generate it using XElement in the latest version. I'd recommend installing the [dotnet-svcutil](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide) 2.0.0 and using that to generate your service reference.
