### ISSUE TITLE
mismatch between Soap WebService class Types and my dotnet core mvc App referece.cs class Types

### ISSUE THREAD

**Issue by pariaSadatHosseiny** [dotnet/wcf#3682] opened 2019-06-11 12:35 UTC
Hello ,
i have a sample dotnet core2 web Application which is Consuming a SOAP webService which is Developed by java lang . when I add the Address of mentioned wsdl , my app generates the reference.cs class but it has Error with one of the Types . 
as i understand ,  there are two main class Types  1 => "W**S**Context"  and 2=>"W**s**Context" in Server
and when dotnet wcf is generating Classes , it consider number 2 as number 1 and it makes lots of errors and Conflicts to Serialize data .
i changed the name of these two class by myself and it works Correctly, but i am thinking if i want to update this wcf should i change code every time or is there other workaround?

Thanks

**Comment by StephenBonikowsky** [comment] 2019-06-17 19:19
Thank you for reporting this @pariaSadatHosseiny 
This looks like a bug in how the tool is generating the C# code. Could you please provide us with a repro or the wsdl so we can reproduce this and do some additional investigation please?

**Comment by pariaSadatHosseiny** [comment] 2019-06-18 06:43
> Thank you for reporting this @pariaSadatHosseiny
> This looks like a bug in how the tool is generating the C# code. Could you please provide us with a repro or the wsdl so we can reproduce this and do some additional investigation please?

yes,sure . can I have your mail to send you our sample wsdl Address?

**Comment by StephenBonikowsky** [comment] 2019-06-18 16:52
You should be able to just drag and drop the wsdl right here.

**Comment by pariaSadatHosseiny** [comment] 2019-06-19 05:43
> You should be able to just drag and drop the wsdl right here.

yes, but I dont have permission to publish that in a forum Like this .it would be your kind if you contact me by my Email (p.hosseiny72@gmail.com) to send you address in private .

**Comment by pariaSadatHosseiny** [comment] 2019-06-19 13:54
> You should be able to just drag and drop the wsdl right here.

Hello Again ...
i Published a sample of our Service in following Address :

http://5.202.178.210:8080/ref-payment2/jax/merchantService?wsdl

i hope it help

**Comment by StephenBonikowsky** [comment] 2019-06-19 15:57
Thank you @pariaSadatHosseiny we will start looking into this!
@imcarolwang could you begin working on a repro please.

**Comment by imcarolwang** [comment] 2019-06-20 03:12
I can reproduce this issue using the service [address](http://5.202.178.210:8080/ref-payment2/jax/merchantService?wsdl ) @pariaSadatHosseiny provided.
The issue doesn't reproduce on project targeting to .NetFramework by running "Add ->Service Reference ...".

By comparing the generated reference.cs between .NetFramework and on .NetCore, I see:
- On .NetFramework, it correctly generated type **wsContext** and **WSContext** 
- On .NetCore, the corresponding type generated are **wsContext** and **WSContext1**

Somehow, when generating "WSContext", dotnet-svcutil checked and found there's already "wsContext" and generate "WSContext1" instead of "WSContext", this looks a code generation bug in dotnet-svcutil.
@dasetser , do you have any insight into the problem?

**Comment by pariaSadatHosseiny** [comment] 2019-06-20 07:49
> Thank you @pariaSadatHosseiny we will start looking into this!
> @imcarolwang could you begin working on a repro please.

sorry what do you mean by "could you begin working on a repro please."???

**Comment by pariaSadatHosseiny** [comment] 2019-06-20 07:54
> I can reproduce this issue using the service [address](http://5.202.178.210:8080/ref-payment2/jax/merchantService?wsdl) @pariaSadatHosseiny provided.
> The issue doesn't reproduce on project targeting to .NetFramework by running "Add ->Service Reference ...".
> 
> By comparing the generated reference.cs between .NetFramework and on .NetCore, I see:
> 
> * On .NetFramework, it correctly generated type **wsContext** and **WSContext**
> * On .NetCore, the corresponding type generated are **wsContext** and **WSContext1**
> 
> Somehow, when generating "WSContext", dotnet-svcutil checked and found there's already "wsContext" and generate "WSContext1" instead of "WSContext", this looks a code generation bug in dotnet-svcutil.
> @dasetser , do you have any insight into the problem?

yes , that is true, but in other methods which we used Wscontext some Errors are shown and if i change all WsContext to WsContext1 by hand it will work fine .But if later some changes goes into  wsdl file I should update my Reference and again change it ,but it is not the right way.

**Comment by StephenBonikowsky** [comment] 2019-06-20 16:58
Thank you @imcarolwang for the additional investigation.
@dasetser and @mconnew since it looks like this is a regression lets consider investigating this sooner.

**Comment by imcarolwang** [comment] 2019-06-21 01:29
The repro app: [issue3682.zip](https://github.com/dotnet/wcf/files/3312668/issue3682.zip).
Reference.cs was generated base on http://5.202.178.210:8080/ref-payment2/jax/merchantService?wsdl.

**Comment by pariaSadatHosseiny** [comment] 2019-07-24 03:54
Hello  @dasetser  can I Ask you if DotNet-SvcUtil 2.0.1 is going to be Released in near Future? or we have to change Our Code our Self?

**Comment by dasetser** [comment] 2019-07-24 17:10
@pariaSadatHosseiny We plan to release dotnet-svcutil 2.0.1 in the next week or so if everything goes as expected.

**Comment by dasetser** [comment] 2019-07-29 19:15
This is fixed in dotnet-svcutil 2.0.1, which is now available.

**Closed by dasetser** 2019-07-29 19:15 UTC
Labels: DotNet-SvcUtil 2.0.1, tooling

**Comment by pariaSadatHosseiny** [comment] 2019-07-30 05:03
Thank you All.

**Comment by StephenBonikowsky** [comment] 2019-07-30 17:34
https://www.nuget.org/packages/dotnet-svcutil/2.0.1
