### ISSUE TITLE
Error on Getter only auto-properties

### ISSUE THREAD

**Issue by JaWiD2** [dotnet/wcf#2287] opened 2017-09-17 00:47 UTC
Hi,
By having:
```cs
[DataContract]
public class Person
{
    [DataMember]
    public int Id { get; }
    public Person(int id)
    {
         Id = id;
    }
}
```
```cs
[DataContract]
public class Person
{
    [DataMember]
    public int Id { get;private set; }
    public Person(int id)
    {
         Id = id;
    }
}
```
on binding of getter only auto-properties, wcf throw exception but in `private set;` its fine!
both property are read-only in the outside of this class.

**Comment by zhenlan** [comment] 2017-09-19 21:29
@shmao can you take a look?

**Comment by shmao** [comment] 2017-09-19 21:57
@JaWiD2 thanks for submitting the issue. DataContractSerializer cannot serialize get-only properties. If a property is marked with [DataMember], it must have a setter. The setter being private is ok as DCS uses reflection to get the setter.

I'm closing the issue as this is by design.

**Closed by shmao** 2017-09-19 21:57 UTC
Labels: Community, serialization
