### ISSUE TITLE
WCF Client generator requires a build before it will generate code.

### ISSUE THREAD

**Issue by Joebeazelman** [dotnet/wcf#2384] opened 2017-11-14 20:18 UTC
Unlike previous versions, the client generator requires a complete build of the project before it even attempts to generate any code.  If the build fails, it fails.  Why?  Previous versions never had this requirement and even svcutil.exe generated code without any knowledge of the environment.  If there's some reason it is broken, then at the very least put up a dialog or launch a browser says "We broke the latest version and it no longer does what you expect.  After we're done playing with our hair, we might move the cheese back if we're not too tired."

I think this is a systemic problem where Microsoft hires based on interview whiteboard style questions instead of hiring people with real talent, experience and have a clue on reality.   Microsoft has the nerve to have certification exams for core competency when it has no competency itself.

**Comment by mlacouture** [comment] 2017-11-14 23:52
Hi @Joebeazelman 

You hit this problem because the WCF Web Service Reference connected service provider, unlike other tools, checks types in the current project in order to determine whether these types can be reused when generating the service reference file.  You can bypass this check by unselecting the 'reuse types' in the data types option page.

hope this helps,
Miguel Lacouture
[MSFT]

**Comment by wsnell** [comment] 2017-11-15 20:29
How does it reuse types? Are the types specific to the generated class scope or global or what?
This needs better documentation...
Thx
-Wes

**Comment by mlacouture** [comment] 2017-11-20 19:37
@wsnell, please refer to the [WCF Web Service Reference](https://github.com/dotnet/wcf/blob/master/Documentation/WCF-Web-Service-Reference-guide.md) documentation.  thanks,

**Comment by Joebeazelman** [comment] 2017-12-03 03:15
Please don't baloney me after all the trials and tribulations I have gone through!  This crappy malware requires a build even if you explicitly tell it not to reuse types! 

[12/2/2017 10:09:46.057 PM] Adding Microsoft WCF Web Service Reference Provider - Preview to the project.
[12/2/2017 10:09:46.057 PM] Importing web service metadata ...
[12/2/2017 10:09:46.075 PM] Number of services found: 1
[12/2/2017 10:09:46.082 PM] Restoring NuGet packages ...
[12/2/2017 10:09:47.551 PM] Building solution ...
[12/2/2017 10:09:50.769 PM] Error:The solution cannot be built, please try to rebuild the solution and fix any build problems.
[12/2/2017 10:09:50.832 PM] Failed adding Microsoft WCF Web Service Reference Provider - Preview to the project.

**Comment by mlacouture** [comment] 2017-12-04 20:40
@Joebeazelman, you are using an old version of the tool.  This was fixed with the release of the tool in Visual Studio 2017 15.5 Preview 2.  Will you be able to try VS 2017 15.5 Preview 2 or a more resent release? you can find more information in the [VS 2017 Release Notes](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes#WCFTools).

thanks,

**Comment by mlacouture** [comment] 2017-12-05 18:35
[VS 2017 15.5 RTW](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes#WCFTools) is now available.

thanks again for helping us deliver a better Visual Studio!

**Comment by Joebeazelman** [comment] 2017-12-12 18:02
I tried this on the latest build.  Same issue. It was never fixed!  It also ignores my setting for using generics instead of arrays.

Importing web service metadata ...
Number of service endpoints found: 1
Restoring NuGet packages ...
Building solution ...
Scaffolding service reference code ...
Restoring NuGet packages for bootstrapper ...

**Comment by mlacouture** [comment] 2017-12-12 19:34
@Joebeazelman, I'll take a look ...

**Comment by mlacouture** [comment] 2017-12-16 04:18
@Joebeazelman, I'm unable to reproduce this issue, I'm using VS 2017 v15.5.  Can you check the version of the tool by looking at the connectedservice.json file added to your project under the Connected Services -> Your_service_reference_folder? thanks,

**Comment by Joebeazelman** [comment] 2017-12-16 14:24
OK. It doesn't require a build, if you turn off reuse types, but even so, why require a build when you can query VS Studio for  the same way intellisense and resharper do?  Also, the generic List<> isn't supported.

**Comment by mlacouture** [comment] 2017-12-18 20:17
thanks for confirming.  The build is required so that types in the user's solution can be can be considered for type reuse when generating the proxy code.  We will consider the pros/cons of not building the user's solution.  thank you for your feedback!

**Comment by mlacouture** [comment] 2018-01-19 02:26
@Joebeazelman, we have decided to change our design and fix this issue, the tool will no longer build the user's project, it will reuse types from referenced projects provided they are available (projects have been built before).  A fix for this will be available in VS 2017 v15.6 Preview 3.

**Comment by mlacouture** [comment] 2018-01-26 18:29
Hi @Joebeazelman 
[Visual Studio 2017 v15.6 Preview 3 is now available](https://www.visualstudio.com/vs/preview/), please give it a try.
thank you!

**Closed by mlacouture** 2018-01-26 18:29 UTC
Labels: Community, Design Discussion, tooling
