### ISSUE TITLE
Message Transmission Optimization Mechanism (MTOM) message encoding is not supported

### ISSUE THREAD

**Issue by ssashok10** [dotnet/wcf#2833] opened 2018-05-08 17:40 UTC
I am using Azure Function (C#) which is calling a .NET standard library to call an external WCF service and I am getting the below error saying that MTOM is not supported. Is there any work around to use MTOM message encoding with Azure Functions and .NET standard library? We are calling an external service and we don't have any control on it.

"System.PlatformNotSupportedException
  HResult=0x80131539
  Message=The Message Transmission Optimization Mechanism (MTOM) message encoding is not supported on this platform.
  Source=System.Private.DataContractSerialization
  StackTrace:
   at System.Xml.XmlDictionaryReader.CreateMtomReader(Stream stream, Encoding[] encodings, String contentType, XmlDictionaryReaderQuotas quotas, Int32 maxBufferSize, OnXmlDictionaryReaderClose onClose)
   at System.Xml.XmlDictionaryReader.CreateMtomReader(Stream stream, Encoding[] encodings, String contentType, XmlDictionaryReaderQuotas quotas)
   at ..."

Here are the platform information,
Microsoft.NET.Sdk.Functions (1.0.13)
.NET Standard Library 2.0
System.ServiceModel.Primities 4.4.2
System.ServiceModel.Http 4.4.2

**Comment by Lxiamail** [comment] 2018-05-18 18:36
This is a large feature request. We put it into backlog for now.

**Comment by zhenlan** [comment] 2018-06-12 16:49
Request for MTOM is tracked in #1810.

Duplicate of #1810.

**Closed by zhenlan** 2018-06-12 16:49 UTC
Labels: feature request

**Comment by bellons91** [comment] 2023-02-09 16:14
Hello there. Any news on this issue?

Do you have a workaround?
