### ISSUE TITLE
OperationFormatter encountered an invalid Message body.

### ISSUE THREAD

**Issue by fccookj** [dotnet/wcf#2446] opened 2017-12-13 13:54 UTC
I'm trying to consume a WCF service from a .NET Standard library.  

I can consume the service and get the expected methods when adding the service reference to a console application through the built-in service reference tool but I run into this issue when adding the reference via the WCF Reference Provider in VS2017 v15.5.  It seems that the regular GetData method is missing but I do see the GetDataAsync version of the method.  

This is the error:  Unhandled Exception:
System.ServiceModel.FaultException`1[[System.ServiceModel.ExceptionDetail, System.ServiceModel, Version=2.0.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]: Error in deserializing body of request message for operation 'GetData'. OperationFormatter encountered an invalid Message body. Expected to find node type 'Element' with name 'GetData' and namespace 'http://tempuri.org/'. Found node type 'Element' with name 'GetDataAsync' and namespace 'http://tempuri.org/' occurred

Thanks!

**Comment by Joebeazelman** [comment] 2017-12-13 23:35
Is it possible for you to post your wsdl here?  You can upload it or attach it via drag and drop.

**Comment by fccookj** [comment] 2017-12-14 02:09
The message shows up when running the proxy and these are in separate projects.  The non .NET Standard projects seem to see everything as they should using the old service reference.  I'll try recreating the .NET Standard project though once more.  If that doesn't work then I'll post the WSDL.  Also, do you have any examples going from creating the service, using the WCF provider for the reference, and consuming it in code?  

Thanks,
Josh

**Comment by PhilPJL** [comment] 2017-12-29 16:37
I get the same issue. Just posted a duplicate bug https://github.com/dotnet/wcf/issues/2463. 
There's nothing wrong with the service.  Referencing it from a standard .NET project or SoapUI works fine (and has done for years).

**Comment by zhenlan** [comment] 2018-01-10 03:19
@fccookj, if you had this issue in a Xamarin project, I believe it has the same root cause as #2463. It's because Xamarin/mono implementation does not support task-based WCF async methods.

Duplicate of #2463.

**Closed by zhenlan** 2018-01-10 03:19 UTC
