### ISSUE TITLE
Can't update service reference unless I delete the old service reference and remove any references to said service in the code base.

### ISSUE THREAD

**Issue by djseng** [dotnet/wcf#2059] opened 2017-07-11 21:12 UTC
When I need to update a service reference the only way I've been able to successfully do that is to delete the old connected service and remove any references to that service in the code base.

If I try just "Adding a new connected service" pointing at the same service with the same namespace then the operations just sits and spins.

If I just delete the old connected service and then try re-adding a new connected service pointing at the same service with the same namespace I will fail because there are build errors in the project -- because I just deleted the old connected service.

I have resorted first deleting the old reference and then commenting out or excluding files that reference the service and ensuring that the project builds before "refreshing" the service. 

... this is a huge pain. :'(

**Comment by zhenlan** [comment] 2017-07-21 20:07
@djseng thanks for the feedback. I do see it can be painful without update support sometimes. This is something on our backlog. I will dup this issue to #1753 for easier tracking.

> If I try just "Adding a new connected service" pointing at the same service with the same namespace then the operations just sits and spins.

I just tried a simple service and it worked for me. @mlacouture also mentioned in #1753 this should work. Can you elaborate what errors you see?

Duplicate of #1753

**Comment by djseng** [comment] 2017-07-21 20:14
It just hangs for me, I don't see anything otherwise.

At present I'm just using the svcutil on the command line to refresh.


   `svcutil url /o:./out.cs /n:*,targetns /ct:System.Collections.Generic.List`1 /noConfig`

**Comment by zhenlan** [comment] 2017-07-24 23:25
@djseng, thanks for the information. We'll have to take a further look.

**Comment by zhenlan** [comment] 2017-10-10 01:21
Close this as we are using #1753 to track the "update service reference" work.

**Closed by zhenlan** 2017-10-10 01:21 UTC
Labels: Community, feature request, tooling
