### ISSUE TITLE
dotnet-svcutil System.Guid

### ISSUE THREAD

**Issue by jimmygilles** [dotnet/wcf#2902] opened 2018-05-25 20:50 UTC
Hello,

I have a web service with properties of type "Guid".
But when I use the tool dotnet-svcutil to generate the classes, the "Guid" types are converted to string.

Is it a normal behaviour ? Is it possible to pass a parameter to the tool to keep the Guid types ?

Thank you very much.

**Comment by gfoidl** [comment] 2018-05-30 10:55
> Is it a normal behaviour ?

I can't reproduce this.

For instance:
```c#
using System;
using System.ServiceModel;

namespace WcfService1
{
    [ServiceContract(Namespace = "http://gfoidl.at/test/")]
    public interface IMyService
    {
        [OperationContract]
        Guid GetId();
    }
}
```
produces
```c#
// ...
[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://gfoidl.at/test/", ConfigurationName="IMyService")]
public interface IMyService
{

    [System.ServiceModel.OperationContractAttribute(Action="http://gfoidl.at/test/IMyService/GetId", ReplyAction="http://gfoidl.at/test/IMyService/GetIdResponse")]
    System.Threading.Tasks.Task<System.Guid> GetIdAsync();
}
// ...
```
So a correct generated class.
The tool also generates a correct client-code when other "primitive" tpyes are used -- whether direct as argument or as part of a class. So
```c#
public class MyModel
{
    public Guid     Id        { get; set; }
    public DateTime TimeStamp { get; set; }
}
```
also works.

> I have a web service with properties of type "Guid".

Maybe the web service has incomplete definition of the messages. The WSDL for above example shows that a `Guid` is used:
```xml
<xs:element minOccurs="0" name="GetIdResult" type="q1:guid" xmlns:q1="http://schemas.microsoft.com/2003/10/Serialization/"/>
```

Please check your WSDL, to see if there's any definition of GUID.

<details>
    <summary>Full WSDL for reference</summary>

    ```xml
    <?xml version="1.0" encoding="utf-8"?>
    <wsdl:definitions name="MyService" targetNamespace="http://gfoidl.at/test/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:i0="http://tempuri.org/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://gfoidl.at/test/" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing">
        <wsdl:types>
            <xs:schema elementFormDefault="qualified" targetNamespace="http://gfoidl.at/test/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
                <xs:import namespace="http://schemas.microsoft.com/2003/10/Serialization/"/>
                <xs:element name="GetId">
                    <xs:complexType>
                        <xs:sequence/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="GetIdResponse">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="0" name="GetIdResult" type="q1:guid" xmlns:q1="http://schemas.microsoft.com/2003/10/Serialization/"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:schema>
            <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/">
                <xs:element name="anyType" nillable="true" type="xs:anyType"/>
                <xs:element name="anyURI" nillable="true" type="xs:anyURI"/>
                <xs:element name="base64Binary" nillable="true" type="xs:base64Binary"/>
                <xs:element name="boolean" nillable="true" type="xs:boolean"/>
                <xs:element name="byte" nillable="true" type="xs:byte"/>
                <xs:element name="dateTime" nillable="true" type="xs:dateTime"/>
                <xs:element name="decimal" nillable="true" type="xs:decimal"/>
                <xs:element name="double" nillable="true" type="xs:double"/>
                <xs:element name="float" nillable="true" type="xs:float"/>
                <xs:element name="int" nillable="true" type="xs:int"/>
                <xs:element name="long" nillable="true" type="xs:long"/>
                <xs:element name="QName" nillable="true" type="xs:QName"/>
                <xs:element name="short" nillable="true" type="xs:short"/>
                <xs:element name="string" nillable="true" type="xs:string"/>
                <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte"/>
                <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt"/>
                <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong"/>
                <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort"/>
                <xs:element name="char" nillable="true" type="tns:char"/>
                <xs:simpleType name="char">
                    <xs:restriction base="xs:int"/>
                </xs:simpleType>
                <xs:element name="duration" nillable="true" type="tns:duration"/>
                <xs:simpleType name="duration">
                    <xs:restriction base="xs:duration">
                        <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/>
                        <xs:minInclusive value="-P10675199DT2H48M5.4775808S"/>
                        <xs:maxInclusive value="P10675199DT2H48M5.4775807S"/>
                    </xs:restriction>
                </xs:simpleType>
                <xs:element name="guid" nillable="true" type="tns:guid"/>
                <xs:simpleType name="guid">
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/>
                    </xs:restriction>
                </xs:simpleType>
                <xs:attribute name="FactoryType" type="xs:QName"/>
                <xs:attribute name="Id" type="xs:ID"/>
                <xs:attribute name="Ref" type="xs:IDREF"/>
            </xs:schema>
        </wsdl:types>
        <wsdl:message name="IMyService_GetId_InputMessage">
            <wsdl:part name="parameters" element="tns:GetId"/>
        </wsdl:message>
        <wsdl:message name="IMyService_GetId_OutputMessage">
            <wsdl:part name="parameters" element="tns:GetIdResponse"/>
        </wsdl:message>
        <wsdl:portType name="IMyService">
            <wsdl:operation name="GetId">
                <wsdl:input wsaw:Action="http://gfoidl.at/test/IMyService/GetId" message="tns:IMyService_GetId_InputMessage"/>
                <wsdl:output wsaw:Action="http://gfoidl.at/test/IMyService/GetIdResponse" message="tns:IMyService_GetId_OutputMessage"/>
            </wsdl:operation>
        </wsdl:portType>
        <wsdl:binding name="BasicHttpBinding_IMyService" type="tns:IMyService">
            <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
            <wsdl:operation name="GetId">
                <soap:operation soapAction="http://gfoidl.at/test/IMyService/GetId" style="document"/>
                <wsdl:input>
                    <soap:body use="literal"/>
                </wsdl:input>
                <wsdl:output>
                    <soap:body use="literal"/>
                </wsdl:output>
            </wsdl:operation>
        </wsdl:binding>
        <wsdl:service name="MyService">
            <wsdl:port name="BasicHttpBinding_IMyService" binding="tns:BasicHttpBinding_IMyService">
                <soap:address location="http://localhost:64025/MyService.svc"/>
            </wsdl:port>
        </wsdl:service>
    </wsdl:definitions>
    ```
</details>

**Comment by mlacouture** [comment] 2018-06-15 19:36
thank you @gfoidl for your help.  @jimmygilles, let us know if you still need help.  closing for now.

**Closed by mlacouture** 2018-06-15 19:36 UTC
Labels: needs more info, tooling

**Comment by srb-milestone** [comment] 2020-02-05 18:35
I just reproduced this behavior with one our our service (but not with others). So apparently it`s dependent on the wsdl...
