### ISSUE TITLE
Adding a Connected Service gives an MSBuild error because SvcUtilBootstrapper.csproj is incomplete

### ISSUE THREAD

**Issue by StingyJack** [dotnet/wcf#1866] opened 2017-04-24 11:38 UTC
I have a solution with a few projects, one of which has a pre-build event to run a bit of code generation. When compiling in VS2017, this works fine, however when trying to add a connected service to that project it fails.

It looks like whatever is making the svcutil bootstrapper is not adding any of the other projects that are in the solution, especially not ones with project based references or that are marked as dependencies to guarantee a correct build order.

VS output window
``` 
[4/24/2017 7:29:56.164 AM] Adding Microsoft WCF Web Service Reference Provider - Preview to the project.
[4/24/2017 7:29:56.170 AM] Scaffolding Code ...
[4/24/2017 7:30:13.948 AM] Error:Error: Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.
  The system cannot find the path specified.
C:\Program Files\dotnet\sdk\1.0.3\Microsoft.Common.CurrentVersion.targets(1263,5): error MSB3073: The command ""utils\CsPocoToTs\bin\Debug\CsToTs.exe" "src\CsToTs.config.json"" exited with code 3. [C:\Users\Andrew\Documents\Visual Studio 2017\Projects\APAS\Trunk\src\Apas.UI\Apas.UI.csproj]
C:\Program Files\dotnet\sdk\1.0.3\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error : Cannot find project info for 'C:\Users\Andrew\Documents\Visual Studio 2017\Projects\APAS\Trunk\src\Apas.UI\Apas.UI.csproj'. This can indicate a missing project reference. [C:\Users\Andrew\AppData\Local\Temp\WCFConnectedService\2017_Apr_24_07_29_56\svcutil_bootstrap\SvcUtilBootstrapper.csproj]
Build FAILED.
C:\Program Files\dotnet\sdk\1.0.3\Microsoft.Common.CurrentVersion.targets(1263,5): error MSB3073: The command ""utils\CsPocoToTs\bin\Debug\CsToTs.exe" "src\CsToTs.config.json"" exited with code 3. [C:\Users\Andrew\Documents\Visual Studio 2017\Projects\APAS\Trunk\src\Apas.UI\Apas.UI.csproj]
C:\Program Files\dotnet\sdk\1.0.3\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error : Cannot find project info for 'C:\Users\Andrew\Documents\Visual Studio 2017\Projects\APAS\Trunk\src\Apas.UI\Apas.UI.csproj'. This can indicate a missing project reference. [C:\Users\Andrew\AppData\Local\Temp\WCFConnectedService\2017_Apr_24_07_29_56\svcutil_bootstrap\SvcUtilBootstrapper.csproj]
    0 Warning(s)
    2 Error(s)
Time Elapsed 00:00:02.08
An error occurred while bootstrapping svcutil. This usually happens when processing references.  You might be able to work around this problem by not providing reference parameters, and manually removing any types redefined in the generated proxy code.

Failed to generate service reference.
[4/24/2017 7:30:14.041 AM] Failed adding Microsoft WCF Web Service Reference Provider - Preview to the project.

```
SvcUtilBootstrapper.csproj in the temp folder named above
``` 
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="dotnet-svcutil" Version="0.5.10406.1201-preview"></PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="C:\Users\Andrew\Documents\Visual Studio 2017\Projects\APAS\Trunk\src\Apas.UI\Apas.UI.csproj" />
  </ItemGroup>
</Project>
```

**Comment by hongdai** [comment] 2017-04-26 16:02
@StingyJack Sorry to hear you are running into issues. 

Could you send me the project definition of Apas.UI.csproj? I will try to repro the issue locally to investigate.

Thanks,
Hong Dai

**Comment by StingyJack** [comment] 2017-04-27 22:35
With all the weird problems in VS 2017 + netcore and the frustration stemming from the colossal chain of  fail that starts with "report a problem", your offer to look it over is **much** appreciated. 

Here's the proj file. if you need more I can zip and email the whole solution. 
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyTitle>Apas.UI</AssemblyTitle>
    <AssemblyName>Apas.UI</AssemblyName>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <OutputType>Exe</OutputType>
    <PackageId>Apas.UI</PackageId>
    <RuntimeIdentifiers>win7-x64;win7-x64;ubuntu.16.04-x64</RuntimeIdentifiers>
    <RuntimeFrameworkVersion>1.1.1</RuntimeFrameworkVersion>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <PreBuildEvent>REM "..\..\..\..\..\utils\CsPocoToTs\bin\$(ConfigurationName)\CsToTs.exe" "..\..\..\..\..\src\CsToTs.config.json"</PreBuildEvent>
    <PackageTargetFallback>portable-net45+win8</PackageTargetFallback>
    <!--<PackageTargetFallback>portable-net45+win8</PackageTargetFallback>-->
    <!--<PackageTargetFallback>$(PackageTargetFallback);dotnet5.6;portable-net45+win8</PackageTargetFallback>-->
  </PropertyGroup>
  <PropertyGroup>
    <!-- Makes the TypeScript compilation task a no-op -->
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="wwwroot/js\apas.js" />
    <Content Remove="wwwroot/js\core.js" />
    <Content Remove="wwwroot/js\jquery-ui.js" />
    <Content Remove="wwwroot/js\jquery-ui.min.js" />
    <Content Remove="wwwroot/js\jquery.js" />
    <Content Remove="wwwroot/js\jquery.min.js" />
    <Content Remove="wwwroot/js\jquery.min.map" />
    <Content Remove="wwwroot/js\jquery.slim.js" />
    <Content Remove="wwwroot/js\jquery.slim.min.js" />
    <Content Remove="wwwroot/js\jquery.slim.min.map" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="images\dist\" />
    <Folder Include="scripts\cs_src\" />
    <Folder Include="scripts\dist\" />
    <Folder Include="scripts\dist\" />
    <Folder Include="scripts\dist\" />
    <Folder Include="scripts\src\" />
    <Folder Include="scripts\test\" />
    <Folder Include="styles\dist\" />
    <Folder Include="wwwroot\css\" />
    <Folder Include="wwwroot\images\" />
    <Folder Include="wwwroot\js\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\favicon.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.1.0" />
    <PackageReference Include="Node.js" Version="5.3.0" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="Views\_ViewStart.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Connected Services" />
  </ItemGroup>

</Project>
```

**Comment by hongdai** [comment] 2017-06-05 00:57
@StingyJack Could you provide below data to help the investigation?
1) Do you still hit the error after disable the prebuild event?
2) I don't see any project reference dependency in your csproj.  You mentioned that "svcutil bootstrapper is not adding any of the other projects that are in the solution". Could you explain?

Thanks,
Hong

**Comment by StingyJack** [comment] 2017-06-05 19:04
If you scroll all the way to the right in the first code example, you can see the temp file I am talking about. Its in there that the reference is missing.
```
C:\Program Files\dotnet\sdk\1.0.3\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): 
  error : Cannot find project info for 'C:\Users\Andrew\Documents\Visual Studio 
  2017\Projects\APAS\Trunk\src\Apas.UI\Apas.UI.csproj'. 
  This can indicate a missing project reference. 
  [C:\Users\Andrew\AppData\Local\Temp\WCFConnectedService\
   2017_Apr_24_07_29_56\svcutil_bootstrap\SvcUtilBootstrapper.csproj]
```

There have been a few updates to some of the dependencies (microsoft.composition 1.0.27 specifically) that have resolved several similar issues with scaffolding etc. This one is corrected as well I think.

**Comment by hongdai** [comment] 2017-06-09 18:44
@StingyJack Great to hear the issue is corrected now. I will close the issue. Please reopen if needed.

**Closed by hongdai** 2017-06-09 18:44 UTC
Labels: Community, tooling
