### ISSUE TITLE
Unable to generate deps.json, it may have been already generated. You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d <toolname>": C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj

### ISSUE THREAD

**Issue by AlexFauteux** [dotnet/wcf#4175] opened 2020-02-27 18:52 UTC
**Describe the bug**
I cannot connect a web service to my .net core application which otherwise connects to .net framework applications. The project is on an internal network which doesn't have access to the internet. The Web Service is also internal and works well with .Net Framework applications but seem to not work with .Net core applications. What can I do to try and remedy the situation?

![Error](https://user-images.githubusercontent.com/26582964/75476074-ef543c00-5967-11ea-8fcf-4304ca1f72b4.PNG)

![Error2](https://user-images.githubusercontent.com/26582964/75476085-f54a1d00-5967-11ea-96d2-50e623aba985.PNG)

**Comment by StephenBonikowsky** [comment] 2020-02-28 22:12
@AlexFauteux Thanks for reporting this.
@dasetser Will provide you with some additional guidance to be able to run the local tool and get more info on the error.

**Comment by dasetser** [comment] 2020-03-02 23:15
@AlexFauteux This looks like a duplicate of #3391, so you can check that issue for previous reports and what they did to fix it,. This is an error that the dotnet SDK reports if something goes wrong when installing/running a local CLI tool (which the WCF Connected Service does internally with dotnet-svcutil).  

In your second screenshot you were able to successfully use dotnet-svcutil 2.x as a global tool from the command line. You can simply use this command line tool as a workaround, it appears to be running as expected. If you want to investigate why this error is happening I would suggest following the instructions from [here](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil1x) to install and run the 1.x version of dotnet-svcutil, and you can add the -d to get the debug output. One main difference between 1.x and 2.x for dotnet-svcutil is that 1.x is used as a local CLI tool and 2.x is used as a global CLI tool. Since this error is specific to local CLI tools you'll need to use a 1.x version (or look into the details in my latest reply on #3391 for more information including how you could install 2.x as a local CLI tool).

**Comment by AlexFauteux** [comment] 2020-03-03 15:52
1st I noticed that my .Net Core 3.0 SDK is corrupted...
2nd I started the CLI call of svcutil. There's an error with the service certificate and asks for confirmation then does nothing after I've agreed to continue.

The corruption of the SDK might be the cause of the problem here.

**Comment by dasetser** [comment] 2020-03-04 19:57
@AlexFauteux Your .NET Core SDK being corrupted could definitely cause this kind of issue. Since this sounds like it's likely a problem with that rather than dotnet-svcutil or a WCF package, I'm marking this issue as closed. Let me know if you find that this error is not related to the SDK being corrupted and is something the tool is doing wrong, and we can reopen this issue.

**Closed by dasetser** 2020-03-04 19:57 UTC
Labels: needs more info, tooling
