### ISSUE TITLE
Escaping ampersands (&) on generated requests

### ISSUE THREAD

**Issue by okarlsson** [dotnet/wcf#3643] opened 2019-05-16 12:32 UTC
I'm having issues with strings containing ampersands in my client generated from dotnet-svcutil.

When I recieve a response through the client all ampersands are serialized as 

``` 
<Users xsi:type=\"xsd:string\">John &amp; Jane</Users>
```

When i extract the value from the request in my code it has been deserialized as an ampersand
```
UserResponse users  = await GetUsersAsync()

users.Names = "John & Jane"
```

In a later stage i need to send the value of the users back like this
```
await SetUsersAsync(users.Names);
```

When i intercept the generated soap request I can see that the ampersand has not been escaped 
``` 
public class MyMessageInspector : IClientMessageInspector
    {
        public void AfterReceiveReply(ref Message reply, object correlationState)
        {
            var xml = reply.ToString(); // This shows <Users xsi:type=\"xsd:string\">John &amp; Jane</Users>
        }

        public object BeforeSendRequest(ref Message request, IClientChannel channel)
        {
            var xml = request.ToString(); // This shows <Users xsi:type=\"xsd:string\">John & Jane</Users>

            return null;
        }
    }

```

This causes the whole request to fail in the connected service. From the information I've found online the ampersand should be converted to `&amp;` by the serializer. I could convert the value myself, but since I'm only returning a value I got from the soap client, I would have to check and convert every single string that is returned back.

Do you have any suggestions on how I could configure the generated client to automatically escape ampersands?

**Comment by StephenBonikowsky** [comment] 2019-05-29 22:17
Thank you @okarlsson 
This issue is the same root cause as #2889.
Will use #2889 as the primary issue and close this one.

**Closed by StephenBonikowsky** 2019-05-29 22:17 UTC
