### ISSUE TITLE
Not available operations

### ISSUE THREAD

**Issue by diegoviscovig** [dotnet/wcf#1500] opened 2016-09-01 19:19 UTC
In this WSDL awshomo.afip.gov.ar/padron-puc-ws/services/select.ContribuyenteNivel10SelectServiceImpl?WSDL, the result reference.cs has not operation get or dummy, only configuration.
Also reference.cs not compile

**Comment by hongdai** [comment] 2016-09-13 22:55
@diegoviscovig , Which VS project you use to hit the issue? Detailed repro steps will be helpful to repro and investigate the issue.

Thanks,
Hong

**Comment by hongdai** [comment] 2016-09-22 22:09
@diegoviscovig I'm able to reproduce this issue in house. This is because we currently do not support Soap encoded operations. We are considering to support it in the future. The feature request is tracked at #1549.

**Comment by hongdai** [comment] 2016-09-28 16:41
I'm closing this issue as we have a feature request to track it. It is also reported by customer in #1517.

**Closed by hongdai** 2016-09-28 16:41 UTC
Labels: tooling
