### ISSUE TITLE
Timeout issue? (how to configure web service client).

### ISSUE THREAD

**Issue by lerudiconsulting** [dotnet/wcf#2507] opened 2018-01-19 15:21 UTC
Hi,

I am consuming a slow connected service and thus simply need to increase the timeout. In previous versions of .NET I could simply adjust timeout settings in the bindings in web.config, however, in ASP.NET Core 2 I cannot find the way to do this. Can you perhaps elaborate on how to do this as all I have found so far are unclosed issues related to this type of question?

Thanks in advance for your help!

 /Peter

**Comment by zhenlan** [comment] 2018-01-19 19:38
@lerudiconsulting thanks for raising the issue.

@mlacouture can you see what we need to change in the connected service generated code to make the configuration (programmatically) easier/possible.

**Comment by lerudiconsulting** [comment] 2018-01-19 20:13
Hi @zhenlan! 

Thanks for taking action on this! Much appreciated! Look forward to the implementation! Any projection on when this is due?

Cheers!

 /Peter

**Comment by lerudiconsulting** [comment] 2018-01-19 21:46
Hi again @zhenlan,

Am I to understand that there is a programmatic way of altering these values, only not a simplified way? If there is a codified way (even if it is not very simple) of doing this while I hold for the fix, I would appreciate it if someone shared this info with me.

Thanks again in advance!

 /Peter

**Comment by mlacouture** [comment] 2018-01-20 01:54
Hi @lerudiconsulting 

As you may know, .NET Core does not support configuration files so binding configuration needs to be done in code.

The generated proxy code provides a configuration partial method for this purpose, for example: assuming your client class is named `ServiceClient `and its namespace `ServiceReference`, you can implement the configuration method as follows:

```
namespace ServiceReference {
   public partial class ServiceClient {
       static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials) {
             // here your code
        }
    }
}
```
I hope this resolves your problem.
Miguel Lacouture

**Comment by zhenlan** [comment] 2018-02-02 23:35
@lerudiconsulting, please let us know if you need anything else. Closing for now.

**Closed by zhenlan** 2018-02-02 23:35 UTC
Labels: tooling

**Comment by ttugates** [comment] 2018-02-05 19:05
@lerudiconsulting , I am having the same issue.  Were you able to increase your timeout inside ConfigureEndpoint as mentioned by @zhenlan ?  If so would you mind sharing full solution?  Thx..

**Comment by mlacouture** [comment] 2018-02-05 19:10
@lerudiconsulting, did you try setting the timeouts exposed by the `System.ServiceModel.Description.ServiceEndpoint.Binding` property inside the `ConfigureEndpoint `method?

**Comment by ttugates** [comment] 2018-02-05 19:16
@mlacouture, assume you were responding to me..  This is what I have:

        ```
private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWorkbooksData))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                // I added below
                result.OpenTimeout = new TimeSpan(0, 1, 0);
                result.CloseTimeout = new TimeSpan(0, 1, 0);
                result.ReceiveTimeout = new TimeSpan(0, 1, 0);
                result.SendTimeout = new TimeSpan(0, 1, 0);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
```

**Comment by mlacouture** [comment] 2018-02-05 20:38
Hi @ttugates.  Yes, I would expect that to work (no need for the WinHttpHandler timeouts. What error do you get?

**Comment by ttugates** [comment] 2018-02-05 20:42
I get: 
exception.Messge = "An error occurred while sending the request."
exception.InnerException.Message = "An error occurred while sending the request."
exception.InnerException.InnerException.Message = "The operation timed out"

Right around the 31 sec mark of starting the request.

**Comment by zhenlan** [comment] 2018-02-05 20:55
@ttugates, the code you have fine. I think you hit the runtime bug #2368. You can try to work around the issue as @mconnew suggested for now. The issue is already fixed in next release.

**Comment by ttugates** [comment] 2018-02-05 21:00
In  #2368, there are 3 solutions.
1) You could pick up a development build from myget which has this issue fixed. 
2) You could build your own WCF assembly from source and use that. 
3) You can use reflection to replace the WinHttpHandler with a modified one.

For 1) What is the simplest way to use the "next release" and or development build?

- It is possible to find in Nuget?

- Or do I build from [here](https://github.com/mconnew/wcf) somehow?
