### ISSUE TITLE
Can't consume brazilian government SOAP

### ISSUE THREAD

**Issue by ctpaula** [dotnet/wcf#3577] opened 2019-04-26 14:59 UTC
Hi people,

In a .NetCore2.1 application I'm trying to consume this service: https://nfe.sefa.pr.gov.br/nfe/NFeAutorizacao4?wsdl
This is a government service, so I have no control of any part of the server.

When I try to Add a WCF using the tool on VS2017 it gives me the following error:

> An error occurred while attempting to find services at 'https://nfe.sefa.pr.gov.br/nfe/NFeAutorizacao4?wsdl'. The request was aborted: Could not create SSL/TLS secure channel.
![image](https://user-images.githubusercontent.com/31453589/56816060-1f4b2400-6819-11e9-849a-868a2d0bebb6.png)

If I copy the wsdl text from the browser, put on a file with "wsdl" extention and import from the file, the tool creates the C# classes, but then when I try to use I got this error:

> The content type application/soap+xml; charset=UTF-8 of the response message does not match the content type of the binding (text/xml; charset=utf-8). If using a custom encoder, be sure that the IsContentTypeSupported method is implemented properly. The first 291 bytes of the response were: '<env:Envelope xmlns:env='http://www.w3.org/2003/05/soap-envelope'><env:Body xmlns:env='http://www.w3.org/2003/05/soap-envelope'><nfeResultMsg xmlns='http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4'><retEnviNFe versao='4.00' xmlns='http://www.portalfiscal.inf.br/nfe'><tpAmb>1</tpAmb>'.

To consume I use the following code:
```
                var binding = new BasicHttpsBinding();
                xml = xml.ToString().Replace("&", "&amp;");
                binding.Security.Mode = BasicHttpsSecurityMode.Transport;
                binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Certificate;

                var endpoint = new EndpointAddress("https://nfe.sefa.pr.gov.br/nfe/NFeAutorizacao4?wsdl");
                var autorizacaoServ = new NFeAutorizacao4Soap12Client(binding, endpoint);
                autorizacaoServ.ClientCredentials.ClientCertificate.Certificate = new X509Certificate2(Path.Combine("Uploads\\Certificados", certificado), senha, X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.PersistKeySet);

                var dadosMsg = XElement.Parse(xml);
                var ret = await autorizacaoServ.nfeAutorizacaoLoteAsync(dadosMsg);
```

Any help of how make this work will be apreciated.

**Comment by nicoclau** [comment] 2019-04-29 15:56
It seems there is a problem of Cert

NET::ERR_CERT_INVALID

**Comment by ctpaula** [comment] 2019-04-29 17:18
> It seems there is a problem of Cert
> 
> NET::ERR_CERT_INVALID

Where? Please explain. 
This wsdl only accept valid employee certificates, guess that maybe accept only brazilian certificates, if you are trying to enter on the "wsdl" link with yout browser, the problem is that you don't have a valid certificate. The problem is not with the certificate of the brazilian government. I can guarantee this.
And also, I have a valid certificate with me that I use to enter.

![BeforeEnter](https://user-images.githubusercontent.com/31453589/56914092-95ee5880-6a89-11e9-9804-aa310d39c346.png)
![The Wsdl](https://user-images.githubusercontent.com/31453589/56914110-a0a8ed80-6a89-11e9-9aa0-058e6daf7ee4.png)

**Comment by dasetser** [comment] 2019-05-08 18:29
@ctpaula Your workaround of downloading the wsdl file and pointing the tool at the local file should give you a valid proxy you can use. We don't have a certificate to pass to the service so we can't reproduce this ourselves or get much information about it. 

The error message you're getting about the content type not matching means something about your client binding isn't matching what the service is expecting (for example, this can be caused by a soap 1.1 vs soap 1.2 mismatch). So I would check your binding setup against their service to see if you can find the mismatch and adjust your binding accordingly.

**Comment by dasetser** [comment] 2019-06-04 20:27
Closing since we don't have an enough information to investigate this.

**Closed by dasetser** 2019-06-04 20:27 UTC
Labels: Backlog, needs more info, tooling
