### ISSUE TITLE
WindowsAuthentication_RoundTrips_Echo test fails cross-windows-machines self-hosted

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#1150] opened 2016-05-12 19:25 UTC
The WindowsAuthentication test fails in cross-machine use.   This is a manual Windows-to-Windows Self-hosted cross machine test involving domain-joined machines.  IIS is not involved.  Non-Windows OSes are not involved. It does not occur yet in CI because the ConditionalFact detectors skip these tests.  By setting environment variables, we force them to run.

Repro steps:

1. Start the self-hosted WCF services on machine A (domain-joined)

2. On machine B running Windows and domain-joined, do these steps
 - Set these environment variables:
```
    set Domain_Joined=true
    set Windows_Authentication_Available=true

```
 - Run the OuterLoops on machine B

```
         Starting:    Security.TransportSecurity.Tests
            Https_ClientCredentialTypeTests.WindowsAuthentication_RoundTrips_Echo [FAIL]
               Test Case: WindowsAuthentication FAILED with the following errors:     Error: Unexpected exception was caught while doing the basic echo test for variation...
         'BasicHttpBinding with Windows authentication'
         Exception: System.ServiceModel.Security.MessageSecurityException: The HTTP request is unauthorized with client authentication scheme 'Negotiate'. The authentication header received from the server was 'Negotiate oXsweaADCgEBonIEcGBuBgkqhkiG9xIBAgIDAH5fMF2gAwIBBaEDAgEepBEYDzIwMTYwNTEyMTg1NTM4WqUFAgMMHmamAwIBKakcGxpSRURNT05ELkNPUlAuTUlDUk9TT0ZULkNPTaoUMBKgAwIBAaELMAkbB3JvbmNhaW4='.
                  at System.ServiceModel.Channels.HttpResponseMessageHelper.ValidateAuthentication() in e:\oss\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpResponseMessageHelper.cs:line 364
                  at System.ServiceModel.Channels.HttpResponseMessageHelper.<ParseIncomingResponse>d__7.MoveNext() in e:\oss\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpResponseMessageHelper.cs:line 39
```

**Comment by iamjasonp** [comment] 2016-06-01 01:35
@roncain - confirmed as an issue even with a .NET Desktop client hitting the same selfhost endpoint

**Comment by iamjasonp** [comment] 2016-06-01 01:50
Found the issue. 

The server side, when selfhosted, is running under the user context. When the WCF client tries to hit the selfhosted service, it does not run under the expected SPN Identity "HOST/machine" - rather it is showing up as the UPN identity "user@domain.com" 

I believe this is a known limitation in WCF - since the selfhosted server has no ability to present itself as the "HOST/machine" SPN. 

The workaround is to replace the factory construction code with: 
```
 factory = new ChannelFactory<IWcfService>(
                binding,
                new EndpointAddress(new Uri("https://selfhostedmachine:44285//HttpsWindows.svc//https-windows"), new UpnEndpointIdentity("user@domain.com")));
```

**Comment by mconnew** [comment] 2016-06-01 03:27
I opened a bug a while ago in corefx that we need support for this on the client side to be able to do mutual authentication dotnet/corefx#4502 with Kerberos. Setting the UpnEndpointIdentity on the client is a no-op in .Net Core as the api's aren't there to do anything about it. Is the workaround actually working for .Net Core?

**Comment by roncain** [comment] 2016-06-01 15:35
@iamjasonp -- is there a way to start the self-host service differently to get around this issue?

**Comment by iamjasonp** [comment] 2016-06-01 16:38
@mconnew - confirmed your hypothesis. 

In .NET Core, specifying the UpnEndpointIdentity does not work around the issue we're seeing with services hosted under a user context - only the system context. 

If we start the selfhosted service using psexec, then authentication happens with no problems. 

(Aside: this is also required and passes on TCP tests)

**Comment by roncain** [comment] 2016-06-01 18:31
PR #1236 allows us to use psexec optionally now.  PR feedback welcome 😁

**Comment by iamjasonp** [comment] 2016-06-08 22:55
Merged, so closing this issue.

**Closed by iamjasonp** 2016-06-08 22:55 UTC
Labels: bug

**Comment by roncain** [comment] 2016-06-09 13:43
For the record, #1271 has been opened to make the self-hosted service use PsExec to allow these tests to pass.  We probably also need a ConditionalFact to run when we detect this has been done.

**Comment by iamjasonp** [comment] 2016-06-09 16:15
The whole UPN Identity support story is a bit convoluted and nuanced - I'm using #10 to keep track of the issue(s) around this.
