### ISSUE TITLE
WCF chanelfactory does not expose Lingerstate property or underline socketconnection.This leads to GC blocked till the underlineSocketConenction dispose is completed

### ISSUE THREAD

**Issue by PDesai1979** [dotnet/wcf#5291] opened 2023-09-15 15:44 UTC
**Describe the bug**
Garbage collection waits for the cooperative thread to finish but that coprative thread is hang in socket connection CloseAsIs regardless of the closetimeout value on the binding.

**To Reproduce**
We are seeing sometimes the GC hang becase of other coprative thread was trying to dispose a socketconnection enters into spin wait beyond its close timeout value
![image](https://github.com/dotnet/wcf/assets/62571228/c9b20469-c777-4ca7-9965-3da780562aae)

![image](https://github.com/dotnet/wcf/assets/62571228/990077db-64f8-4cca-9ff9-bd9c5e17407d)
Gabrge collection is in suspended state because of the above thread
![image](https://github.com/dotnet/wcf/assets/62571228/0d8a1386-d904-45ba-ae19-bd74243678e5)

We noticed the Socketconnection has lingerstate property that can be set to close this socket faster. But it seems this underline socketconnection is not exposed in WCF channelfactory.

**Expected behavior**
SocketCnnecctionCloseAsIs should either take into consideration the binding closetineout value or wcf can expose setting this socketconnection property 

**Screenshots**

**Additional context**

**Comment by mconnew** [comment] 2023-09-20 00:46
You're having issues on .NET Framework, this isn't the right place to open issues for .NET Framework. From the About description for this repo:

> This repo contains the client-oriented WCF libraries that enable applications built on .NET Core to communicate with WCF services.

The correct place for .NET Framework issues is https://developercommunity.visualstudio.com/VisualStudio

There are a couple of things at play here when using NetTcp. WCF pools idle connections between the client and service. When you create a channel and open it, WCF checks an idle connection pool and only creates a new connection if there isn't one available. When you are finished with a channel and close it, there's a close handshake to tell the service no more requests are going to be sent and handles waiting for any remaining responses to complete before placing the socket in an idle connection pool. This means the binding close timeout is irrelevant as that timeout is used for this close handshake. It's only if the idle connection pool is full or the socket has existed for longer than the configured lease timeout when the socket will actually be closed that the close timeout comes into play. If a connection has sat idle in the connection pool for too long, we close the socket and use a timeout no more than half the idle timeout value. It's impossible to know what conditions your socket is being closed as you are using ngen'd binaries and the WCF frames aren't visible. You can turn off using ngen'd binaries as well as disable JIT optimizations which both obscure the call stack by setting these two environment variables before launching the process:
```cmd
set COMPlus_ZapDisable=1
set COMPLUS_JitMinOpts=1
``` 
There are two things you can do to address this problem, both involved configuring your connection pool. You either configure your connection pool so that there is very little closing of connections needed, or you configure it so idle connections are never pooled so that your Close timeout is applied to the socket as well. To do that, you will need to use a custom binding and configure the [Tcp transport connection pool](https://learn.microsoft.com/en-us/dotnet/api/system.servicemodel.channels.tcptransportbindingelement.connectionpoolsettings?view=dotnet-plat-ext-7.0). You can configure it like this:
```c#
var netTcpBinding = new NetTcpBinding(); // Configure as normal, or you could pass binding config name to constructor
var customBinding = new CustomBinding(netTcpBinding);
var tcpTBE = customBinding.Elements.Find<TcpTransportBindingElement>();
tcpTBE.ConnectionPoolSettings.IdleTimeout = TimeSpan.MaxValue;
tcpTBE.ConnectionPoolSettings.LeaseTimeout = TimeSpan.MaxValue;
// Set to a bit more than your maximum number of concurrent channels
tcpTBE.ConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint = 100;
var factory = new ChannelFactory<IService>(customBinding, "net.tcp://myserver/service.svc");
```
This will mean you won't ever close a connection. Well, that's not 100% true, it does reference counting on the ChannelFactory instances using a pool (a pool is shared between all channel factories in the process on a per remote host basis that have the same connection setting group name). When you close the ChannelFactory, if it's the last instance using a pool, it closes all the connections then. If you have a single ChannelFactory, it effectively means the connection lifetime is tied to the ChannelFactory.  

The other option is to make WCF always close the socket when you close the channel. For that, you just need to set `MaxOutboundConnectionsPerEndpoint` to 0. Either option should fix your problem. If you are still having problems, you can do an unclean close by calling `Abort` on the channel.  

The linger shouldn't be causing any real delay at that point. The purpose of a linger is to allow any outstanding bytes that need to be written to be written. The point where we call `Close` on the socket, we have at most a single byte which was encrypted (so maybe blown up to a couple of hundred bytes, but still a single TCP packet) to signal closing the connection that might not have been sent on the socket yet. If it's being closed via the idle connection pool cleaning up idle connections, there will be no outstanding data. This means the delay is caused by the two way FIN handshake taking time, which most likely means you have a network problem somewhere and this is a symptom. NetTcp isn't intended for use on high latency connections, it has several characteristics which mean you can have some performance issues with high latency (eg streamed transfer mode throttles a lot with latency).

Hopefully this helps solve your issue. If not, post to the developer community and include call stacks with more information by suppressing ngen and JIT optimizations if possible.

**Closed by mconnew** 2023-09-20 00:46 UTC
Labels: triaged
