### ISSUE TITLE
Error "An HTTP Content-Type header is required for SOAP messaging and none was found."

### ISSUE THREAD

**Issue by waldimen** [dotnet/wcf#2188] opened 2017-08-11 12:32 UTC
I created connected service to PHP powered SOAP Web Service.
When I try to connect ot the service using generated code I got error:

"An HTTP Content-Type header is required for SOAP messaging and none was found."

I can invoke the service from SoapUI without any problems.

Any ideas  what else to check ?

**Comment by hongdai** [comment] 2017-08-11 17:34
@waldimen Sorry to hear you are running into the issue!

Is the service public accessible? It will speed up the investigation if you can provide a repro.

Thanks,
Hong Dai

**Comment by waldimen** [comment] 2017-08-14 09:16
No, it is not a public repo. What is strange in Fiddler I can see that the
response was sent by server, but it seems that it is not properly decoded.

Regards,

Waldimen

2017-08-11 19:34 GMT+02:00 Hong Dai <notifications@github.com>:

**Comment by mconnew** [comment] 2017-08-16 00:31
@waldimen, the problem is the server is doing the wrong thing.  

The Content-Type header is required according to the [SOAP 1.2 spec](http://www.w3.org/TR/soap12-part2/#http-respbindprocess).
> If Status line is 200, then the media type of the response body, see [7.1 Introduction](http://www.w3.org/TR/soap12-part2/#http-intro) for a description of permissible media types.  If status line is other than 200, then the Content-Type header is not sent.

The Content-Type header is also required according to the [SOAP 1.1 spec](http://www.w3.org/TR/2000/NOTE-SOAP-20000508/#_Toc478383526).
> HTTP applications MUST use the media type "text/xml" according to RFC 2376 [[3]](http://www.w3.org/TR/2000/NOTE-SOAP-20000508/#RFC2376) when including SOAP entity bodies in HTTP messages.

So basically the endpoint you are communicating with doesn't correctly implement the SOAP spec which is why WCF is throwing an exception when getting an invalid response. It seems like the SoapUI tool supports communicating with endpoints which aren't SOAP compliant whereas WCF is more strict. Can you modify the server side to conform to the SOAP spec?

**Comment by zhenlan** [comment] 2017-09-08 18:46
Closing for now. @waldimen please let us know if you have any other questions.

**Closed by zhenlan** 2017-09-08 18:46 UTC
Labels: Community

**Comment by srjohn** [comment] 2018-03-13 14:26
Hi @zhenlan, you are right that header is required according to the SOAP rule-book. I have a different scenario for this situation. 

As you know Magento is a open-source e-trade application written in php. I'm trying to connect Magento SOAP services and service is wrongly configured response content is text/xml. I can't change magento source codes and dotnetcore doesn't easliy allow me to accept that header. 

I've tested .net framework, it allows me to connect without content-type=application/soap+xml header and this situitation forces me to use .net framework library in .net core.

I know rules are important but it must be a simple solution for this situtation.

**Comment by ntark** [comment] 2025-02-27 08:51
Hi @mconnew , sorry for commenting on an old issue but 
> If Status line is 200, then the media type of the response body, see [7.1 Introduction](http://www.w3.org/TR/soap12-part2/#http-intro) for a description of permissible media types. If status line is other than 200, then the Content-Type header is not sent.
That means if status line is not 200, WCF fails with message "An HTTP Content-Type header is required for SOAP messaging and none was found.", instead of forwarding the response (likely containing exception), which I might need for logging.

Is there any way I can suppress wcf exception and read the response body?
