### ISSUE TITLE
Error: The method or operation is not implemented

### ISSUE THREAD

**Issue by diegonc** [dotnet/wcf#4412] opened 2020-10-22 18:05 UTC
I'm getting the error in the subject when importing a wsdl file. No code is generated and the wizard ends with "no .net core compatible endpoint found" (sorry, the error is in Spanish and I don't know the exact message)

I have no idea what in the wsdl file might be wrong. May I have someone give a look at it?

[Autenticacion.zip](https://github.com/dotnet/wcf/files/5424761/Autenticacion.zip)

**Comment by HongGit** [comment] 2021-03-02 06:09
@imcarolwang can you please see if you could repro this?

**Comment by imcarolwang** [comment] 2021-03-03 02:56
Hi @diegonc , I tried running dotnet-svcutil against the attached wsdl file and I cannot reproduce the Error as you posted in the issue title "The method or operation is not implemented", I got following error instead:

```
Warning: Cannot import wsdl:portType
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Description.DataContractSerializerMessageContractImporter
Error: Schema with target namespace 'http://tempuri.org/' could not be found.
```

It's due to the referenced xsd files (`Autenticacion.xsd` and `Autenticacion1.xsd`) in the wsdl file are relative local paths which is unavailable on my repro environment, could you provide the dependency xsd files as well?

**Comment by diegonc** [comment] 2021-03-04 21:58
Sorry for the late response, work drifted away of this project. Here are the XSDs files imported by the WSDL. Thanks

[xsds.zip](https://github.com/dotnet/wcf/files/6086833/xsds.zip)

**Comment by HongGit** [comment] 2023-07-27 03:58
Close this issue as this is resolved.  Please open a new issue if there are more problems.

**Closed** 2023-09-05 09:06 UTC
Labels: tooling
