### ISSUE TITLE
Support MessageHeaderAttribute & MessageBodyMemberAttribute

### ISSUE THREAD

**Issue by YZahringer** [dotnet/wcf#35] opened 2015-05-25 19:42 UTC
svcutil generates proxy with MessageHeader & MessageBodyMember attributes and does not compile with the DNX Core 5 because there attributes does not exist in System.ServiceModel

Here is a workaround to compile a generated proxy from svcutil in a vNext assembly:
```cs
#if DNXCORE50

namespace System.ServiceModel
{
    internal class MessageHeaderAttribute : Attribute
    {
        public string Namespace { get; set; }
    }
}

namespace System.CodeDom.Compiler
{
    internal class GeneratedCodeAttribute : Attribute
    {
        public GeneratedCodeAttribute(string name, string version)
        {
            
        }
    }

}

namespace System
{
    internal class SerializableAttribute : Attribute
    {

    }

    internal class NonSerializedAttribute : Attribute
    {

    }
}

namespace System.Diagnostics
{
    internal class DebuggerStepThroughAttribute : Attribute
    {
        
    }
}

namespace System.ComponentModel
{
    internal class DesignerCategoryAttribute : Attribute
    {
        public DesignerCategoryAttribute(string name)
        {
            
        }
    }

    internal class BrowsableAttribute : Attribute
    {
        public BrowsableAttribute(bool browsable)
        {
        
        }
    }
}

namespace System.Runtime.Serialization
{
    internal interface IExtensibleDataObject
    {
    
    }

    internal class ExtensionDataObject : IExtensibleDataObject
    {

    }

    internal class OptionalFieldAttribute : Attribute
    {

    }
}

#endif
```

**Comment by roncain** [comment] 2015-05-26 15:21
Thanks for reporting this and offering the work-around @YZahringer .  This issue is a great place to start a conversation about svcutil itself.   This tool has not been updated to generate code appropriate for Windows Store, UWP or DNX Core 5 apps.  Instead, "Add Service Reference" (aka ASR) in Visual Studio has taken over this role entirely and left svcutil behind (one exception: VS 2015 RC still has not added ASR support for ASP.NET 5 apps, but we're working with them to correct this). So the larger questions are:
* **How important is svcutil (and/or ASR) to you for app development?**
* **Should svcutil be made OSS and upgraded for UWP and DNX Core 5 apps?**

We have some initial usage data that suggest about 50% of all WCF app developers use ASR, and we'd like to better understand the usage of svcutil. We'd appreciate hearing your thoughts and how you'd prioritize it against other work.

**Comment by YZahringer** [comment] 2015-05-26 15:46
I use svcutil because ASR is not available for ASP.NET 5 applications.

If I retrieves the References.cs generated with ASR on .NET 4.6 application, it did the same problems of missing attributes with svcutil on an ASP.NET 5 application.

The support of ASR on an ASP.NET 5 application would solve my problem. This is planned?

**Comment by roncain** [comment] 2015-05-26 16:03
We are actively working with the VS folks doing the new tooling for "Add Connected Services" to add support for ASR for ASP.NET 5 apps.  I don't have an ETA yet.  In the meantime, there is another temporary work-around I recommend you try. Create a new Windows Universal app (now called UWP) and use ASR there. This generates client code compatible with both UWP and ASP.NET 5 apps.  Then copy the References.cs like you did. One big difference between this code-gen vs. the .NET 4.6 is that no app.config is generated -- configuration is done in the generated code itself.

**Comment by YZahringer** [comment] 2015-05-26 18:22
Thank you for work-around, this is more clean. Only these attributes are missing:
```cs
#if DNXCORE50

namespace System.CodeDom.Compiler
{
    internal class GeneratedCodeAttribute : Attribute
    {
        public GeneratedCodeAttribute(string name, string version)
        {
            
        }
    }

}

namespace System.Diagnostics
{
    internal class DebuggerStepThroughAttribute : Attribute
    {
        
    }
}

#endif
```

and add "Linked" Reference.cs on project.json:
```json
{
"compile": [
    "../UWP.Project/Service References/NameOfService/Reference.cs"
  ]
}
```

**Comment by roncain** [comment] 2015-05-27 16:59
These types did not exist in the Windows Store profiles but arguably should have.  Resolving this issue means they will be duplicated from the full .NET Framework, and added to a new higher level version of System.ServiceModel.Primitives. It is an API-addition to the WCF client libraries but does not affect the API surface of the .NET Framework.

**Comment by YZahringer** [comment] 2015-07-05 09:20
hello,

The beta5 no longer allows code compilation of ASR generated from UWP application.

This worked well in beta4, in beta5 it does not find the ServiceKnownTypeAttribute, FaultContractAttribute, OperationContractAttribute, ...........

I tried to add the NuGet "System.Private.ServiceModel" but it does not fix.

There is a solution?

**Comment by roncain** [comment] 2015-07-06 12:48
Thanks for reporting this @YZahringer .  Could I ask you to provide more details of the steps you took?  For example, what version of VS are you using?  How did you get beta5 (upgrade an existing app, build a new one)? Were you creating a UWP app so that you could use the generated code in an ASP.NET 5 app, as we discussed before?  And was the compile failure with the UWP app or the ASP.NET 5 app?

**Comment by YZahringer** [comment] 2015-07-06 14:39
Hi @roncain,

I use Visual Studio 2015 RC with Windows 8.1.

I tried the upgrade of an existing project in beta4 to beta5 and a new project in beta5. Same error...

Yes, I use Reference.cs generated code from UWP app in ASP.NET 5 app. ASP.NET 5 app in beta4 compile, same file in ASP.NET 5 app in beta5 give some errors of missing Attributes...

**Comment by roncain** [comment] 2015-07-06 17:00
Hi @YZahringer .  We are investigating.  In the meantime, could you describe the steps you took to upgrade to beta5?  Did you manually edit the .json files in the existing project?  Use 'dnvm upgrade'?

**Comment by YZahringer** [comment] 2015-07-06 17:06
Yes, I use 'dnvm upgrade', then edit global.json in solution and fix to beta5 version, finally upgrade all nuget packages to latest version.

Solution works and compile in beta5 without generated code from UWP.

I think that attributes are missing or have been moved to another package in beta5.

**Comment by YZahringer** [comment] 2015-07-07 18:41
Hi @roncain,

I found how to compile in beta5, there are many changes in the nuget packages.

in project.json
```json
{
    "frameworks": {
        "dnx451": {
            "frameworkAssemblies": {
                "System.ServiceModel": "4.0.0.0"
            }
        },
        "dnxcore50": {
            "dependencies": {
                "System.ServiceModel.Http": "4.0.10-beta-23019",
                "System.Private.ServiceModel": "4.0.0-beta-23019",
                "System.ServiceModel.Primitives": "4.0.0-beta-23019"
            }
        }
    }
}
```

This works, but I do not understand why the dependencies in dnxcore50 no longer works with dnx451 in beta5? Is it correct to put "System.ServiceModel" in dnx451?

**Comment by roncain** [comment] 2015-07-08 11:54
Thank you @YZahringer for your investigation. Good information.  I am also coming up to speed on the changes in beta5 packages, and the developer most familiar with beta5 testing is OOF this week. We'll try to get you an answer early next week. We definitely appreciate your taking the time to explore the new packages and provide this feedback.

**Comment by hongdai** [comment] 2015-07-13 18:56
@YZahringer, to answer your question,   "dnx451" and  "dnxcore50" are two different frameworks, you need to define assembly dependencies separately. It's by design the dependencies in dnxcore50 do not work with dnx451 framework.

By default, dnx451(Full .Net Framework) is used. You are correct that you need to add the "System.ServiceModel" reference in dnx451 in your case.

**Comment by atanasa** [comment] 2015-09-14 15:16
On the topic of svcutil:
I think manually creating the contracts is the best option - both svcutil and ASR have their shortcomings.
Unfortunately I have to connect to a Java web service that has hunderds of methods and I can't manually create those contracts, so svcutil is in general the better option for these reasons:
- Svcutil allows you to automate the process of building a WCF client proxy.
- Svcutil supports the generation of serializers assembly (the /t:xmlSerializer option), while the VS ASR does not. For the web services that I target, serializer assemblies speeds up things significantly. From my observations so far, .Net Core uses the same dynamically generated in-memory XML serializers, so generating a serializer assembly is still relevant.
- ASR would always nest the namespace of the generated code - I prefer to have my proxy client code be in its own assembly and reusable by multiple projects rather than mixed with other code and ASR doesn't seem to be designed with that option in mind (e.g. no option to generate only a service contract).

**Comment by ShaneK2** [comment] 2015-11-26 23:11
+10 to this bug please :).  Lacking [MessageHeader] for [MessageContract] in Streaming mode fairly complicates things since, of course;
```
Unhandled Exception: System.InvalidOperationException: In order to use Streams with the MessageContract programming model, the type foo must have a single member with MessageBodyMember attribute and the member type must be Stream.
```
I tried to use the above workaround's but am still pretty new to coreclr and porting my WCF project needed to stick to Buffered.

I don't want to cross threads too much but setting up MessageEncoding MTOM eludes me also, defaulted down to TEXT.

Thanks for the work, posting some `commands ` soon :+1:

**Comment by shmao** [comment] 2015-12-14 20:02
Opened #631 for tracking the API change.
Opened #632 for adding scenario tests for the new API.

**Closed** 2016-01-07 00:17 UTC
Labels: api addition, feature request

**Comment by spboyer** [comment] 2016-05-25 00:12
Is there a working example of aspnet core consuming a wcf service using these libraries? I am not seeing a path to success.  Getting unresolved `System.Private.ServiceModel` unless I add it to the project.json specifically.  Please advise or show a simple console app.

Thanks.

**Comment by zhenlan** [comment] 2016-05-25 01:11
@spboyer, yes, due to some packaging issues, you will have to add `System.Private.ServiceModel` package explicitly to the project json if you are using our RC2 release (see known issues in [RC2 release notes](https://github.com/dotnet/wcf/releases/tag/v1.0.0-rc2)). Sorry for this inconvenience. Did you get further or run into other issues after you included `System.Private.ServiceModel`?

**Comment by spboyer** [comment] 2016-05-25 02:34
@zhenlan - creating the proxy via svcutil, creating the Client and then calling a method on the proxy just fails with

```
Unhandled Exception: System.PlatformNotSupportedException: Configuration files are not supported.
   at System.ServiceModel.ClientBase`1..ctor()
   at GetPeopleServiceClient..ctor()
   at ConsoleApp2.Program.Main(String[] args)
```

**Comment by zhenlan** [comment] 2016-05-25 03:16
The proxy code generated by desktop svcutil tool will not be compatible with .NET Core. For example, the configuration is not supported on .NET Core.

@spboyer - are you using [.NET Core RC2](https://blogs.msdn.microsoft.com/dotnet/2016/05/16/announcing-net-core-rc2/) or on RC1 bits?

**Comment by spboyer** [comment] 2016-05-25 03:19
this is RC2 bits.  Which svcutil version should be used, or what method should be used to generate the proxy.

**Comment by spboyer** [comment] 2016-05-25 03:22
@zhenlan trying to document this process/approach for other teams. so any guidance would be helpfuld for both of us.

**Comment by spboyer** [comment] 2016-05-25 12:24
Here are all of the current svcutil.exe versions that are on my machine...curious which one if any we are suppose to be using for creating the client proxy for dotnet core.

![svcutil](https://cloud.githubusercontent.com/assets/7681382/15539723/19415a26-2252-11e6-8849-05188f865273.png)

**Comment by zhenlan** [comment] 2016-05-25 23:17
@spboyer - we just published an updated [WCF Connected Service VS extension for VS 2015](https://blogs.msdn.microsoft.com/webdev/2016/05/25/announcing-wcf-connected-service-for-net-core-rc2-and-asp-net-core-rc2/) moments ago. Please use it to generate .NET Core RC2 compatible WCF client proxy.

cc: @mlacouture

**Comment by spboyer** [comment] 2016-05-26 00:38
@zhenlan of course.  I did find the way via reading the code in the tests. see - http://tattoocoder.com/asp-net-core-getting-clean-with-soap/

**Comment by zhenlan** [comment] 2016-05-26 01:36
Nice blog post @spboyer. Thanks for including the link of WCF Connected Service 😄. We would love to hear your feedback too.

**Comment by spboyer** [comment] 2016-06-09 15:25
@zhenlan the Connected service is great! I noticed that the `GeneratedCodeAttribute` is `dotnet-svcutil` does that mean that there is a xplat dotnet command `svcutil`? I dont see it on any of the nuget feeds.  Would love to be able to use/demo this on *nix 

So on OSX using it from bash `$ dotnet svcutil <url>`

`[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.2.0.0"`

**Comment by zhenlan** [comment] 2016-06-09 16:50
Thanks @spboyer. Yes, a xplat svcutil is on our radar, but it is not yet ready for a standalone release. It is currently only available as part of WCF Connected Service VS extension.

Thank you for the feedback!
