### ISSUE TITLE
soap rpc style bug

### ISSUE THREAD

**Issue by timebubble** [dotnet/wcf#2359] opened 2017-10-25 10:52 UTC
发生了 System.InvalidOperationException
  HResult=0x80131509
  Message=The operation 'xxxx' could not be loaded because it specifies \"rpc-style\" in \"literal\" mode, but uses message contract types or the System.ServiceModel.Channels.Message. This combination is disallowed -- specify a different value for style or use parameters other than message contract types or System.ServiceModel.Channels.Message.
  Source=<无法计算异常源>
  StackTrace:
   at System.ServiceModel.Dispatcher.OperationFormatter.Validate(OperationDescription operation, Boolean isRpc, Boolean isEncoded)
   at System.ServiceModel.Dispatcher.OperationFormatter..ctor(OperationDescription description, Boolean isRpc, Boolean isEncoded)
   at System.ServiceModel.Description.XmlSerializerOperationBehavior.CreateFormatter()
   at System.ServiceModel.Description.XmlSerializerOperationBehavior.System.ServiceModel.Description.IOperationBehavior.ApplyClientBehavior(OperationDescription description, ClientOperation proxy)
   at System.ServiceModel.Description.DispatcherBuilder.BindOperations(ContractDescription contract, ClientRuntime proxy, DispatchRuntime dispatch)
   at System.ServiceModel.Description.DispatcherBuilder.BuildProxyBehavior(ServiceEndpoint serviceEndpoint, BindingParameterCollection& parameters)
   at System.ServiceModel.Channels.ServiceChannelFactory.BuildChannelFactory(ServiceEndpoint serviceEndpoint, Boolean useActiveAutoClose)
   at System.ServiceModel.ChannelFactory.OnOpening()
   at System.ServiceModel.Channels.CommunicationObject.<System-ServiceModel-IAsyncCommunicationObject-OpenAsync>d__79.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.CommunicationObject.<OpenAsyncInternal>d__78.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.ChannelFactory.EnsureOpened()
   at System.ServiceModel.ChannelFactory`1.CreateChannel(EndpointAddress address, Uri via)
   at System.ServiceModel.ClientBase`1.get_Channel()
   at

**Comment by nmocruz** [comment] 2017-10-25 18:23
Same problem here :(

**Comment by shmao** [comment] 2017-10-25 21:28
Thanks for submitting the issue. Can you please share some repro code with me? I can give it a try.

**Comment by nmocruz** [comment] 2017-10-25 22:24
I can share the message and classes used.

`<?xml version="1.0"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/">
    <SOAP-ENV:Body SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:NS1="urn:M_SessionManagerIntf-ISessionManagerSvc" xmlns:NS2="urn:M_SessionManagerIntf">
        <NS1:AuthenticateWithSessionResponse>
            <return href="#1"/>
        </NS1:AuthenticateWithSessionResponse>
        <NS2:TSwCredentials id="1" xsi:type="NS2:TSwCredentials">
            <SessionToken xsi:type="xsd:string">3C63A95AD368410122295C1C</SessionToken>
            <Username xsi:type="xsd:string">SYSTEM</Username>
            <IsAuthenticated xsi:type="xsd:boolean">true</IsAuthenticated>
            <ErrorCode xsi:type="xsd:int">1</ErrorCode>
            <ErrorMessage xsi:type="xsd:string"></ErrorMessage>
            <ForcePasswordChange xsi:type="xsd:boolean">false</ForcePasswordChange>
            <PasswordExpiryDate xsi:type="xsd:dateTime">1899-12-30T00:00:00.000Z</PasswordExpiryDate>
            <ShowBanner xsi:type="xsd:boolean">false</ShowBanner>
            <UserId xsi:type="xsd:int">1</UserId>
            <DefaultUrl xsi:type="xsd:string">Main.htm</DefaultUrl>
            <DefaultEmpId xsi:type="xsd:int">0</DefaultEmpId>
        </NS2:TSwCredentials>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

`using IdentityCore.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Threading.Tasks;
using System.Xml.Serialization;
using System.Security.Claims;
using IdentityCore.Data;

namespace IdentityCore.Services
{


    [SoapTypeAttribute(Namespace="urn:M_SessionManagerIntf")]
    [Serializable]
    public partial class TSwCredentials
    {
    
        public string SessionToken { get; set; }

        public string Username { get; set; }
        
        public bool IsAuthenticated { get; set; }

        public int ErrorCode { get; set; }

        public string ErrorMessage { get; set; }

        public bool ForcePasswordChange { get; set; }

        public System.DateTime PasswordExpiryDate { get; set; }

        public bool ShowBanner { get; set; }

        public int UserId { get; set; }

        public string DefaultUrl { get; set; }

        public int DefaultEmpId { get; set; }

      
        
    }

   
    [MessageContract(WrapperName="ImpersonateResponse", WrapperNamespace="urn:M_SessionManagerIntf-ISessionManagerSvc")]
 
    public class ImpersonateResponse  {

        public TSwCredentials @return { get; set; }

        public ImpersonateResponse()
        {
        }
        
        public ImpersonateResponse(TSwCredentials @return)
        {
            this.@return = @return;
        }
     }

    [MessageContract(WrapperName="AuthenticateResponse", WrapperNamespace="urn:M_SessionManagerIntf-ISessionManagerSvc", IsWrapped=true)]
    public class AuthenticateResponse {

        [MessageBodyMember(Namespace = "", Order = 0)]
        public TSwCredentials @return { get; set; }

        
        public AuthenticateResponse(TSwCredentials @return){

            this.@return = @return;
        }
     }
     

   
    
    [MessageContract(WrapperName="Authenticate", WrapperNamespace="urn:M_SessionManagerIntf-ISessionManagerSvc", IsWrapped=true)]
    
    public partial class AuthenticateRequest
    {
        
        [MessageBodyMember(Namespace="", Order=0)]
        public string Username { get; set; }
        
        [MessageBodyMember(Namespace="", Order=1)]
        public string Password { get; set; }

        public AuthenticateRequest(string Username, string Password)
        {
            this.Username = Username;
            this.Password = Password;
        }

    }

    [MessageContractAttribute(WrapperName="Impersonate", WrapperNamespace="urn:M_SessionManagerIntf-ISessionManagerSvc", IsWrapped=true)]
    public class  ImpersonateRequest{


        public string Username { get; set; }
        public string Password { get; set; }
        public string cUsernameToImpersonate { get; set; }

        public ImpersonateRequest(){}

        public ImpersonateRequest(string Username, string Password, string cUsernameToImpersonate) {

            this.Username = Username;
            this.Password = Password;
            this.cUsernameToImpersonate = cUsernameToImpersonate;
        }
    }

    [ServiceContract(Namespace="urn:M_SessionManagerIntf-ISessionManagerSvc")]
    public interface IRemoteUserService
    {
        [OperationContract(Action="urn:M_SessionManagerIntf-ISessionManagerSvc#Authenticate", ReplyAction="*")]
        [XmlSerializerFormat(Style=OperationFormatStyle.Rpc, Use=OperationFormatUse.Encoded)]
        TSwCredentials Authenticate(string username, string password);

        [OperationContract]
        [XmlSerializerFormat(Style = OperationFormatStyle.Rpc, Use=OperationFormatUse.Encoded)]

        ImpersonateResponse Impersonate(ImpersonateRequest request);
    }


    public interface IUserService
    {
        TSwCredentials Authenticate(string username, string password);

        TSwCredentials Impersonate(string username);

    }

    public class UserService : ClientBase<IRemoteUserService>, IUserService
    {

        protected UsersDbContext _dbContext;
        public UserService(string endpoint, UsersDbContext dbContext):
            base(new BasicHttpBinding(), new EndpointAddress(endpoint))
        {
            this._dbContext = dbContext;
        }

        public TSwCredentials Authenticate(string username, string password)
        {
            var r = base.Channel.Authenticate(username, password);
            return r;
        }

        public TSwCredentials Impersonate(string cusername){

            var username = "";
            var password = "";
            var r = base.Channel.Impersonate(new ImpersonateRequest(username, password, cusername));
            return r.@return;
        }

    }
}
`

**Comment by nmocruz** [comment] 2017-10-25 22:49
If you know a workaround to deserialize this message I will appreciate. Is a legacy system we don't want to change the message format, and not a wcf expert to get this working.

**Comment by nmocruz** [comment] 2017-10-26 07:56
Forgot to mention I am using dotnet core 2.0 and wcf 4.4.0 . I tried to use a dev version on myget but was complaining about a dependency on a preview of ... platforms

**Comment by nmocruz** [comment] 2017-10-26 10:02
seem to be the same as https://github.com/dotnet/wcf/issues/2264 but this fix not released to dotnet core 2.0

**Comment by shmao** [comment] 2017-10-26 17:38
@nmocruz you're right. This shares the same root cause with #2264. The fix was made post .Net Core 2.0. It would be included in the next release. It would help a lot if you can try the packages from myget for verification purpose (not sure if it's possible for your project to suppress the warning/error on using preview packages).

**Comment by nmocruz** [comment] 2017-10-26 20:35
@shmao I tried and and now I stuck on issue [2349](https://github.com/dotnet/wcf/issues/2349)

**Comment by zhenlan** [comment] 2017-10-27 18:35
> @shmao I tried and now I'm stuck on issue #2349

@nmocruz, can you please elaborate why you are "stuck". Would it possible for you to change the `--runtime` to use RIDs like win7-*, win81-* or win10-*?

**Comment by zhenlan** [comment] 2017-11-10 20:47
Closing this as the original issue is a Duplicate of #2264.

Please use #2349 for any further discussion about the WCF RID support.

**Closed by zhenlan** 2017-11-10 20:47 UTC
Labels: bug

**Comment by nmocruz** [comment] 2017-11-10 21:49
I changed the target to net471 for now and maybe later I try again with
core 2.0.  But the problem was attempt to load an assembly not sure exact
name and version but was something like Microsoft.serviceModel 4.x.x.x

Em 27/10/2017 19:35, "Zhenlan Wang" <notifications@github.com> escreveu:

@shmao <https://github.com/shmao> I tried and now I'm stuck on issue #2349
<https://github.com/dotnet/wcf/issues/2349>

@nmocruz <https://github.com/nmocruz>, can you please elaborate why you are
"stuck". Would it possible for you to change the --runtime to use RIDs like
win7-*, win81-* or win10-*?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dotnet/wcf/issues/2359#issuecomment-340051226>, or mute
the thread

**Comment by nmocruz** [comment] 2017-11-10 21:53
It looks like this one #2337

Em 10/11/2017 21:49, "nuno cruz" <nmocruz@gmail.com> escreveu:
