### ISSUE TITLE
Crashes Visual Studio 

### ISSUE THREAD

**Issue by rdvanbuuren** [dotnet/wcf#2262] opened 2017-09-01 12:45 UTC
Some days ago I installed .NET Core 2.0 and latest VS update (15.3.3). 

Now, the tool crashes my Visual Studio when I try to add a new reference.
It stops at "Scaffolding service reference code ..." and after a while Visual Studio is restarted automatically.

Versions I'm using:
Visual Studio 15.3.3
Microsoft WCF Web Service Reference Provider 0.5.10808.800
.NET Core 2.0

I've included the .wsdl [SalesShipment.zip](https://github.com/dotnet/wcf/files/1270215/SalesShipment.zip) I'm using to generate the service reference.

Best regards,
Rick

**Comment by hongdai** [comment] 2017-09-01 17:45
@rdvanbuuren Sorry to hear that you are running into the issue. We will try to repro it locally and investigate the root cause.

Thanks,
Hong Dai

**Comment by hongdai** [comment] 2017-09-01 18:11
@rdvanbuuren I couldn't repro locally using the provided configuration.

To further investigate, could you provide below information?
1) log under %temp%\WCFConnectedService
2) Your project definition.

Thanks,
Hong Dai

**Comment by rdvanbuuren** [comment] 2017-09-01 19:02
@hongdai Here is the log file you requested:
[WCFConnectedServiceLog.txt](https://github.com/dotnet/wcf/files/1271238/WCFConnectedServiceLog.txt)
and the project definition:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
 <DocumentationFile>bin\Debug\netcoreapp2.0\ITDepartment.Core.Transaction.Ordering.Api.xml</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="6.1.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="3.0.1" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Proxy" Version="0.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.WebSockets" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="2.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="1.0.0" />
    <PackageReference Include="System.ServiceModel.Duplex" Version="4.4.0" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.4.0" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.4.0" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.4.0" />
    <PackageReference Include="System.Xml.XmlSerializer" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ITDepartment.Core.Transaction.Ordering.Api.Contracts\ITDepartment.Core.Transaction.Ordering.Api.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Connected Services" />
  </ItemGroup>
</Project>
```
If you need more information, please let me know!

Best regards,
Rick

**Comment by hongdai** [comment] 2017-09-01 19:11
@rdvanbuuren Please also attach the below file:
"C:\Users\rickv\AppData\Local\Temp\WCFConnectedService\2017_Sep_01_20_53_10\SvcUtilParams.txt""

**Comment by rdvanbuuren** [comment] 2017-09-01 19:15
@hongdai Here you go:
[SvcUtilParams.txt](https://github.com/dotnet/wcf/files/1271288/SvcUtilParams.txt)

**Comment by hongdai** [comment] 2017-09-01 20:06
@rdvanbuuren It might be related to one of the references. Could you try **Disable reuse type**?

I will also need to take a look at the svcutil bootstrapper project generated. Could you zip the whole log directory and attach it?

Thanks,
Hong Dai

**Comment by rdvanbuuren** [comment] 2017-09-01 20:26
@hongdai I disabled "Reuse types in referenced assemblies" and that fixed the problem. No more crashes. So thank you for the analisys and your quick replies! 👍  

Still, here's the zip file of the project causing the crash:
[2017_Sep_01_20_53_10.zip](https://github.com/dotnet/wcf/files/1271413/2017_Sep_01_20_53_10.zip)
I hope you can benefit from it and create a more solid tool!

Thanks,
Rick

**Comment by hongdai** [comment] 2017-09-01 20:30
@rdvanbuuren Thanks for helping us improve the tool, Rick!

I notice that the 2.0 Asp.net Core template has the below line that is missing from your project. It has caused problem for other customers migrated from previous VS versions before. 
   `<PackageTargetFallback>$(PackageTargetFallback);portablenet45+win8+wp8+wpa81;</PackageTargetFallback>`

I'd suggest you add this line to your project.

-Hong Dai

**Comment by zhenlan** [comment] 2017-09-07 19:57
@hongdai are you able to repo the issue? We should not crash regardless.

**Comment by hongdai** [comment] 2017-09-07 20:28
I'm unable to repro the issue so far.

**Comment by hongdai** [comment] 2017-09-29 17:47
Haven't found a clue from inspecting the code. Closing it as no further action could be taken.

**Closed by hongdai** 2017-09-29 17:47 UTC
Labels: Community, tooling
