### ISSUE TITLE
HttpTransportBindingElement.UseDefaultWebProxy not working

### ISSUE THREAD

**Issue by f0rt** [dotnet/wcf#2436] opened 2017-12-08 13:03 UTC
Team,

The setting "HttpTransportBindingElement.UseDefaultWebProxy" doesn't work as expected when set to "true" on .Net Core. I've used Fiddler to see if the data goes trough the default proxy. It is working fine on .Net Framework. 
Looking through [the code](https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs#L50) shows that the _useDefaultWebProxy is not initialized and is always "false". This seems like a bug.

Let me know if you need more information.

Thanks,
f0rt

**Comment by zhenlan** [comment] 2018-01-10 03:36
Duplicate of #1592

**Closed by zhenlan** 2018-01-10 03:36 UTC
