### ISSUE TITLE
Visual Studio WCF Connected Service tool fails on soap:Header

### ISSUE THREAD

**Issue by linflux** [dotnet/wcf#1698] opened 2016-12-09 14:37 UTC
I'm in trouble with this extension tool in VS 2015 with ASP.NET Core (using version 1.1) .
I have one SOAP service and when I try to execute some methods there are missings parameters. 
I try a lot of things, change the generate Reference.cs file to include this soap:Header UserCredentials, like the old tool in .NET 4.6 does but failed too. Can anyone help me please?

[VisualStudioWCFConnectedServiceTool](https://marketplace.visualstudio.com/items?itemName=erikcai-MSFT.VisualStudioWCFConnectedService)

Below a sample of one of post request body:
```xml
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header>
    <UserCredentials xmlns="http://www.foo.com/bar">
      <userid>abcxyz</userid>
      <password>wordpass</password>
    </UserCredentials>
  </soap:Header>
  <soap:Body>
    <PromoWork xmlns="http://www.foo.com/bar">
      <PromoWork_Request>
        <AccountNumber>0000000000000000</AccountNumber>
        <PrimaryAccountNumber></PrimaryAccountNumber>
      </PromoWork_Request>
    </PromoWork>
  </soap:Body>
</soap:Envelope>
```

Sample of generate code from this preview tool:
```c#
public System.Threading.Tasks.Task<PayService.PromoWorkResponse1> PromoWorkAsync(PayService.PromoWorkRequest PromoWork_Request)
{
    PayService.PromoWorkRequest1 inValue = new PayService.PromoWorkRequest1();
    inValue.PromoWork_Request = PromoWork_Request;
    return ((PayService.PrepaidServicesSoap)(this)).PromoWorkAsync(inValue);
}
```

Generate code from old .NET 4.6:
```c#
public System.Threading.Tasks.Task<OldWebAppSoapTest.PayService.PromoWorkResponse1> PromoWorkAsync(OldWebAppSoapTest.PayService.UserCredentials UserCredentials, OldWebAppSoapTest.PayService.PromoWorkRequest PromoWork_Request) {
    OldWebAppSoapTest.PayService.PromoWorkRequest1 inValue = new OldWebAppSoapTest.PayService.PromoWorkRequest1();
    inValue.UserCredentials = UserCredentials;
    inValue.PromoWork_Request = PromoWork_Request;
    return ((OldWebAppSoapTest.PayService.PrepaidServicesSoap)(this))
}
```

I try to call on a Controller Web API like this:
```c#
private async Task<PromoWorkResponse1> GetSomeStuff()
{
            PrepaidServicesSoapClient client = new PrepaidServicesSoapClient(PrepaidServicesSoapClient.EndpointConfiguration.PrepaidServicesSoap12);

            //should have another parameter for UserCredentials on .NET Core
            var response = await client.PromoWorkAsync(request);
            //this is the way that works on NET 4.6
            //var response = await client.PromoWorkAsync(user, request);

            return response;
}
```

After change on Reference.cs for add this parameter on methods like the old tool do I receive an exception:
```
"Operation is not supported on this platform."
  at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Some.Thing.Api.Controllers.FooController.<GetSomeStuff>d__7.MoveNext() in C:\Users\MyUser\projects\project01\src\something\Controllers\FooController.cs:line 193
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Some.Thing.Api.Controllers.FooController.<Get>d__3.MoveNext() in C:\Users\MyUser\projects\project01\src\something\Controllers\FooController.cs:line 34
```

**Comment by hongdai** [comment] 2016-12-09 17:58
Passing UserCredentials is not supported yet by the WCF Connected Service VS Extension Preview for .NET Core and ASP.NET Core tool. The product team is evaluating the feasibility to support it.

However, make changes to the reference.cs should work. Do you have a repro service that I can use to reproduce it in house?

**Comment by linflux** [comment] 2016-12-09 20:03
@hongdai Thanks for answer me. 
Unfortunately I can't share with you the URL API Address for security reasons. 

Could you show me some repository, link, or blog with the changes needed in Reference.cs for support UserCredentials ? I already try to find this but can't find it.

Some more parts of Referece.cs.

The OperationContract:
```c#
[System.ServiceModel.OperationContractAttribute(Action="http://www.foo.com/bar/PromoWork", ReplyAction="*")]
[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
System.Threading.Tasks.Task<FooBarService.PromoWorkResponse1> PromoWorkAsync(FooBarService.PromoWorkRequest1 request);
```

Add UserCredentials as parameter of this method:
```c#
public System.Threading.Tasks.Task<FooBarService.PromoWorkResponse1> PromoWorkAsync(FooBarService.UserCredentials UserCredentials, FooBarService.PromoWorkRequest PromoWork_Request)
{
    FooBarService.PromoWorkRequest1 inValue = new FooBarService.PromoWorkRequest1();
    inValue.UserCredentials = UserCredentials;
    inValue.PromoWork_Request = PromoWork_Request;
    return ((FooBarService.PrepaidServicesSoap)(this)).PromoWorkAsync(inValue);
}
```

Add a prop for UserCredentials in PromoWorkRequest1:

```c#
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PromoWork", WrapperNamespace="http://www.foo.com/bar", IsWrapped=true)]
    public partial class PromoWorkRequest1
    {
        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://www.foo.com/bar")]
        public FooBarService.UserCredentials UserCredentials;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.foo.com/bar", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FooBarService.PromoWorkRequest PromoWork_Request;
        
        public PromoWorkRequest1()
        {
        }

        public PromoWorkRequest1(FooBarService.UserCredentials UserCredentials, FooBarService.PromoWorkRequest PromoWork_Request)
        {
            this.UserCredentials = UserCredentials;
            this.PromoWork_Request = PromoWork_Request;
        }
    }
```

**Comment by hongdai** [comment] 2016-12-10 05:02
Could you attach the generated reference.cs(remove the sensitive information)? It's helpful to take a look at the FooBarService code.

**Comment by linflux** [comment] 2016-12-13 18:01
@hongdai i sent an email to @zhenlan with this attachment. Hope he could foward to you.

**Comment by hongdai** [comment] 2016-12-21 19:02
@linflux , I have got a chance to take a look the generated reference.cs. I believe the client credential needs to be set on the clientBase. Could you send me the app.config and reference.cs from the old .NET 4.6 tool? I can probably figure out exactly what needs to be set by looking at the them.

**Comment by linflux** [comment] 2016-12-22 14:48
@hongdai I sent you an email with the files.

**Comment by hongdai** [comment] 2016-12-22 22:04
@linflux the web.config file seems incorrect. For example, https cannot have basicHttpBinding. Could you double check and ensure all the related information are included? The web.config file is important because 4.6 tools use config file to configure binding security information.

**Comment by hongdai** [comment] 2016-12-23 00:56
@linflux  After dig into the reference.cs you provided, I figure it out this is the same issue as #702.

Thanks for reporting it! It helps the product team evaluating the priority of the issue.

**Comment by hongdai** [comment] 2016-12-31 00:49
Closing this issue as it's tracked by #702.

**Closed by hongdai** 2016-12-31 00:49 UTC
Labels: Community, tooling
