### ISSUE TITLE
Make ServiceUri a required parameter for running outerloop tests against an existing service

### ISSUE THREAD

**Issue by zhenlan** [dotnet/wcf#1120] opened 2016-05-04 10:24 UTC
This is to continue [this discussion](https://github.com/dotnet/wcf/issues/1098#issuecomment-215615545). As designed, ServiceUri is a required parameter for outerloop testing and it is the case today for all cross machine/cross platform testing. However, on Windows, we opportunistically reuse an existing servicing running on the same machine if ServiceUri is not specified. This (magic) causes confusion and inconsistency for running outerloop tests on different platforms. It also complicates some of the automation. Instead, we should fail early once we detected a service is already running but ServiceUri is not specified and provide detailed error message something like below:

> "We cannot start a new service as we detected there was already a servicing running on local machine. If you want to use the existing service, please pass /p:ServiceUri=localhost to the build.cmd. Alternatively, please shut down the existing service and we will create a new one for you.".

**Comment by roncain** [comment] 2016-05-04 15:35
I think this discussion should be considered "As proposed" rather than "As designed" because it represents a change from what we have been using satisfactorily to date (both with BridgeHost and ServiceUri).

I think you will find that the dev experience will be degraded by this proposal.  The only time a service is already running on the dev machine is either (a) the dev started self-host manually, or (b) the dev has configured for IIS hosted locally.  In either case, the experience of reusing a running service vs. having the service self-start is the same -- just 'build.cmd /p:WithCategories=OuterLoop'.

This proposal now requires the dev to become aware of ServiceUri for the first time, even to run locally. And their "normal" way of running locally will now produce a build error.  I know dev's will run into this and be confused (because I know I will trip over it).

The only time a running service can be reused (due to an unspecified ServiceUri) is on Windows, so I don't think there is any confusion on non-Windows machines.  To run cross-machine (and cross-plat), the dev *must* become aware of ServiceUri.  But until then, there is no need to confront them with it.

I still believe this proposal is trying to optimize for CI at the expense of the dev experience.

I don't want to block on this point, but I believe it will become an inconvenience to the dev experience and be a source of confusion during local debugging -- not the other way around as stated.  If someone prepares a prototype PR with this change, we should ask the devs to try it out, especially using VS to debug services, using locally hosted IIS, manually started self-hosted, etc.

**Comment by zhenlan** [comment] 2016-05-05 00:28
Thank you for sharing you input @roncain. Appreciate it. I will try to respond to your key points, but please let me know if I missed anything.

> This proposal now requires the dev to become aware of ServiceUri for the first time, even to run locally.

For first time devs who are not aware of the requirement of service to run outerloop tests, our build script `'build.cmd /p:WithCategories=OuterLoop` will continue to start the self hosted WCF service automatically without the need to specify ServiceUri. This is not changed. For devs who already know to start WCF service manually, it is fair to require them to specify the ServiceUri explicitly, so we don't pick up a service unintentionally, for example, a dev has service setup on IIS while having a lingering self-hosted service process running on the same box too. While her/his intention is to run against IIS we simply pick self-hosted service silently.

> And their "normal" way of running locally will now produce a build error.

The error message will increase the awareness and is educational. We want our devs to be ready for x-plat development and are aware of the need of ServiceUri, don't we?

> The only time a running service can be reused (due to an unspecified ServiceUri) is on Windows, so I don't think there is any confusion on non-Windows machines.  To run cross-machine (and cross-plat), the dev must become aware of ServiceUri.

This is exactly the point I am trying to convey. Everyone then needs to remember these "the only time" of how A works, "the only time" of how B works and so on so forth. Over the time they will add up, confuse people who are new and increase the learning curve. To maintain these special cases, they will make future designs even more complicated. We should try to avoid entering such a circle but stay simple whenever we can. We are developing a x-plat framework. As you said "dev must become aware of ServiceUri", why must we special case Windows?

> I think you will find that the dev experience will be degraded by this proposal.
> I believe it will become an inconvenience to the dev experience 

Just to make sure we are talking about the same thing - the "degraded" experience or "inconvenience" will be to type the extra `/p:ServiceUri=xxx`. How bad is it? Most of the time, people may just copy/paste it or use doskey to get it from the command history.

> If someone prepares a prototype PR with this change, we should ask the devs to try it out, especially using VS to debug services, using locally hosted IIS, manually started self-hosted, etc.

Agreed. We should make sure the debugging experience is still excellent!

**Comment by roncain** [comment] 2016-05-05 14:27
Thanks @Zhenlan.  High order bit -- don't let me block progress.  I am just giving my dev reaction to the proposal, and I continue to believe it will be (mildly) disruptive to dev workflow, at least mine.  I guess testing a PR prototype will tell if others find it so.

That said, I think your last point is right on target -- ensure an *excellent* debug experience (not "good enough", but excellent)!  To that end, I think we can gain clarity if we clearly articulate the steps required for a dev to do each of the following.  I think it will add perspective to the ServiceUri discussion above.

On a developer's Windows machine:
 - Run all OuterLoops from the CMD line using self-host (expect auto-start)
 - Run all OuterLoops from the CMD line using IIS-host (expect auto activation)
 - Do both of the above, one after the other.
 - Debug a test using self-host
 - Debug a test using IIS-host
 - Debug server-side code using self-host
 - Debug server-side code using IIS-host
 - Debug self-host startup and service activation
 - Debug IIS-host service activation

The last 2 become important when you add a new endpoint -- not an everyday experience but when you do, as almost all of us have, you often need to debug the service host factory execution.

On X-plat:
 - Run all OuterLoops on CMD line
 - Debug an OuterLoop test
 - Debug an OuterLoop test and server-side code at the same time (multi-machine testing)

We can discuss this separately, of course, either now or later.  I bring it up here because the /p:ServiceUri=xxx discussion is focused only on the CMD line experience with an already running service, which is a fairly narrow slice of the dev experience.  Seeing how it plays out in the other dev scenarios will give us more context to choose wisely.

**Comment by roncain** [comment] 2016-12-05 17:59
@zhenlan -- do you still recommend we do this work, or can we close it?  We seem to be working fine as is.  If we change it, we may need to update docs, CI scripts and Helix runs.

**Closed** 2017-06-13 21:49 UTC
Labels: Design Discussion, Infrastructure
