### ISSUE TITLE
Reading AXIS wsdl error with Microsoft WCF Web Service Reference Provider

### ISSUE THREAD

**Issue by Tecnico1** [dotnet/wcf#2360] opened 2017-10-25 15:35 UTC
When I try to read wsdl from "http://www.axis.com/vapix/ws/action1/ActionService.wsdl", there is not problem with Visual Studio 2015, but with the new tool ("Microsoft WCF Web Service Reference Provider") for Visual Studio 2017 I never get a response, always with "Please wait..." message.

**Comment by mlacouture** [comment] 2017-10-30 17:11
Hi @Tecnico1 

Thank you for reporting this issue.  This is the same problem as discussed in issue #2104. Please use issue #2104 to track progress

Miguel Lacouture

**Comment by mlacouture** [comment] 2017-10-30 17:11
Duplicate of #2104

**Closed by mlacouture** 2017-10-30 17:11 UTC
Labels: Community, tooling
