### ISSUE TITLE
The build failed. Please fix the build errors and run again.

### ISSUE THREAD

**Issue by maikebing** [dotnet/wcf#3320] opened 2018-12-21 09:35 UTC
The build failed. Please fix the build errors and run again.

**Comment by dasetser** [comment] 2019-01-02 18:02
@maikebing Can you give us some more information on what the problem you're having is? It sounds like you're running into some build errors related to the wsdl file you attached. 

Are you saying you used the WCF Web Service Reference Provider and the Reference.cs it generated won't compile? What kind of build errors are you seeing?

**Comment by maikebing** [comment] 2019-01-03 01:39
used the WCF Web Service Reference Provider ，This error is reported when referencing WCF, some machines appear, and some do not.VS2017 and VS2019 have this problem, and at the moment I don't know why this is happening. I'm going to focus on that.

**Comment by maikebing** [comment] 2019-01-07 01:45
just get the message "The build failed. Please fix the build errors and run again." , no code , no more message !

**Comment by maikebing** [comment] 2019-01-07 02:00
![095832](https://user-images.githubusercontent.com/3445167/50745054-05360780-1263-11e9-9bfe-ff5e37b31e35.jpg)

**Comment by dasetser** [comment] 2019-01-07 18:35
The ConsoleApp1.csproj in your attachment does not include the PackageReferences to the ServiceModel packages. Are these not being added to your project when you run the tool? Does your project work correctly if you manually add them? If so that would definitely be a bug and we would need to figure out why they're not being generated for you.

Do you see build errors when doing "Build Solution" (or dotnet build)? It's strange that you're just seeing a message saying to fix the build errors if you're not seeing any build errors. I apologize for all the questions. I'm unable to reproduce this myself so it's difficult to narrow down why you are hitting this.

**Comment by maikebing** [comment] 2019-01-07 23:37
I removed it.

**Comment by dasetser** [comment] 2019-02-14 23:04
@maikebing It looks like the Connected Service tool runs successfully, but the problem is that when you try to run the project you get an error saying to fix the build errors and run again, correct? Are you still hitting this issue? Do you get any errors when you try to simply build (not run) the project?

**Comment by Lxiamail** [comment] 2019-04-17 16:35
Close the issue. Please reopen if you still have problem.

**Closed by Lxiamail** 2019-04-17 16:35 UTC
Labels: tooling
