### ISSUE TITLE
Error: Invalid URI: The format of the URI could not be determined

### ISSUE THREAD

**Issue by Brett-Bailey** [dotnet/wcf#3302] opened 2018-12-02 01:21 UTC
When attempting to load the attached wsdl, I get the error below. This wsdl works fine in all different versions of Visual Studio and other apps, but not in WCF with .net standard 2.0. Changed real site name to just site, but everything else is the same.

[dpt.zip](https://github.com/dotnet/wcf/files/2636495/dpt.zip)

Warning: Cannot import wsdl:port
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Channels.TransportBindingElementImporter
Error: Invalid URI: The format of the URI could not be determined.
XPath to Error Source: //wsdl:definitions[@targetNamespace='http://wwwapps.site.com/dpt/dpt.xsd']/wsdl:service[@name='dptService']/wsdl:port[@name='dptSoap11']

**Comment by dasetser** [comment] 2018-12-21 19:32
@Brett-Bailey Do you own this service? It looks like the error is caused by this line in the wsdl:
<soap:address location="/dpt/ws/" />

Is there a reason this is not an absolute address? From what I can tell it should be, and the error is caused because we try to treat it as one and end up not being able to parse the URI correctly. We can look into how other tools handle this scenario, but I'm not sure it's valid.

**Comment by dasetser** [comment] 2019-02-14 23:05
Closing this issue since it looks like the wsdl is invalid.

**Closed by dasetser** 2019-02-14 23:05 UTC
Labels: tooling
