### ISSUE TITLE
Microsoft WCF Web Service Reference Provider HRESULT:0x80131500

### ISSUE THREAD

**Issue by Elprogrammador** [dotnet/wcf#2077] opened 2017-07-17 02:53 UTC
I'm getting the following error when I try to add a new Connected Service:

"Connected Services. The Connected Services component 'Microsoft WCF Web Service Reference Provider - Preview' failed: (HRESULT:0x80131500) One or more errors occurred"

**Comment by ali61n60** [comment] 2017-07-17 14:10
I get the same error too

**Comment by chaseWillden** [comment] 2017-07-17 16:40
I'm getting the same error, please fix

**Comment by macho0001** [comment] 2017-07-17 17:21
Same here

**Comment by Cyrus-Sushiant** [comment] 2017-07-17 22:43
I get the same error

**Comment by zhenlan** [comment] 2017-07-17 23:20
Thanks for reporting the issue.

Duplicate of #2076

**Closed** 2017-07-24 23:51 UTC
Labels: Community, tooling
