### ISSUE TITLE
Wrap all scenario tests with a configurable timeout.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#491] opened 2015-10-30 16:22 UTC
Make it configurable so that it can be changed easily for debugging.

**Comment by iamjasonp** [comment] 2015-11-04 12:07
Dup of #416?

**Comment by roncain** [comment] 2015-11-04 13:31
Yes, dupe of #416, so I assigned that one to @StephenBonikowsky and closed this one.

**Closed by roncain** 2015-11-04 13:31 UTC
Labels: test bug
