### ISSUE TITLE
Error Adding Connected Service with dor net 2.2

### ISSUE THREAD

**Issue by bilalmalik777** [dotnet/wcf#3335] opened 2019-01-14 15:31 UTC
Hi,

I'm trying to use the "Add Connected Service" feature inside the VS2017 but I'm getting the following error message all the time.
![wcfcapture](https://user-images.githubusercontent.com/23011613/51121979-97797500-183a-11e9-8f03-bd1375d9cc02.PNG)
I am using dot net core 2.2 and visual studio versio is15.9.3

**Comment by StephenBonikowsky** [comment] 2019-01-14 18:51
Thanks for reporting the issue @bilalmalik777 !

**Comment by dasetser** [comment] 2019-01-14 19:32
@bilalmalik777 This sounds like a bug in the tool. Do you get this for every service you try to use the tool with (for example, on a newly created WCF Service project in VS)? Or is this specific to one service?

There are two things you could try that would help us see what's causing this so we can get this fixed:
1) Use the [dotnet-svcutil](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide) command line tool to add this service reference to the project and add the "-v Debug" parameter. The output of this should help us see what's causing the error.

2) Alternatively, if this is specific to one service you're trying to use if you can attach the wsdl for us we can try reproducing it ourselves to investigate. You can append "?singleWsdl" to the service address to get the wsdl from a WCF service

**Comment by bilalmalik777** [comment] 2019-01-15 09:18
@dasetserI am facing this issue in case of dot net core but with dot net 4.6 its work perfectly. 
I will try the first option to find the exact error
I cannot share anything with you relating to services because the client does not allow us to do that and services can only be accessed from client created VM.

**Comment by joaopauloit** [comment] 2019-01-30 17:37
> @bilalmalik777 This sounds like a bug in the tool. Do you get this for every service you try to use the tool with (for example, on a newly created WCF Service project in VS)? Or is this specific to one service?
> 
> There are two things you could try that would help us see what's causing this so we can get this fixed:
> 
> 1. Use the [dotnet-svcutil](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide) command line tool to add this service reference to the project and add the "-v Debug" parameter. The output of this should help us see what's causing the error.
> 2. Alternatively, if this is specific to one service you're trying to use if you can attach the wsdl for us we can try reproducing it ourselves to investigate. You can append "?singleWsdl" to the service address to get the wsdl from a WCF service

Hi @dasetser .
See my stack trace:

[6752.872] Time elapsed: 00:00:00.7110734
dotnet sdk version:2.1.503
[6752.846] Time elapsed: 00:00:00.7469745
[6752.740] Time elapsed: 00:00:00.8546778
Attempting to download metadata from 'https://grupotecnoset--tst1.custhelp.com/services/soap/connect/soap?wsdl' using WS-Metad
ata Exchange and HttpGet.
[6752.846] Importing metadata ...
Warning: Cannot import wsdl:binding
Detail: An exception was thrown while running a WSDL import extension: System.ServiceModel.Channels.StandardBindingImporter
Error: The method or operation is not implemented.
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:wsdl.ws.rightnow.com/v1_4']/wsdl:binding[@name='RightNowSyncBi
nding']
Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:wsdl.ws.rightnow.com/v1_4']/wsdl:service[@name='RightNowSyncSe
rvice']/wsdl:port[@name='RightNowSyncPort']
Warning: Cannot import wsdl:binding
Detail: An exception was thrown in a call to a policy import extension.
Extension: System.ServiceModel.Channels.SecurityBindingElementImporter
Error: The method or operation is not implemented.
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:wsdl.ws.rightnow.com/v1_4']/wsdl:binding[@name='RightNowFedAut
hSyncBinding']
Warning: Cannot import wsdl:port
Detail: 
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:wsdl.ws.rightnow.com/v1_4']/wsdl:service[@name='RightNowSyncSe
rvice']/wsdl:port[@name='RightNowFedAuthSyncPort']
Warning: No endpoints compatible with .Net Core apps were found.
[6752.846] Time elapsed: 00:00:12.3939735
[6752.240] Processing Code DOM ...
Generating files...

It does not generate correct the service reference.

Can you help?

Tks

**Comment by joaopauloit** [comment] 2019-01-30 18:12
Cannot import wsdl:port
Detail: There was an error importing a wsdl:binding that the wsdl:port is dependent on.
XPath to wsdl:binding: //wsdl:definitions[@targetNamespace='urn:wsdl.ws.rightnow.com/v1_4']/wsdl:binding[@name='RightNowFedAuthSyncBinding']
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:wsdl.ws.rightnow.com/v1_4']/wsdl:service[@name='RightNowSyncService']/wsdl:port[@name='RightNowFedAuthSyncPort']
Cannot import wsdl:binding
Detail: An exception was thrown in a call to a policy import extension.
Extension: System.ServiceModel.Channels.SecurityBindingElementImporter
Error: An unsupported security policy assertion was detected during the security policy import: <sp:SignedSupportingTokens xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"><wsp:Policy xmlns:wsp="http://www.w3.org/ns/ws-policy"><sp:IssuedToken sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient"><sp:RequestSecurityTokenTemplate><t:TokenType xmlns:t="http://docs.oasis-open.org/ws-sx/ws-trust/200512">http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLV2.0</t:TokenType><t:KeyType xmlns:t="http://docs.oasis-open.org/ws-sx/ws-trust/200512">http://docs.oasis-open.org/ws-sx/ws-trust/200512/Bearer</t:KeyType><t:CanonicalizationAlgorithm xmlns:t="http://docs.oasis-open.org/ws-sx/ws-trust/200512">http://www.w3.org/2001/10/xml-exc-c14n#</t:CanonicalizationAlgorithm><t:SignWith xmlns:t="http://d...
XPath to Error Source: //wsdl:definitions[@targetNamespace='urn:wsdl.ws.rightnow.com/v1_4']/wsdl:binding[@name='RightNowFedAuthSyncBinding']

**Comment by dasetser** [comment] 2019-01-31 18:23
@joaopauloit It looks like you're having a different problem than the one reported in this issue. I'll follow up on issue #3371 which it looks like you filed for the problem you're having.

**Comment by joaopauloit** [comment] 2019-01-31 18:40
@dasetser Okay. I found it after I created the issue.

Tks

**Comment by dasetser** [comment] 2019-02-14 22:59
@bilalmalik777 Did you ever get a chance to try this with dotnet-svcutil's verbosity increased so we can find a callstack for this issue?

**Comment by Lxiamail** [comment] 2019-02-20 21:23
Closing the issue for now. @bilalmalik777 Please feel free to reactivate the issue with additional information that Daniel suggested if you still need help.

**Closed by Lxiamail** 2019-02-20 21:23 UTC
Labels: needs more info, tooling
