### ISSUE TITLE
Unit tests using null values are failing in UWP.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#1449] opened 2016-08-04 20:34 UTC
Unit tests that use 'null' as an "InlineData" value are failing. No other data is available right now as there are no logs produced. Theory tests do not run in ToF so this is the first time these tests have been run in a long time (in NetNative).

System.ServiceModel.Primitives\tests\ServiceModel: MessageContractTest.WrapperName_Property_Sets_Throws_ArgumentNull
System.ServiceModel.Primitives\tests\ServiceModel: MessageContractTest.WrapperNamespace_Property_Sets
System.ServiceModel.Primitives\tests\Channels: CustomBindingTest.CustomBinding_Name_Property_Set_Throws
System.ServiceModel.Http\tests\ServiceModel: BasicHttpBindingTest.Name_Property_Set_Invalid_Value_Throws
System.ServiceModel.Http\tests\ServiceModel: BasicHttpBindingTest.Namespace_Property_Set_Invalid_Value_Throws

**Comment by roncain** [comment] 2016-08-05 15:08
Stack trace from bin\tests\...\testResults.xml:
```
      </test>
      <test name="MessageContractTest.WrapperNamespace_Property_Sets" type="MessageContractTest" method="WrapperNamespace_Property_Sets" time="0" result="Fail">
        <failure exception-type="$BlockedFromReflection_1_d9deefc4">
          <message><![CDATA[$BlockedFromReflection_1_d9deefc4 : Reflection_InsufficientMetadata_NoHelpAvailable, <unavailable>. For more information, visit http://go.microsoft.com/fwlink/?LinkId=623485]]></message>
          <stack-trace><![CDATA[   at System.Reflection.Runtime.General.ReflectionCoreCallbacksImplementation.GetTypeInfo(Type type) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Reflection.Core\src\System\Reflection\Runtime\General\ReflectionCoreCallbacksImplementation.cs:line 38
   at Internal.Reflection.Core.Execution.Binder.DefaultBinder.BindToMethod($MethodBase[] match, Object[]& args) in f:\dd\ndp\fxcore\src\Common\Internal\Reflection\Execution\Binder\DefaultBinder.cs:line 172
   at Internal.Reflection.Execution.ReflectionExecutionDomainCallbacksImplementation.ActivatorCreateInstance(Type type, Object[] args) in f:\dd\ndp\fxcore\src\System.Private.Reflection.Execution\Internal\Reflection\Execution\ReflectionExecutionDomainCallbacksImplementation.cs:line 103]]></stack-trace>
        </failure>
      </test>
```

**Comment by roncain** [comment] 2016-08-09 14:06
The root cause is that this expression causes an issue in UWP when the toolchain processes it:
```
 [InlineData(null)]
```

This is due to the fact InlineData's ctor expects a 'params object[] data' and the null becomes a null object[] array, not an array containing a null.  This issue is being tracked outside of GitHub because the toolchain is not currently open source.  The workaround is to use this syntax:
```
 [InlineData(new object[] {null})]
```
This workaround has been applied to WCF test projects so that they can pass.  This issue number has been left as a comment in the code at the workarounds.  Those comments should be removed when the toolchain issue is resolved.

**Comment by roncain** [comment] 2016-10-11 14:35
Confirmed on 10/11/16 this is still broken.  But because the workaround above works fine, and because there is an open issue for this in VSO against the ILC toolchain, I believe we can close this.  But we should probably cleanup the test code to remove references to this issue.  Thoughts?

**Comment by zhenlan** [comment] 2016-10-20 03:05
Agreed to do the cleanup and close this issue.

**Closed** 2016-10-20 20:32 UTC
Labels: Infrastructure, test bug, tracking, UWP
