### ISSUE TITLE
Error adding connected service with new version

### ISSUE THREAD

**Issue by geno-github** [dotnet/wcf#2078] opened 2017-07-17 14:16 UTC
Error when attempting to add a connected service to a DotNetCore 1.1 project in VS 2017 (15.2) with version  0.5.10712.1027.  Was able to do this with previous versions and with VS 2015.

Steps to repro:

1.  Right-click "Connected Services" in project, choose "Add Connected Service"
2.  Click "Microsoft WCF Web Service Reference Provider - Preview"

Error message:

"<Title> Connected Services <body> The Connected Services component 'Microsoft WCF Web Service Reference Provider - Preview' failed: (HRESULT:0x80131500) One or more errors occurred."

Would like some help troubleshooting this error or at least a path to downgrade to the previous version that was working for me.

**Comment by chrisstaley** [comment] 2017-07-17 15:07
I am getting the same error as well in a DotNetCore 1.0 project in VS 2017 using the same repro steps.

**Comment by chaseWillden** [comment] 2017-07-17 16:40
I get the same issue. Please fix

**Comment by macho0001** [comment] 2017-07-17 17:21
Same here

**Comment by zhenlan** [comment] 2017-07-17 23:20
Thanks for reporting the issue.

Duplicate of #2076

**Closed** 2017-07-24 23:52 UTC
Labels: Community, tooling
