### ISSUE TITLE
Organize Unit tests properly.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/wcf#66] opened 2015-06-02 21:03 UTC
There are some questions on how unit tests are organized particularly tests of non-public APIs. Also, the unit test cs projects use the convention "\*.cs" to pull in all files to compile, this works great except in the project located under System.Private.ServiceModel\tests since that location also contains the scenario tests, this particular project needs to be changed in some fashion.

**Comment by iamjasonp** [comment] 2015-06-10 14:25
Is #75 a dupe of this?

**Comment by roncain** [comment] 2015-06-10 16:08
They are related. #75 has more details for the recommended approach, and #66 describes an actual bug with the current layout. Whoever gets one should own both.,

**Comment by StephenBonikowsky** [comment] 2015-07-06 23:02
The Unit test project under System.Private.ServiceModel\tests has now been moved under its own Unit directory so this issue is solved. There is one clean-up related matter which can be done as part of PR141 for this to be complete. Removing the condition: Exclude="Scenarios\**\*

**Closed** 2015-07-07 21:32 UTC
Labels: 2 - In Progress, enhancement, test bug
