### ISSUE TITLE
Usage of local relative paths in ConnectedService.json file

### ISSUE THREAD

**Issue by WebDucer** [dotnet/wcf#3264] opened 2018-11-19 12:58 UTC
It would be nice to be able to use relative paths for local WSDL files in the `ConnectedService.json` file. Now, if we add a new service, that is generated from local WSDL file (file is inside the project / solution repository), a full abolute path is stored in the `ConnectedService.json` file.

```json
{
  "ProviderId": "Microsoft.VisualStudio.ConnectedService.Wcf",
  "Version": "15.0.20119.1312",
  "ExtendedData": {
    "Uri": "C:\\src\\MySolution\\MyProject\\wsdl\\my-wsdl.wsdl",
  },
}
```

Is an another developer try to update the service, it fails because of different absolute path on his computer.

If we could use relative paths for local WSDL files, this problem would not happen.

```json
{
  "ProviderId": "Microsoft.VisualStudio.ConnectedService.Wcf",
  "Version": "15.0.20119.1312",
  "ExtendedData": {
    "Uri": "./wsdl/my-wsdl.wsdl",
  },
}
```

**Comment by dasetser** [comment] 2018-11-19 17:29
Thanks for the suggestion. We'll look into this.

**Comment by dasetser** [comment] 2019-05-15 18:52
After some investigation it looks like this is a bug. The dotnet-svcutil tool correctly uses a relative path, but for some reason the Connected Service is doing something that saves it as a full path. We'll investigate why this is happening and work on a fix.

**Comment by dasetser** [comment] 2019-08-16 17:49
This is fixed in the latest preview version of Visual Studio (VS 2019 16.3 Preview 2), which you can download from https://visualstudio.microsoft.com/vs/preview/. Thanks for reporting this so we could fix it!

**Comment by Jean-Marc1** [comment] 2020-02-27 17:58
This issue is still happening in VS2019 vs 16.4.5

**Comment by dasetser** [comment] 2020-02-28 19:07
@Jean-Marc1 Can you give some more information about what you're experiencing? We made a fix for this in 16.3 and without more information I'm not sure what to investigate. Do you see this when using the tool for an update or for generating a new proxy? Is it the wsdl path that isn't relative or some other path?

**Comment by Jean-Marc1** [comment] 2020-02-28 20:09
.Net Standard 2.0 class library project with a reference to a WCF .NetFramework 4.7.2 service...
The "references" node inside "ConnectedService.json" would should a physical path for a dependency dll (a project in the same solution).
Since the path is not the same on all developers' machine, this creates a bunch of compile errors.

**Comment by dasetser** [comment] 2020-03-04 20:00
Reopening since it looks like the fix we made may have been specific to only the wsdl file, which is why you would still experience this problem with the references node. We'll need to investigate and handle all paths the same way.

**Comment by emilwkarlsson** [comment] 2020-12-09 07:34
> .Net Standard 2.0 class library project with a reference to a WCF .NetFramework 4.7.2 service...
> The "references" node inside "ConnectedService.json" would should a physical path for a dependency dll (a project in the same solution).
> Since the path is not the same on all developers' machine, this creates a bunch of compile errors.

Experiencing the same as @Jean-Marc1 in VS2019 16.7.3

**Comment by AlNoes** [comment] 2021-06-21 13:27
"ExtendedData" -> "Endpoint" also can't be used with a relative path. It's kind of working but resolves to a full path using the location of the VS installation...

**Comment by imcarolwang** [comment] 2021-09-17 07:47
Hi @Jean-Marc1, the references node in ConnectedService.json is generated when running the tool to add WCF connected service. After the json file get generated it's not used during project compilation. Even though the physical reference path looks not right when moving to a different environment it should not cause compiling error. Are you able to share more details of your scenario? It will be great if you can provide a standalone project that can reproduce the problem. Thank you.

**Comment by Jean-Marc1** [comment] 2021-09-17 17:23
Sorry, it has been at least 1 year and half ago since the last report.  I moved on.

**Comment by imcarolwang** [comment] 2021-09-22 01:52
Since we can not repro the compiling error, closing this issue for now. Feel free to re-activate this issue if this is still an issue and provide the repro steps.

**Closed by imcarolwang** 2021-09-22 01:52 UTC
Labels: bug, tooling, priority 2
