### ISSUE TITLE
MTOM request is buffered with TransferMode.Streamed or TransferMode.StreameadRequest

### ISSUE THREAD

**Issue by MarcWils** [dotnet/wcf#4984] opened 2023-01-12 10:28 UTC
**Describe the bug**
We're migrating some of our WCF clients from .NET 4.7.2 to .NET 6. Some of these clients upload large files to a WCF streaming service (SOAP 1.1, MTOM, HTTPS). With .NET 4.7.2 this works quit well. Streaming works end-to-end from the client to the service. We're able to upload files up to 5GB. 

After migrating to .NET 6 (System.ServiceModel.Http 4.10.0) we notice the streaming concept is broken. The request is buffered in memory. Requests larger than 2.147.483.647 bytes are not allowed because of the maxSizeInBytes setting on the MTOM writer.

**To Reproduce**
1. Checkout this repository: https://github.com/MarcWils/WcfMtomStreaming. This contains both a full framework and .NET 6 sample project.

.NET 4.7.2 runs successfully sending a 4GB file to a WCF service. 

.NET 6 fails with:
System.Xml.XmlException: The 'maximum size in bytes' quota (2147483647) has been exceeded while writing MTOM data. This quota may be increased by changing the maxSizeInBytes setting used when creating the MTOM writer.

**Expected behavior**
WCF streaming works without buffering the request. Requests larger than 2GB should also work.

**Additional context**
I can see a difference in behavior with the XmlMtomWriter:
https://github.com/dotnet/wcf/blob/5830d45a94738f00c80361cc281e1249963d9650/src/System.ServiceModel.Primitives/src/Internals/System/Xml/XmlMtomWriter.cs#L291

Running the project in .NET 4.7.2 the WriterState is set to Content. The buffer is directly passed to the inner XmlDictionaryWriter.

Running the project in .NET 6 the WriterState is set to Element. Each block of 256 bytes is added to the _binaryDataChunks list. After reading 2147483647 from the request stream an exception is thrown:
https://github.com/dotnet/wcf/blob/5830d45a94738f00c80361cc281e1249963d9650/src/System.ServiceModel.Primitives/src/Internals/System/Xml/XmlMtomWriter.cs#L324

**Comment by HongGit** [comment] 2023-02-02 00:07
@afifi-ins can you please take a look at this and see if you can identify where the issue is?

**Comment by HongGit** [comment] 2023-07-12 18:48
This is fixed now.

**Closed by HongGit** 2023-07-12 18:48 UTC
Labels: triaged
