### ISSUE TITLE
Error 80131500

### ISSUE THREAD

**Issue by ricardag** [dotnet/wcf#2079] opened 2017-07-17 19:33 UTC
When clicking on the WCF Link on Project Connected Services we receive an error HRESULT 0x8131500 (please see attached evidence)
![image](https://user-images.githubusercontent.com/12039145/28286165-af2b4d4e-6b0d-11e7-989f-2577a4dcf90b.png)

**Comment by dbaghdanov** [comment] 2017-07-17 19:38
I'm getting this exact error as well.

Microsoft Visual Studio Professional 2017 
Version 15.2 (26430.16) Release
VisualStudio.15.Release/15.2.0+26430.16
Microsoft .NET Framework
Version 4.6.01590

I just installed, the WCF Web Service Reference Provider, today, Version: 0.5.10712.1027

**Comment by zhenlan** [comment] 2017-07-17 23:20
Thanks for reporting the issue.

Duplicate of #2076

**Closed** 2017-07-24 23:52 UTC
Labels: Community, tooling
