### ISSUE TITLE
Deserialization error (WCF Connected Service)

### ISSUE THREAD

**Issue by sumanthaus** [dotnet/wcf#1684] opened 2016-11-30 02:20 UTC
I tried this to connect to a SOAP service (not WCF) and I'am getting some de-serialization error:

"The content type text/xml; charset="utf-8" of the response message does not match the content type of the binding (text/xml; charset=utf-8). If using a custom encoder, be sure that the IsContentTypeSupported method is implemented properly."

I checked in Fiddler, the web service which I'am hitting is actually returning back the data. But somehow not able to deserialize the data back to those proxy classes

The same thing works absolutely fine in older .Net non core version through service reference. Has anybody experienced similar issue?

**Comment by sumanthaus** [comment] 2016-11-30 22:43
By the way the service being consumed uses SOAP 1.1. Could you please confirm if it supports SOAP 1.1 like the old "Service reference" used to? Thanks

**Comment by sumanthaus** [comment] 2016-12-01 23:02
Also, wanted to let you know that, it works fine when I re-target my asp.Net core application to .Net full framework 4.6.1 (still using WCF connected service). So, it might be issue with .Net core library rather than anything to do with WCF connected service itself.

**Comment by hongdai** [comment] 2016-12-06 21:38
@sumanthaus  do you have a repro that we can reproduce in house?

**Comment by sumanthaus** [comment] 2016-12-06 22:50
@hongdai I have attached the WSDL file and also the SOAP request and response messages. Using these you could probably re-create a dummy Soap Service and reproduce the issue.

Regards,

[FilesToReplicateError.zip](https://github.com/dotnet/wcf/files/635251/FilesToReplicateError.zip)

**Comment by hongdai** [comment] 2016-12-07 00:50
@sumanthaus I was able to use the WSDL file directly to generate the proxy client.

Could you try the latest version(0.4.21118.0) of the WCF connected service we just released?

**Comment by sumanthaus** [comment] 2016-12-08 05:47
@hongdai The problem is not in generating the Proxy. I was able to generate the proxy earlier as well. But when I make a call to the service, I get run-time exception. As pointed out earlier, I'am able to see the soap response in Fiddler. But, somehow its not able to de-serialize it. Please refer to the SOAP request and response messages from my previous message.

**Here is the Exception message:**
"The content type text/xml; charset=\"utf-8\" of the response message does not match the content type of the binding (text/xml; charset=utf-8). If using a custom encoder, be sure that the IsContentTypeSupported method is implemented properly. The first 1024 bytes of the response were: '<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<SOAP-ENV:Envelope xmlns:SOAP- ------------bla bla"

**Here is the Stack trace:**
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SampleCoreWebApi.Controllers.ValuesController.<Get>d__0.MoveNext()

**Comment by sumanthaus** [comment] 2016-12-08 05:54
@hongdai by the way, I'am using the latest version of the WCF Connected service (0.4.21118.0)

**Comment by hongdai** [comment] 2016-12-08 17:34
@sumanthaus Thanks for the clarification. I'll try to reproduce the runtime failure in house.

**Comment by sumanthaus** [comment] 2016-12-13 03:22
@hongdai This is a legacy service build using Microfocus and Cobol which is owned by different team all-together. So, its very difficult to provide the service code. Can we not walk backwards and build a service using the WSDL which would emit similar SOAP response as provided?

**Comment by hongdai** [comment] 2016-12-21 19:07
@sumanthaus It just takes much longer to investigate if no Repro App provided. That's why I suggested you provide the service if it's feasible.

Given it's very difficult for you, I will attempt to build a similar service.

**Comment by hongdai** [comment] 2016-12-22 01:55
@sumanthaus  Unfortunately I'm unable to reproduce the issue you are seeing by building a web service using the WSDL and SOAP response you provided. The client call succeeded for me.

**Comment by hongdai** [comment] 2017-01-03 16:34
@sumanthaus We will not be able to investigate further without a repro. I'm closing this issue. Please reopen it if you have a repro.

**Closed by hongdai** 2017-01-03 16:34 UTC
Labels: Community, tooling

**Comment by crackedcornjimmy** [comment] 2017-06-06 19:41
Is it possible to reopen this question? I'm having the same problem and hopefully can provide more information.

**Comment by ulmermark** [comment] 2018-07-13 16:17
Similar issue going on here....The SOAP Client generated from the WSDL works fine when run from a Unit Test.

The same SOAP Client code when invoked from a Controller ( receiving JSON) in  WEBAPI application produces the same error that you are seeing

I have tried various flavors of the BasicHttpBinding instance and EndpointAddress

Current code is shown below


```            var binding = new BasicHttpBinding (System.ServiceModel.BasicHttpSecurityMode.None);
            binding.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.None;
            binding.TextEncoding = System.Text.Encoding.UTF8;

            var endpoint = new EndpointAddress (new Uri (rocketApiOptions.Url));
            client = new SOAPClient (binding, endpoint); // this is the SOAP client generated from the WSDL
```

I have also just tried
``` binding = new BasicHttpBinding();
```

**Comment by Tonay** [comment] 2019-04-03 11:04
I have same issue and i tried every possible that could be solved. But i did not find any solution.

**Comment by ChetanSirigur** [comment] 2019-05-29 12:44
Do we have an alternate approach to overcome this issue ?

**Comment by obi111** [comment] 2020-09-17 07:58
I have the same issue ... any solutions??
