### ISSUE TITLE
wcf web service in visual studio 2017 taking very long time to add

### ISSUE THREAD

**Issue by HemaSK** [dotnet/wcf#3602] opened 2019-05-03 11:12 UTC

**Comment by HemaSK** [comment] 2019-05-03 11:14
Hi,
I created a WCF service application and I just run it. It is running correctly and I have the url 
And then I have created a Asp.Net Core Web application. Here, I tried adding the wcf service created. But, it is not adding and no error thrown. It is taking very very long time to add. Still it is loading

Any help please

**Comment by Lxiamail** [comment] 2019-05-07 00:39
@HemaSK Thanks for reporting the problem. Which version (build number) of VS 2017 that you are using. Since we haven't heard similar report before, I guess there may be something unique about your WCF server. Can you share the service URL if it is public or can you share the WSDL file? BTW, this repo is for WCF Client framework on .NET Core. Please use https://developercommunity.visualstudio.com/ to report  any VS related problem

**Comment by HemaSK** [comment] 2019-05-07 06:43
I will explain you step by step about the issue I am facing
I am using Visual Studio 2017 15.9 version. 

Step1: I have created a WCF Service Application as in screenshot below
![image](https://user-images.githubusercontent.com/50235354/57276659-e126ed80-70bf-11e9-8496-0e6d0f0a5a8e.png)

Step2: I simply build and run the application and had the output as below which is correct, The url is http://localhost:58198/Service1.svc
![image](https://user-images.githubusercontent.com/50235354/57276814-47137500-70c0-11e9-9271-026791231cf2.png)

Step3: I have created a .Net Core Web Application as in screenshot below
![image](https://user-images.githubusercontent.com/50235354/57276949-9bb6f000-70c0-11e9-9191-df323302c90e.png)

Now, since I want the GetData method in the WCF service to be consumed in the .Net Core application which I have just created, I am adding the service in Adding Connected Service option as below
![image](https://user-images.githubusercontent.com/50235354/57277108-13851a80-70c1-11e9-8997-afea853ef1dd.png)

But, after giving all the WCF Web Service Reference and click Finish, the Web Service is not actually adding. It keep on scrolling for more than hours as below
![image](https://user-images.githubusercontent.com/50235354/57277193-43342280-70c1-11e9-9f07-dedfe814cd00.png)


Any help on this

Thanks

**Comment by dasetser** [comment] 2019-05-08 18:17
@HemaSK Thanks for the detailed information. A few questions about this:

1) Do you have the .NET Core 3.0 SDK installed on your machine? There are a few issues with using this tool on VS2017 if you have .NET Core 3.0 installed that are fixed in the VS2019 version.

2) Which option do you select when creating the web application? Is it just an empty app? Or do you use one of their built-in templates (like Web Forms, MVC, etc)?

3) Can you attach the logs/generated project for the run as a zip file? To do this you just need to run go to the %temp%\WCFConnectedService directory and find the folder with the date/time for the run that you experienced the error for, and zip and attach that folder to this issue.

**Comment by HemaSK** [comment] 2019-05-09 06:37
Hi
1. No, I have .Net Core 2.1.505 SDK installed in my machine and .Net Core 3.0 SDK is **not** installed
2. I select Empty to create my Web application
3. I have attached the log file zipped
[2019_May_09_12_05_03.zip](https://github.com/dotnet/wcf/files/3160661/2019_May_09_12_05_03.zip)


Thanks for the help

**Comment by dasetser** [comment] 2019-05-15 19:10
There are two possibilities based on your logs for what's happening:
1) Something is causing a `dotnet restore --ignore-failed-sources` command in the C:\Users\774715\AppData\Local\Temp\WCFConnectedService\2019_May_09_12_05_03\svcutil_starter directory to block. You should be able to verify if this is the cause by running the command manually and seeing if it completes. If it does not complete you'll want to follow up on the dotnet CLI repository to see if they can help determine why.

2) You are hitting a deadlock in the WCF Connected Service code. We fixed a few deadlocks similar to this in VS2019, so I would suggest upgrading to VS2019 if #1 is not the cause.

**Comment by dmitriy-shleht** [comment] 2019-05-16 13:27
>     2. You are hitting a deadlock in the WCF Connected Service code. We fixed a few deadlocks similar to this in VS2019, so I would suggest upgrading to VS2019 if #1 is not the cause.

There is another problem at the VS2019 16.0.4 links are not added at all or are added incorrectly.

![vs](https://user-images.githubusercontent.com/13961834/57857277-74b29980-77f7-11e9-9ad0-85355288f585.gif)

**Comment by dasetser** [comment] 2019-05-16 16:32
@dmitriy-shleht It looks like you're reporting the same issue that's tracked in [this feedback](https://developercommunity.visualstudio.com/content/problem/526584/connected-services.html). HemaSK is using an ASP.NE Core project, which shouldn't run into this issue.

**Comment by dasetser** [comment] 2019-05-22 17:45
@HemaSK Were you able to determine which problem you were hitting based on my last reply? This seems like something that's likely fixed in VS2019, so it would be great if you can confirm that fixes it.

**Comment by HemaSK** [comment] 2019-05-23 06:40
> No description provided.

Hi,
For now, I skipped the process. May be later if I have to work on this way, I will come back. For now, we can close this ticket. Thanks for all your time and help
Regards,
Hemalatha. J

**Closed** 2019-05-23 06:41 UTC
Labels: needs more info, tooling
