### ISSUE TITLE
Adding New Connected Service gives error " The filename or extension is too long"

### ISSUE THREAD

**Issue by stephenmorton** [dotnet/wcf#3471] opened 2019-03-18 03:40 UTC
Hi,

When adding a new Connected Service, I keep receiving an error  "The filename or extension is too long"
I have attached 4 images showing the error. I can't figure out where to get more information about the error within VS

Can anyone help determine what this error is relating to or how I can see specifically what the ieeue is. Is there a log I can use (I have included a snaphot of the output, however, it isn't showing much useful info).

Thanks in advance,

![Capture](https://user-images.githubusercontent.com/11910775/54505334-81e41100-498b-11e9-85b2-ea3873979776.PNG)
![Capture2](https://user-images.githubusercontent.com/11910775/54505336-827ca780-498b-11e9-8936-776b889ccfcc.PNG)
![Capture3](https://user-images.githubusercontent.com/11910775/54505337-827ca780-498b-11e9-8dac-7455860798ae.PNG)
![Capture4](https://user-images.githubusercontent.com/11910775/54505338-827ca780-498b-11e9-8dcb-970d9cb8a39f.PNG)

**Comment by stephenmorton** [comment] 2019-03-20 02:20
Hi, Anyone seen this before or have any ideas what could be the problem? I have used the wsdl file elsewhere without issues.

**Comment by Lxiamail** [comment] 2019-03-20 21:55
@stephenmorton This is due to the folder path is too long as the error reported in VS. Please try to reduce the path.

**Comment by stephenmorton** [comment] 2019-03-20 22:00
Hi Lxiamail, I thought the same thing, so I reduced the path already to the file to only c:\Frontierlink2019\ frontierlink.wsdl the same error however.

**Comment by Lxiamail** [comment] 2019-03-20 22:31
@stephenmorton can you share the VS version that you are using?

**Comment by stephenmorton** [comment] 2019-03-20 23:54
VS Community 2017 V 15.9.9
.NET framework 4.7.03190

Microsoft Visual Studio Community 2017 
Version 15.9.9
VisualStudio.15.Release/15.9.9+28307.518
Microsoft .NET Framework
Version 4.7.03190

**Comment by Lxiamail** [comment] 2019-03-21 00:26
@dasetser can you try to repro it?

**Comment by stephenmorton** [comment] 2019-03-21 00:42
Hi Dasetser, sure, I have done it again, with screenshots for you showing all the relevant info.
![Capture7](https://user-images.githubusercontent.com/11910775/54727860-5c931500-4bce-11e9-8280-61a2e67f4aa7.PNG)
![Capture8](https://user-images.githubusercontent.com/11910775/54727861-5c931500-4bce-11e9-85a6-ca0043228b4e.PNG)
![Capture9](https://user-images.githubusercontent.com/11910775/54727862-5d2bab80-4bce-11e9-8521-bfc35a5b8ee4.PNG)

**Comment by dasetser** [comment] 2019-03-21 19:40
@stephenmorton That's odd that this happens even with a short path. The files in the xsd folder don't have exceptionally long names or anything, do they? There should be some logs in a folder at %temp%\WCFConnectedService\(Date and time) with more information. You can look through those to see if there's some hint, or attach them and we can take a look. 

If that doesn't have anything helpful you could run the [dotnet-svcutil](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x) command line tool on this wsdl with --verbosity Debug and the output should tell us where the error is coming from.

**Comment by stephenmorton** [comment] 2019-03-21 22:30
Hi Daniel,

Thanks for your help. I found the logs (thanks for that). I can’t see anything at first glance. I thought, perhaps if it’s OK, it might be better to just zip up and send directly to you. I’m sure a trained eye will make light work of this issue 😊

I had a look in the .wsdl file, there are a few xsd files that have file names around 51 or so characters, but nothing super crazy. I have taken a snapshot of some of the files in the xsd, with the longest name being DSLQueryProgressExtendedLinePerformanceResponse.xsd

Regards,

Stephen G Morton
Total Telco Group Pty Ltd
P 1300 484 511 | D 02 8488 3151 | M 0418 111 068

**Comment by dasetser** [comment] 2019-03-22 17:05
Yes, we'll take a look if you can attach a zip of the folder.

**Comment by stephenmorton** [comment] 2019-03-24 22:52
Hi Daniel,

Pls see attached. I zipped up the error log (thought I attached to my last reply, but apparently not).
I also attached a screenshot showing the longest file name in the wsdl file.

[2019_Mar_21_11_38_17.zip](https://github.com/dotnet/wcf/files/3000958/2019_Mar_21_11_38_17.zip)
![Capture1](https://user-images.githubusercontent.com/11910775/54887119-6aed7380-4ee3-11e9-8471-e8d7604c9cf2.PNG)

**Comment by stephenmorton** [comment] 2019-03-29 01:57
Hi guys, do you think it is because of the file name lengths of some of the.xsd files? What is the file lengths  limit for these?
Steve

**Comment by dasetser** [comment] 2019-04-02 22:44
@stephenmorton None of the individual file names are too long. I'm still investigating exactly what's going on, and I'm thinking the error message may not be entirely correct. Could you try using the latest version of the [dotnet-svcutil](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x) command line tool or Visual Studio 2019 and seeing if you get the same thing? The version of VS you're using is using an older version of dotnet-svcutil and we've changed some of this logic so it may not reproduce on the latest version.

**Comment by stephenmorton** [comment] 2019-04-03 01:53
Hi Daniel, worked a treat.

I upgraded everything, including it VS2019, tried it again and it worked GREAT! So, must have been something with my version. Thanks, that’s awesome!

Regards,

Stephen G Morton
Total Telco Group Pty Ltd
P 1300 484 511 | D 02 8488 3151 | M 0418 111 068

**Comment by dasetser** [comment] 2019-04-03 16:47
Glad it's working with the latest version. I'll close this issue.

**Closed by dasetser** 2019-04-03 16:47 UTC
Labels: tooling
