### ISSUE TITLE
Unable to generate deps.json, it may have been already generated.  You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d <toolname>": C:\Program Files\dotnet\sdk\2.1.503\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj

### ISSUE THREAD

**Issue by karthik33** [dotnet/wcf#3631] opened 2019-05-10 10:39 UTC
Hi ,

I am not able to include service reference using a WSDL file in Visual Studio 2017 (ASP.NET Core) Project.

Below are the Error log
--------------------------

[05/10/2019 13:59:23],24,Importing web service metadata ...
[05/10/2019 13:59:23],17,Number of service endpoints found: 1
[05/10/2019 13:59:23],67,Scaffolding service reference code ...
[05/10/2019 13:59:23],17,Executing command [C:\Users\BD9086\AppData\Local\Temp\WCFConnectedService\2019_May_10_13_59_23\svcutil_starter]
 "dotnet new console --no-restore --force --type project --language C# --output . --name svcutil_starter"
[05/10/2019 13:59:30],67,Executing command [C:\Users\BD9086\AppData\Local\Temp\WCFConnectedService\2019_May_10_13_59_23\svcutil_starter]
 "dotnet restore --ignore-failed-sources"
[05/10/2019 13:59:36],60,Executing command [C:\Users\BD9086\AppData\Local\Temp\WCFConnectedService\2019_May_10_13_59_23\svcutil_starter]
 "dotnet svcutil --additionalprobingpath "C:\Users\BD9086\.nuget\packages" "C:\Users\BD9086\AppData\Local\Temp\WCFConnectedService\2019_May_10_13_59_23\SvcUtilParams.txt""
[05/10/2019 13:59:39],67,Unable to generate deps.json, it may have been already generated.  You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d <toolname>": C:\Program Files\dotnet\sdk\2.1.503\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj
[05/10/2019 13:59:39],67,Done.

**Comment by dasetser** [comment] 2019-05-21 20:20
Closing this issue. Based on your response in issue #3391 it sounds like this is a bug we fixed in VS2019/dotnet-svcutil. If you still experience the same problem in VS2019 let us know and we can investigate further.

**Closed by dasetser** 2019-05-21 20:20 UTC
Labels: tooling

**Comment by glapsvin** [comment] 2019-06-26 14:26
Still have same problem in 2019 Preview 3

**Comment by dasetser** [comment] 2019-06-26 17:42
@glapsvin If you install dotnet-svcutil 1.x and run "dotnet -d svcutil" what output do you get? This unable to generate deps.json message is very general and I've seen it have a few different root causes.

**Comment by karthik33** [comment] 2019-06-29 13:25
Hi ,
Thanks for your reply.
After installing dotnet -d svcutil my issue is resolved. Thanks.


Regards,
Karthik KOMMANDI

**Comment by mujgancihan** [comment] 2020-03-24 09:03
Hi,
I have the same issue, I am using VS2019 and I have already installed svcutil 1.0.4.
When type dotnet -d svcutil I get the error ;





projecttoolscommandresolver: resolving commandspec from 0 Tool Libraries.
projecttoolscommandresolver: failed to resolve commandspec from library.
Microsoft.DotNet.Cli.Utils.CommandUnknownException: Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-svcutil does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
   at Microsoft.DotNet.CommandFactory.CommandFactoryUsingResolver.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

**Comment by ivanalie** [comment] 2020-09-24 09:51
> Hi,
> I have the same issue, I am using VS2019 and I have already installed svcutil 1.0.4.
> When type dotnet -d svcutil I get the error ;
> 
> projecttoolscommandresolver: resolving commandspec from 0 Tool Libraries.
> projecttoolscommandresolver: failed to resolve commandspec from library.
> Microsoft.DotNet.Cli.Utils.CommandUnknownException: Could not execute because the specified command or file was not found.
> Possible reasons for this include:
> 
> * You misspelled a built-in dotnet command.
> * You intended to execute a .NET Core program, but dotnet-svcutil does not exist.
> * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
>   at Microsoft.DotNet.CommandFactory.CommandFactoryUsingResolver.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
>   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
>   at Microsoft.DotNet.Cli.Program.Main(String[] args)

Encounter the same issue after installing VS2019 and svcutil 1.0.4. Any clue how to fix this?
