### ISSUE TITLE
ExpectedExceptionTests.UnknownUrl_Throws_EndpointNotFoundException fails on Windows

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#896] opened 2016-03-09 21:06 UTC
This scenario test fails periodically on Windows with HRESULT 0x80131620 (I/O streaming error):

12:04:42   Starting:    Client.ExpectedExceptions.Tests
12:04:48      ExpectedExceptionTests.UnknownUrl_Throws_EndpointNotFoundException [FAIL]
12:04:48         Assert.Throws() Failure
12:04:48         Expected: typeof(System.ServiceModel.EndpointNotFoundException)
12:04:48         Actual:   typeof(System.ServiceModel.CommunicationException): Received HttpRequestException with unknown error code -2146232800
12:04:48         Full details for HttpRequestException:
12:04:48         System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: The write operation failed, see inner exception. ---> System.Net.Http.WinHttpException: The connection with the server was terminated abnormally
12:04:48            --- End of inner exception stack trace ---
12:04:48            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:04:48            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:04:48            at System.ServiceModel.Channels.BufferedMessageContent.<SerializeToStreamAsync>d__8.MoveNext() in d:\j\workspace\outerloop_win---80ddfca7\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\MessageContent.cs:line 234
12:04:48            --- End of inner exception stack trace ---
12:04:48            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:04:48            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:04:48            at System.Net.Http.WinHttpHandler.<InternalSendRequestBodyAsync>d__126.MoveNext()
12:04:48         --- End of stack trace from previous location where exception was thrown ---
12:04:48            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:04:48            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:04:48            at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
12:04:48         --- End of stack trace from previous location where exception was thrown ---
12:04:48            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:04:48            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:04:48            at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__13.MoveNext() in d:\j\workspace\outerloop_win---80ddfca7\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\HttpChannelFactory.cs:line 938
12:04:48         
12:04:48         Stack Trace:
12:04:48            d:\j\workspace\outerloop_win---80ddfca7\src\System.Private.ServiceModel\tests\Scenarios\Client\ExpectedExceptions\ExpectedExceptionTests.cs(327,0): at ExpectedExceptionTests.<>c__DisplayClass7_0.<UnknownUrl_Throws_EndpointNotFoundException>b__0()
12:04:57   Finished:    Client.ExpectedExceptions.Tests

**Comment by roncain** [comment] 2016-03-14 19:42
Investigation shows it fails sporadically on both Debug and Release OuterLoop runs on Jenkins.  We occasionally see it running locally, so it is difficult to reproduce.

**Comment by zhenlan** [comment] 2016-03-29 21:47
The root cause is an issue in WinHttp layer. However, we can make a change of our code to avoid this issue.

**Comment by shmao** [comment] 2016-04-06 16:30
Changed the title. Closing the issue as it is a duplicate of of #87 .

**Closed by shmao** 2016-04-06 16:30 UTC
Labels: bug
