### ISSUE TITLE
regression in default values for listenBacklog and maxConnections

### ISSUE THREAD

**Issue by benken-parasoft** [dotnet/wcf#4850] opened 2022-06-27 17:57 UTC
**Describe the bug**
In a .NET WCF client/service configuration file, netTcpBinding has various configuration attributes including listenBacklog and maxConnections. If you were to omit these two attributes from the netTcpBinding/binding element then default values should be used which is supposed to be 10 as correctly stated in the docs (not a docs issue):
https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.configuration.nettcpbindingelement.listenbacklog
https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.configuration.nettcpbindingelement.maxconnections

I have been using System.ServiceModel.Configuration API to read settings from arbitrary .NET config files. The ListenBacklog and MaxConnections properties of my NetTcpBindingElement object are now unexpectedly returned as 0 instead of 10.  This is a regression as this did not used to be the case in some earlier version or update of .NET.

I also see the exact same issue with these incorrectly being returned with a default value of 0:
https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.configuration.netnamedpipebindingelement.maxconnections
https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.configuration.connectionorientedtransportelement.maxpendingaccepts
https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.configuration.connectionorientedtransportelement.maxpendingconnections

**To Reproduce**
This regression in behavior is plainly visible with the Microsoft Service Configuration Editor (SvcConfigEditor.exe) tool.

1. Open SvcConfigEditor.exe from "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools" on Windows 10.
2. Click Bindings > New Binding Configuration.. > netTcpBinding > OK
3. Notice that 0 is unexpectedly shown for both ListenBacklog and MaxConnections:
![image](https://user-images.githubusercontent.com/11323121/176005983-6070bd61-ae1a-47c4-8672-41c0131a1c14.png)

**Expected behavior**
The default values should be 10, matching the documentation.  This was the case in some earlier version of .NET 3/4.  On an old Windows Server VM I was able to confirm that the behavior used to match the documentation, where 10 used to be correctly returned as default:
![image](https://user-images.githubusercontent.com/11323121/176006026-d239b646-3044-47ac-b6c4-fe8f8eecaeff.png)

**Screenshots**
(see above)

**Additional context**
The issue was originally reported to me by one of my users.  When I looked closer, I saw Microsoft's own Service Configuration Editor showing the exact same thing, where 0 is now being incorrectly returned as the default value for certain configuration attributes that were not specified on the netTcpBinding/binding element in my .NET client/service config file.

On a side note, a value of 0 is definitely illegal on the Binding object itself. If I were to actually set 0 for either of these properties on a NetTcpBinding object then I get a System.ArgumentOutOfRangeException "The value of this argument must be positive.".

Also refer to the original description I posted here: https://docs.microsoft.com/en-us/answers/questions/899904/nettcpbinding-regression-in-default-values-for-lis.html

**Comment by mconnew** [comment] 2022-06-27 20:45
This is the wrong place to raise an issue with .NET Framework. The about text for this repo says:

> This repo contains the client-oriented WCF libraries that enable applications built on .NET Core to communicate with WCF services.

The first sentence of the readme.md file on the repo home page says:

> This repository contains the .NET Core version of the Windows Communication Foundation client libraries.

Having said that, I'll response and then close the issue.

What you are examining is the configuration object model for WCF, which then gets applied to a binding instance. In this case the class `System.ServiceModel.Configuration.NetTcpBindingElement` is the config OM which then applies its values to the System.ServiceModel.NetTcpBinding binding class. This is the code which applies the config OM listen backlog value to the binding value:
https://github.com/microsoft/referencesource/blob/master/System.ServiceModel/System/ServiceModel/Configuration/NetTcpBindingElement.cs#L165-L168
```c#
            if (this.ListenBacklog != TcpTransportDefaults.ListenBacklogConst)
            {
                nptBinding.ListenBacklog = this.ListenBacklog;                
            }
```
The value of `TcpTransportDefaults.ListenBacklogConst` is 0, so this basically says set the listen backlog on the actual binding if a value other than 0 has been set. The value 0 means use the default. In the NetTcpBindingElement.ListenBacklog definition, it is attributed to say this is the default value:
https://github.com/microsoft/referencesource/blob/fa352bbcac7dd189f66546297afaffc98f6a7d15/System.ServiceModel/System/ServiceModel/Configuration/NetTcpBindingElement.cs#L64-L70
```c#
        [ConfigurationProperty(ConfigurationStrings.ListenBacklog, DefaultValue = TcpTransportDefaults.ListenBacklogConst)]
        [IntegerValidator(MinValue = 0)]
        public int ListenBacklog
        {
            get { return (int)base[ConfigurationStrings.ListenBacklog]; }
            set { base[ConfigurationStrings.ListenBacklog] = value; }
        }
```
That configuration property `DefaultValue = TcpTransportDefaults.ListenBacklogConst` has the effect that if the OM property has this value, exclude it when writing out the XML. So if `NetTcpBindingElement.ListenBacklog` has a value of 0 in the config editor, when any changes get written back to your config file, a value of 0 will mean the `ListenBacklog` attribute won't be written out. This is the correct behavior because 0 means use the default, so we don't want to specify it.  

On the `NetTcpBinding` side, the `ListenBacklog` property is passed through to `TcpTransportBindingElement.ListenBacklog`. If you look at the constructor of `TcpTransportBindingElement`, it sets the default value based on the return value from calling `TcpTransportDefaults.GetListenBacklog()`. The code for that method can be found here:
https://github.com/microsoft/referencesource/blob/fa352bbcac7dd189f66546297afaffc98f6a7d15/System.ServiceModel/System/ServiceModel/Channels/TransportDefaults.cs#L279-L288
```c#
        private const int ListenBacklogPre45 = 10;

        internal static int GetListenBacklog()
        {
            // OSEnvironmentHelper.IsApplicationTargeting45 checks for whether target Fx version is >= 4.5 despite its name
            if (OSEnvironmentHelper.IsApplicationTargeting45)
            {
                return 12 * OSEnvironmentHelper.ProcessorCount;
            }

            return ListenBacklogPre45;
        }
```
The if check here is seeing if your application is targeting .NET 4.5 or later, or if it's still targeting .NET 4.0. This is compatibility code so that existing apps compiled against .NET 4.0 will get the same behavior when running on .NET 4.5, which is to use a value of 10 as the listen backlog. The newer behavior is to scale the listen backlog with the number of CPU cores and is a better behavior to have as the listen backlog should scale with the number of CPU cores.  

The MaxConnections property is similar. I'm not going to connect all the same dots for you as I believe you have enough info to verify that for yourself if you wish. The code for calculating the MaxConnections is here:
https://github.com/microsoft/referencesource/blob/fa352bbcac7dd189f66546297afaffc98f6a7d15/System.ServiceModel/System/ServiceModel/Channels/TransportDefaults.cs#L246-L255
```c#
        internal static int GetMaxPendingConnections()
        {
            // OSEnvironmentHelper.IsApplicationTargeting45 checks for whether target Fx version is >= 4.5 despite its name
            if (OSEnvironmentHelper.IsApplicationTargeting45)
            {
                return 12 * OSEnvironmentHelper.ProcessorCount;
            }

            return MaxPendingConnectionsPre45;
        }
```
The previous value was 10 on .NET 4.0. The `TcpTransportBindingElement` class has a `MaxPendingAccepts` property which also has similar behavior. In this case, pre .NET 4.5 the default value was 1, and for .NET 4.5+ the default value is 2X processor count.  

This isn't a regression as if you were to run an application compiled against .NET 4.0, you would get the exact same behavior as you've always had. When recompiling against the newer framework versions, you get different behavior. But as you are compiling against a newer version, you get the behavior of the newer version.  

I would categorize this as a documentation bug. We're not going to change the behavior of the product to match the previous version as anyone who has compiled their app against .NET 4.5 in the last 10 years would have different (worse) performance. It was also an intentional change. 

I suspect the issue you actual want help with is how do you apply the configuration read from a .config file to the binding object, and you aren't reading from the app.config or web.config file otherwise you could just pass the config name to the binding on construction and have it just work. I think you might be doing things the hard way. You can just call [ApplyConfiguration](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.configuration.standardbindingelement.applyconfiguration?view=netframework-4.8) on the `NetTcpBindingElement` (it's degined on the base class `StandardBindingElment`). You pass your instance of `NetTcpBinding` to the method and it applies all the settings for you.

**Closed by mconnew** 2022-06-27 20:45 UTC

**Comment by benken-parasoft** [comment] 2022-06-27 22:53
Thank you, Matt.  I could not find an answer or explanation anywhere else.  Now, I managed to get the attention of Microsoft's WCF/SOAP guy.  :)


> This is the wrong place to raise an issue with .NET Framework

My apologies.  On the .NET community support forum, I attempted to get an answer for "correct place" among other things but was going nowhere fast.  This looked like the closest place to report something against System.ServiceModel API as opposed to .NET Framework in general.  However, I do wonder where the correct place would be.


> Having said that, I'll response and then close the issue.

I really appreciate you taking the time to respond.


> So if NetTcpBindingElement.ListenBacklog has a value of 0 in the config editor, when any changes get written back to your config file, a value of 0 will mean the ListenBacklog attribute won't be written out. This is the correct behavior because 0 means use the default, so we don't want to specify it.

I understand that if the value is the default then it does not (or at least should not) get written out.  The default used to be 10 whereas in .NET 4.5 the default is now dynamic, based on the number of CPU cores.  Instead of using 10, .NET 4.5 started using 0 to mean "use default" in this specific case where the default is not some fixed number.  In contrast, other configuration properties do have a fixed number or a fixed string as the default value, where I do not have to test for 0 to mean something special.


> This is compatibility code so that existing apps compiled against .NET 4.0 will get the same behavior when running on .NET 4.5, which is to use a value of 10 as the listen backlog. The newer behavior is to scale the listen backlog with the number of CPU cores and is a better behavior to have as the listen backlog should scale with the number of CPU cores.

This is the answer I have been looking for.  I have been trying to find someone who can explain what changed and why, if it was expected or unintentional.  It does look unintentional for at least a couple reasons.  However, I now understand that the change is very intentional based on how WCF code is currently written as you very explicitly point out.


> This isn't a regression as if you were to run an application compiled against .NET 4.0, you would get the exact same behavior as you've always had.

I agree that "exact same behavior" is what should happen.  In reality, backwards compatibility was not completely preserved, at least not for my application.  I had the line of code "binding.ListenBacklog = config.ListenBacklog".  The target is < 4.5.  When running in .NET < 4.5 this assigns a value of 10 to the binding object.  In current .NET 4.8, this it assigns a value of 0 which throws a System.ArgumentOutOfRangeException "The value of this argument must be positive."  I understand that other parts of WCF internals compensate for the change based on compilation target, so other applications are generally not impacted.  My application had a tiny bit of breakage when run in .NET >= 4.5 but fortunately this change had somewhat minimal impact.


> I would categorize this as a documentation bug.

Yes, that's right.  The docs for .NET 4.5 and later incorrectly state that it is 10, not a function of the CPU core count.  In my opinion, stating what 0 means would also be very helpful.  The Microsoft Service Configuration editor also shows a description for the currently selected property but only says "The maximum number of _blah_" without saying what 0 means.  Offhand, I found the issue in at least four or five config properties.

Would it be better for me to file a documentation issue or for you to do this?  It looks like the "correct place" would be the "dotnet-api-docs" repo, right?


> We're not going to change the behavior of the product to match the previous version as anyone who has compiled their app against .NET 4.5 in the last 10 years would have different (worse) performance. It was also an intentional change.

I am not arguing for changing .NET.  The behavior only looked unexpected because of the current .NET 4.8 documentation still describing the original pre-4.5 behavior.  The other thing that made the behavior look unexpected is that 0 is not a legal property value on the binding object itself (throws System.ArgumentOutOfRangeException).  There was no documentation to explain what 0 actually means, why it is legal on the config object but not the binding object.  As you say, this is a documentation issue.


> you aren't reading from the app.config or web.config file otherwise you could just pass the config name to the binding on construction and have it just work

Yes, exactly.  My application has funny requirements.  We load arbitrary .NET config files on-the-fly to accomplish complex messaging and validation scenarios.


> I think you might be doing things the hard way. You can just call ApplyConfiguration on the NetTcpBindingElement

You may be right.  The code in question was originally developed shortly after .NET WCF was first introduced (in 3.0) and has continued to evolve as new functionality has been added to WCF in subsequent releases of .NET.  I see that "ApplyConfiguration" is also not new in that 3.0 is listed in the online docs.  However, I suspect we had some technical reason why we could not use it.  I can not say what that might be at this particular moment.

Anyway, please let me know if it would be better for me or for you to file a docs issue.  I see this affecting the documentation for at least 4 or 5 different binding element properties.
