### ISSUE TITLE
NoBootstrap option and referenced assembly

### ISSUE THREAD

**Issue by PhilPJL** [dotnet/wcf#4308] opened 2020-07-16 09:46 UTC
In order to debug the dotnet-svcutil tool I need to use the -nb option.  This causes an error when referencing a .NET standard 2.0 assembly.

[test.zip](https://github.com/dotnet/wcf/files/4930626/test.zip)

Using the attached files use: dotnet-svcutil.exe Service1.wsdl -v debug  -r SharedDataContracts.dll -nb

This should generate the service reference without error, but we get 

![image](https://user-images.githubusercontent.com/271656/87655783-95a2b180-c750-11ea-8a70-9978441de318.png)

The solution for me was to modify LoadReferencedAssemblies in CommandProcessOptions.cs to load binary references using Assembly.LoadFile.

```   
        private void LoadReferencedAssemblies()
        {
            // we should not load the ServiceModel assemblies as types will clash with the private code types.
            var loadableReferences = this.References.Where(r => !TargetFrameworkHelper.ServiceModelPackages.Any(s => s.Name == r.Name));
            foreach (ProjectDependency reference in loadableReferences)
            {
                // new code
                Assembly assembly = null;

                switch (reference.DependencyType)
                {
                    case ProjectDependencyType.Binary:
                        assembly = Assembly.LoadFile(reference.FullPath);
                        break;
                    case ProjectDependencyType.Package:
                    case ProjectDependencyType.Tool:
                    case ProjectDependencyType.Project:
                        // TODO: should each dependency type be loaded differently?
                        assembly = TypeLoader.LoadAssembly(reference.AssemblyName);
                        break;
                    default:
                    case ProjectDependencyType.Unknown:
                        break;
                }

                // comment out
                //Assembly assembly = TypeLoader.LoadAssembly(reference.AssemblyName);

```

**Comment by imcarolwang** [comment] 2021-02-19 01:50
Bootstrapping is required for type reuse, so `-r SharedDataContracts.dll -nb` doesn't seem to be a supported command option combination to run the tool.

**Comment by PhilPJL** [comment] 2021-02-19 08:52
@imcarolwang 

It's a while since I looked at this but as I mentioned above I was trying to debug the tool in the VS debugger.  I found that in order to do that I had to use -nb which then caused the error shown.  I remedied this with the code change shown.

This allowed me to determine a possible solution to https://github.com/dotnet/wcf/issues/3812 which I raised in 2019 and marked 'priority 1'.

**Comment by imcarolwang** [comment] 2021-02-19 10:42
@PhilPJL The information you provided is helpful and the issue is under investigation, thank you so much for your patience!

**Comment by imcarolwang** [comment] 2021-09-18 08:09
The type loading exception was thrown when calling [LoadReferencedAssemblies()](https://github.com/dotnet/wcf/blob/8e18e27cd563d0bf9f084c671f8e8ce7374eb30d/src/dotnet-svcutil/lib/src/CommandProcessorOptions.cs#L783) which would only be invoked when [RequiresBoostrapping ](https://github.com/dotnet/wcf/blob/8e18e27cd563d0bf9f084c671f8e8ce7374eb30d/src/dotnet-svcutil/lib/src/CommandProcessorOptions.cs#L776)is false. The repro command here specified -nb option which indicates no bootstraper is required but type reuse feature(for the "-r" command option to work) has to be run under Bootstrapper context, it's a feature by design. Closing issue.

**Closed by imcarolwang** 2021-09-18 08:09 UTC
Labels: tooling
