### ISSUE TITLE
Azure Functions project: Can't create new ConnectedService reference when System.Reflection.TypeExtensions nuget package is not added manually to project first

### ISSUE THREAD

**Issue by hansmbakker** [dotnet/wcf#3066] opened 2018-07-27 09:13 UTC
Steps to reproduce:

Create .net core Azure Functions project in Visual Studio 15.8 Preview 4 or 5
Add connected service reference

When VS is generating the code (still in the wizard), it tries to restore nuget packages. There is a conflict between versions of the System.Reflection.TypeExtensions nuget package and the Connected Service reference fails to complete.

The workaround is to manually add System.Reflection.TypeExtensions to your project before running the Connected Service wizard.

**Comment by mlacouture** [comment] 2018-07-31 18:12
Thank you @wind-rider  for reporting this issue and providing a workaround.

**Comment by mlacouture** [comment] 2018-08-03 01:33
Another workaround is to disable System.Reflection.TypeExtensions from the Data Types Options page in the WCF Web Service Reference wizard.  In order to make it simple for selecting all but one referenced assembly after selecting the 'Reuse types in specified referenced assemblies' check box, Tab into the list box, type Ctrl+A (select all) followed by a Space (check all), now find and uncheck the assembly.

Finally, if you don't care about type reuse you can just uncheck the 'Reuse types in referenced assemblies' options.

Hope this helps,

**Comment by hansmbakker** [comment] 2018-08-13 14:38
(changed my GitHub handle) Thank you for your feedback

**Comment by dasetser** [comment] 2019-04-26 17:41
I'm unable to reproduce this issue on VS2019. I believe one of the changes we made in recent versions in this area fixed this, so closing the issue.

**Closed by dasetser** 2019-04-26 17:41 UTC
Labels: bug, tooling
