### ISSUE TITLE
WCF Web Service Reference (dotnet-svcutil) doesn't re-use assemblies

### ISSUE THREAD

**Issue by petwal11** [dotnet/wcf#3253] opened 2018-11-15 13:48 UTC
I have an existing assembly (NET Framework 4) with types matching a wcf service. I have tested with regular svcutil.exe and this does not reproduce any of the types (in the assembly).

I copy the code to a new .NET Core 2.0 project, compile without any issues and package output as nuget (and push the package to local repository). I call dotnet svcutil http://domain.com/service.svc?wsdl --reference "{MyAssembly,1.0.0}"

All the types are duplicated in the output. The util is supposed to check if the combination of Namespace+Name in the DataContractAttribute of any class defined in the assembly is a match for any class required by the service (if so then the class defintion should not be duplicated in the proxy, it should be referenced from the assembly). The result is the same if I choose Web Service Reference within Visual studio.

[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.myorganisation.com/base/2011/10/sharedcontract", Name = "MyObject", )]
public partial class MyObject : object
{}

This is probably the same issue as 2929. To reproduce: Generate a proxy for any WCF service (that was created using regular .NET) using dotnet svcutil for NET Core. Copy any of the generated classes to a newly created assembly (having a different .NET namespace), compile as NET 2.0 and push the package to local repository. Generate the proxy again using dotnet svcutil and verify that the class in the assembly is not duplicated.

It could be that there is something special with my service or any of my classes is causing an error (I have a lot of experience using SvcUtil, but I am rather new to NET core). But no error or warning is returned from the tool. If a referenced assembly is not found, there must be a warning in the output (or error). If a match is found (Namespace+Name), but the class can not be used, there must be a warning in the output (or error).

**Comment by petwal11** [comment] 2018-11-20 13:37
Adding an example

SharedContract assembly with this content is compiled using .NET Core 2.0:

```
using System.Runtime.Serialization;

namespace SharedContractNetCore21
{
    [DataContract(Name = "MyRequest", Namespace = "http://www.myorganisation.com/2018/11/sharedcontract")]
    public class MyRequest
    {
        [DataMember]
        public string Data { get; set; }
    }

    [DataContract(Name = "MyResponse", Namespace = "http://www.myorganisation.com/2018/11/sharedcontract")]
    public class MyResponse
    {
        [DataMember]
        public string Data { get; set; }
    }
}

```

When I generate a proxy for the service with a reference to this assembly, the types are replicated:

```
namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyRequest", Namespace="http://www.myorganisation.com/2018/11/sharedcontract")]
    public partial class MyRequest : object
    {
        
        private string DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyResponse", Namespace="http://www.myorganisation.com/2018/11/sharedcontract")]
    public partial class MyResponse : object
    {
        
        private string DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.myorganisation.com/wcfservice1/2018/11/", ConfigurationName="ServiceReference1.WcfService1")]
    public interface WcfService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.myorganisation.com/2018/11/getdata", ReplyAction="http://www.myorganisation.com/2018/11/getdataresponse")]
        System.Threading.Tasks.Task<ServiceReference1.MyResponse> GetDataAsync(ServiceReference1.MyRequest request);
    }
}
```
The expected result (according to regular svcutil) is this:

```
namespace ServiceReference1
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.myorganisation.com/wcfservice1/2018/11/", ConfigurationName="ServiceReference1.WcfService1")]
    public interface WcfService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.myorganisation.com/2018/11/getdata", ReplyAction="http://www.myorganisation.com/2018/11/getdataresponse")]
        System.Threading.Tasks.Task<SharedContractNetCore21.MyResponse> GetDataAsync(SharedContractNetCore21.MyRequest request);
    }
}
```
(Some not relevant details have been left out to reduce size)

**Comment by dasetser** [comment] 2018-11-20 17:03
Thanks for reporting this and providing a sample. I'll look into it to see if I can figure out why the type isn't being reused.

**Comment by petwal11** [comment] 2018-11-21 10:23
Hi @dasetser ! If you have any trouble reproducing, let me know where to send/post the full souce of the service. There isn't much to it (a .NET 4 Wcf service with one method to receive MyRequest and echo data as MyResponse). We are in the process of porting a Silverlight application to .NET core and being unable to reuse the contract causes major issues. It would be great to have this solved, either as a bugfix or tutorial (if there is some specific trick to getting this to work that I have not yet found).

**Comment by JStepien90** [comment] 2019-01-10 19:11
I can confirm the same issue. Even more with the .NET Core 2.2 I have the problem with genereting types at all when I want to resuse some library. With the older sdk types were duplicated.

**Comment by PhilPJL** [comment] 2019-01-12 14:42
Same issue for me, all types are duplicated.  I'll be unable to start migrating to .NET Core until this is fixed.

**Comment by jjanuszkiewicz** [comment] 2019-02-05 23:13
Same for me, types are not reused even if they have matching `DataContractAttribute`.

**Comment by dasetser** [comment] 2019-02-22 19:57
We found a bug in our logic when selecting types to reuse that was causing this scenario not to work. We've included the fix for it in dotnet-svcutil 2.0. Closing this issue, but feel free to comment if you still have trouble with types not being reused in the latest version.

**Closed by dasetser** 2019-02-22 19:57 UTC
Labels: Community, tooling

**Comment by jjanuszkiewicz** [comment] 2019-02-24 03:15
@dasetser That's great to hear, I'll give it a try. Do you know if VS2019 will use the 2.0 version when generating the service reference via GUI?

**Comment by dasetser** [comment] 2019-02-25 18:17
VS2019 uses a preview version of dotnet-svcuil 2.0 that does not include this bug fix. We'll try to get this updated when we can, but it's likely to be in an update after GA.

**Comment by davidglassborow** [comment] 2019-02-27 17:52
@dasetser I'm having some issues, and want to debug what is going on, but can't find the source in this repository ?  ( I can see the dotnet-svcutil.xmlserializer src )

**Comment by dasetser** [comment] 2019-02-27 18:39
@davidglassborow The dotnet-svcutil tool is not open source. Can you create a simple project that we can reproduce the problem internally with?

**Comment by davidglassborow** [comment] 2019-02-28 15:14
Trouble is the WSDL documents I'm having problems with are under NDA from a third party.  Is there any likely hood of it being open sourced at some point ?  Or any way I can turn on more robust logging ?

**Comment by dasetser** [comment] 2019-02-28 18:48
@davidglassborow We do not have any plans to open source it at this time. Are you having trouble getting the tool to reuse types, similar to the problem described in this issue? Can you provide more information about the types? The bug we fixed for this was in how we detected that the type was serializable (we weren't checking for the DataContractAttribute correctly). If you can tell me what attributes are on the type and what types the members are that may help us look for similar issues.

You can run the tool with increased verbosity (`dotnet-svcutil -v Debug wsdl.wsdl`) to get more information from it.

**Comment by davidglassborow** [comment] 2019-03-01 17:57
Not sure what the problem is at this stage, thanks for the info on debugging.
Out of interest, given core and dotnet/wcf are all open source, whats the thinking in this tool not being ?

**Comment by dasetser** [comment] 2019-03-04 18:21
@davidglassborow Please open a new issue if you need further help with your problem, as it sounds like it's not related to this issue so we should track it separately.

As far as open sourcing the tool, we have issue #3191 open to consider it doing it at some point. It's something we've thought about doing but it has been a lower priority than other work.
