### ISSUE TITLE
TCP_ServiceCertFailedCustomValidate_Throw_Exception fails in NET Native

### ISSUE THREAD

**Issue by roncain** [dotnet/wcf#983] opened 2016-04-06 16:50 UTC
The nightly "N from K" run in TFS shows this new test failure.  I have not yet confirmed whether it happens when run locally against NET Native.

```
--------------------------------
Running Test: ExpectedExceptionTests.TCP_ServiceCertFailedCustomValidate_Throw_Exception
Assert.True:Expected 'System.Exception' to be thrown, however 'System.PlatformNotSupportedException' was thrown.
Xunit.AssertTestException: Assert.True: Expected 'System.Exception' to be thrown, however 'System.PlatformNotSupportedException' was thrown.
   at Xunit.Assert.HandleFail(String assertionName, String message) in E:\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Assertion.cs:line 605
   at Xunit.Assert.Throws(Action action) in E:\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Assertion.cs:line 76
   at ExpectedExceptionTests.TCP_ServiceCertFailedCustomValidate_Throw_Exception(Exception exception) in E:\ProjectK\src\NDP\FxCore\WcfOpen\src\System.Private.ServiceModel\tests\Scenarios\Client\ExpectedExceptions\ExpectedExceptionTests.cs:line 504
   at EntryPointMain.<>c.
b__0_12() in E:\ProjectK\src\QA\ToF\PN\amd64\rel\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Client\ExpectedExceptions\Client.ExpectedExceptions.Tests.main.cs:line 25
   at CoreFXTestLibrary.Internal.Runner.RunTestMethod$catch$0() in E:\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
---- Test FAILED ---------------
```

**Comment by iamjasonp** [comment] 2016-04-08 10:08
Confirmed to be happening on CoreCLR official runs as well, but not local box

**Comment by roncain** [comment] 2016-04-11 12:57
@iamjasonp -- did the CoreCLR failure have the same stack trace?  If I run this test without ToF under VS (not elevated), I get the following.  I wonder if we have a CoreCLR run running non-elevated.
```
Starting:    Client.ExpectedExceptions.Tests
   ExpectedExceptionTests.TCP_ServiceCertFailedCustomValidate_Throw_Exception [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.Exception)
      Actual:   typeof(Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException): Access is denied
      Stack Trace:
            at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags)
            at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
```

**Comment by zhenlan** [comment] 2016-04-12 21:22
May related to #959 

@StephenBonikowsky will look into further what happed in the test for the issue @roncain reported.

We will need more clarification from @iamjasonp to understand better the issue @iamjasonp reported.

**Comment by iamjasonp** [comment] 2016-04-13 01:10
Hmm, @roncain your experience is different from mine. When I ran from CoreCLR, I got some odd (somewhat similar) error, but not the "Access Denied" error. 

If it's Access Denied, it puts my understanding of the issue firmly into the "someone ran tests earlier on *nix sudo-ed and now we are trying to run it as a normal user" causing the access denied.

**Comment by roncain** [comment] 2016-04-13 12:08
@iamjasonp -- my access denied occurred on Windows running our GitHub tests from VS (non-elevated). Just running OuterLoops on Windows from a non-elevated CMD windows will repro this failure (and many others).  That part may be as-designed, and if so, we need to close on the [ConditionalFact] conditions to apply to this test and others like it.

**Comment by iamjasonp** [comment] 2016-04-13 16:09
Hm, I need to take a further look at this. I wonder if permissions around accessing the certificate stores have been tightened recently; I know there was some work in corefx around access.

**Comment by iamjasonp** [comment] 2016-04-13 16:22
@StephenBonikowsky - Want to assign to me so it's on my radar, or will you continue to look?

**Comment by StephenBonikowsky** [comment] 2016-04-13 16:29
I haven't started yet, might be a day or two before I have a chance, need to finish syncing the build scripts first. So if you will look into it in the next couple of days go ahead and take it otherwise leave it and I'll get to it.

**Comment by StephenBonikowsky** [comment] 2016-04-18 18:05
It is still failing with the call stack as originally reported by Ron.
Assigning to @iamjasonp to check on access changes to certificate stores.
Pending his investigation need to determine if this test needs to be skipped on NET Native runs.

**Comment by StephenBonikowsky** [comment] 2016-06-02 23:27
UPDATE
Test case is now failing in NetNative because the test is expecting the wrong exception...
Assert.True:Expected 'System.Exception' to be thrown, however 'System.ServiceModel.Security.SecurityNegotiationException' was thrown.

Need to investigate why we are getting two different exceptions on NetNative versus NetCore.

**Comment by iamjasonp** [comment] 2016-06-04 03:35
Thanks @StephenBonikowsky for the investigation!

**Comment by roncain** [comment] 2016-06-06 14:14
Thanks @StephenBonikowsky .Are we actually getting a different exception? Do we get a different exeption running "K on K?"  It might be that ToF's xunit is being too picky about an exact type match in Assert.Throws.  I'd make sure we are using exactly the exception we expect in Assert.Throws and see if we see a difference between "N on K" vs "K on K".

**Comment by roncain** [comment] 2016-06-20 16:40
Note: I don't know what is happening in NET Native yet, but in normal run direct from GitHub enlistment, I see:
 - The custom validation logic is called
 - The custom validator throws a vanilla Exception (by design)
 - The original Exception thrown by the custom validator is thrown all the way back to the client code making the call via the proxy (no intermediate catch or interpretation of the exception)

 When it is called, the stack trace is:
```
>	client.expectedexceptions.tests.dll!MyCertificateValidator.Validate(System.Security.Cryptography.X509Certificates.X509Certificate2 certificate) Line 385	C#
 	system.private.servicemodel.dll!System.IdentityModel.Selectors.X509SecurityTokenAuthenticator.ValidateTokenCore(System.IdentityModel.Tokens.SecurityToken token) Line 62	C#
 	system.private.servicemodel.dll!System.IdentityModel.Selectors.SecurityTokenAuthenticator.ValidateToken(System.IdentityModel.Tokens.SecurityToken token) Line 49	C#
 	system.private.servicemodel.dll!System.ServiceModel.Channels.SslStreamSecurityUpgradeInitiator.ValidateRemoteCertificate(object sender, System.Security.Cryptography.X509Certificates.X509Certificate certificate, System.Security.Cryptography.X509Certificates.X509Chain chain, System.Net.Security.SslPolicyErrors sslPolicyErrors) Line 686	C#
 	system.net.security.dll!System.Net.Security.SecureChannel.VerifyRemoteCertificate(System.Net.Security.RemoteCertValidationCallback remoteCertValidationCallback)	Unknown
 	system.net.security.dll!System.Net.Security.SslState.CompleteHandshake()	Unknown
 	system.net.security.dll!System.Net.Security.SslState.CheckCompletionBeforeNextReceive(System.Net.Security.ProtocolToken message, System.Net.AsyncProtocolRequest asyncRequest)	Unknown
 	system.net.security.dll!System.Net.Security.SslState.StartSendBlob(byte[] incoming, int count, System.Net.AsyncProtocolRequest asyncRequest)	Unknown
 	system.net.security.dll!System.Net.Security.SslState.ProcessReceivedBlob(byte[] buffer, int count, System.Net.AsyncProtocolRequest asyncRequest)	Unknown
 	system.net.security.dll!System.Net.Security.SslState.ReadFrameCallback(System.Net.AsyncProtocolRequest asyncRequest)	Unknown
 	system.net.security.dll!System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(int bytes)	Unknown
 	system.net.security.dll!System.Net.FixedSizeReader.ReadCallback(System.IAsyncResult transportResult)	Unknown
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()	Unknown
 	System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Private.CoreLib.ni.dll!System.Threading.Tasks.AwaitTaskContinuation.RunCallback(System.Threading.ContextCallback callback, object state, ref System.Threading.Tasks.Task currentTask)	Unknown
 	System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task<int>.TrySetResult(int result)	Unknown
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<int>.SetResult(int result)	Unknown
 	system.private.servicemodel.dll!System.ServiceModel.Channels.ConnectionStream.ReadAsync(byte[] buffer, int offset, int count, System.Threading.CancellationToken cancellationToken) Line 400	C#
 	[Resuming Async Method]	
 	System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.RunWithDefaultContext()	Unknown
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0()	Unknown
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()	Unknown
 	System.Private.CoreLib.ni.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)	Unknown
 	System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task<int>.TrySetResult(int result)	Unknown
 	System.Private.CoreLib.ni.dll!System.Threading.Tasks.TaskCompletionSource<int>.TrySetResult(int result)	Unknown
 	system.private.servicemodel.dll!System.ServiceModel.Channels.ConnectionStream.OnReadComplete(object state) Line 423	C#
 	system.private.servicemodel.dll!System.ServiceModel.Channels.SocketConnection.FinishRead() Line 389	C#
 	system.private.servicemodel.dll!System.ServiceModel.Channels.CoreClrSocketConnection.OnReceiveAsync(object sender, System.Net.Sockets.SocketAsyncEventArgs eventArgs) Line 709	C#
 	system.private.servicemodel.dll!System.ServiceModel.Channels.CoreClrSocketConnection.OnReceiveAsyncCompleted(object sender, System.Net.Sockets.SocketAsyncEventArgs e) Line 106	C#
 	System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	system.net.sockets.dll!System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(System.Net.Sockets.SocketError socketError, int bytesTransferred, System.Net.Sockets.SocketFlags flags)	Unknown
 	system.net.sockets.dll!System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* nativeOverlapped)	Unknown
 	System.Private.CoreLib.ni.dll!System.Threading._IOCompletionCallback.PerformIOCompletionCallback(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* pOVERLAP)	Unknown

```

**Closed** 2016-06-29 18:42 UTC
Labels: 2 - In Progress, test bug, TOF, UWP
