### ISSUE TITLE
Error while trying to add wcf reference in VS 2019

### ISSUE THREAD

**Issue by vese** [dotnet/wcf#4713] opened 2021-09-17 09:47 UTC
When I launch the Add Connected Services option in C# project, and try to add a SOAP Web Service reference using the "Microsoft WCF Web Service Reference Provider", instead of showing the dialog to add the Web Service reference, it shows an alert message with the following error:

The connected services component 'Microsoft WCF Web Service Reference Provider' failed: The project reference specification 'System.ServiceModel' does not have a file path.

Visual Studio 2019 16.11.3

May be connected https://github.com/dotnet/wcf/issues/3648

![image](https://user-images.githubusercontent.com/17708516/133761918-618e25f0-2b05-4a13-b42d-3618eafca166.png)

**Comment by mpaine-act** [comment] 2021-09-20 20:19
I am seeing this as well.   Using dotnet cli, I get something similar:

PS P:\> dotnet svcutil https://some.url.here/WarehouseService?WSDL
Microsoft (R) WCF Service Model Proxy Generation Tool for .Net Core platform
[Microsoft.Tools.ServiceModel.Svcutil, Version 2.0.3-preview3.21351.2]
Copyright (c) Microsoft Corporation.  All rights reserved.

This tool collects information about how it is used in order to improve the tool. This functionality can be disabled by setting the environment variable "DOTNET_SVCUTIL_TELEMETRY_OPTOUT" to 1.

Error: The project reference specification 'System.ServiceModel' does not have a file path.

If you would like more help, type "dotnet-svcutil -h"

**Comment by imcarolwang** [comment] 2021-09-30 06:41
@vese Thanks for raising the issue. Base on the error message looks like the tool detect the project has binary reference to System.ServiceModel.dll with no path specified. For a .NET Core or .NET Standard project, if you want to reference WCF product  we expect you use PackageReference such as System.ServiceModel.Http instead of directly referencing System.ServiceModel.dll.  If it's not the case that you were referencing System.Servicemodel.dll in the working .csproj file, could you please share more information about the project? Thank you.

**Comment by vese** [comment] 2021-09-30 09:56
@imcarolwang 
Project has these references:
```
    <PackageReference Include="System.ServiceModel.Http" Version="4.8.1" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="4.8.1" />
```
Also it has this part
```
  <ItemGroup>
    <Reference Include="System.ServiceModel">
      <Private>false</Private>
    </Reference>
  </ItemGroup>
```
Removing this part helped with issue. It was generated when I added wcf reference in older version of vs (in February)
Thanks for answer

**Comment by desJunta** [comment] 2021-11-03 18:02
```
Remove this, 
  <ItemGroup>
    <Reference Include="System.ServiceModel">
      <Private>false</Private>
    </Reference>
  </ItemGroup>
```
works for me. Thanks

**Comment by carios23** [comment] 2021-11-17 18:38
> @imcarolwang Project has these references:
> 
> ```
>     <PackageReference Include="System.ServiceModel.Http" Version="4.8.1" />
>     <PackageReference Include="System.ServiceModel.Primitives" Version="4.8.1" />
> ```
> 
> Also it has this part
> 
> ```
>   <ItemGroup>
>     <Reference Include="System.ServiceModel">
>       <Private>false</Private>
>     </Reference>
>   </ItemGroup>
> ```
> 
> Removing this part helped with issue. It was generated when I added wcf reference in older version of vs (in February) Thanks for answer

Had this issue with Visual Studio 2022, this helped. Thanks

**Comment by imcarolwang** [comment] 2021-11-18 02:18
Update: fix of the issue would be available in the upcoming Visual Studio 2022 release.

**Comment by tomexou** [comment] 2021-12-01 03:26
> ```
> Remove this, 
>   <ItemGroup>
>     <Reference Include="System.ServiceModel">
>       <Private>false</Private>
>     </Reference>
>   </ItemGroup>
> ```
> 
> works for me. Thanks

You saved my poor life. XD

**Comment by mhl-itm-bhg** [comment] 2022-01-31 07:20
I'm still experiencing this on Visual Studio 2022 Version 17.0.5 even though my project file contains no references to `System.ServiceModel`. Any ideas for alternative fixes?

**Comment by PrakashPaul** [comment] 2022-03-11 17:16
remove <Reference Include="System.ServiceModel"/> is now not throwing any exception.  
though I am not able to update or add service...
Edit> able to discover the contracts and methods, but during finish it is not updating or generating and new code/references.
New> able to discover the contracts and methods, but during finish it is not able to find any method... some zero index exception.
project migrated from core to .net 5
tried with visual studio version 2019 and 2016
no success..

**Comment by HongGit** [comment] 2022-04-13 02:22
@imcarolwang can you please follow up on this?

**Comment by imcarolwang** [comment] 2022-04-15 02:56
Closing as a fix of this issue has been released in the most recent version of VS2019 and VS2022. Feel free to re-activate if this is still an issue.

**Closed by imcarolwang** 2022-04-15 02:56 UTC
Labels: tooling

**Comment by vvenkataratnam** [comment] 2022-04-15 08:52
Hi, I am using VS 2022 (17.1.4)  with.NET Core 6.0 and still facing this issue

![image](https://user-images.githubusercontent.com/57880936/163549284-7df4109a-c815-4a82-948a-26fb89d56f5c.png)

**Comment by imcarolwang** [comment] 2022-04-15 09:32
Hi @vvenkataratnam, the original problem described in this issue is about error `The project reference specification 'System.ServiceModel' does not have a file path.` and it has been resolved in the most recent VS release. The error you mentioned appears to be caused by different reason. Could you open a new issue for your problem? If you got a simplified repro project or the repro service/wsdl information, that will help with further investigation. Thank you!

**Comment by vvenkataratnam** [comment] 2022-04-17 04:12
Thanks @imcarolwang for the reply. I have created a new issue
https://github.com/dotnet/wcf/issues/4811

**Comment by ricardoMondardo** [comment] 2022-07-25 16:18
> ```
> Remove this, 
>   <ItemGroup>
>     <Reference Include="System.ServiceModel">
>       <Private>false</Private>
>     </Reference>
>   </ItemGroup>
> ```
> 
> works for me. Thanks

**Comment by VanLance** [comment] 2024-02-14 11:00
I'm getting the same issue as OP when attempting to add system reference wpf project.
"microsoft wcf web service reference provider failed project reference specification 'system.runtime' does not have a file path.
I have visual 22
after reading this thread i found this section:
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Runtime" />
    <Reference Include="System.Data" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.ServiceModel" /> <-------------- Attempting removing this line
    <Reference Include="System.Xml" />
    <Reference Include="System.Xml.Linq" />
  </ItemGroup>
  
  To no avail

**Comment by peteringemann** [comment] 2024-05-21 11:19
I get this error when having a C# project trying to create a connection to a WCF while having a project link to a VB-project.
To fix this I would have to either remove the project link to my VB-project OR add the reference directly to the VB-dll-file instead of the project reference (that will create a link to the vbproj-file). Seems like C# doesn't like it when the project link is a vbproj.

**Comment by antoniochavez1** [comment] 2025-04-14 15:58
> I get this error when having a C# project trying to create a connection to a WCF while having a project link to a VB-project. To fix this I would have to either remove the project link to my VB-project (temp while creating the WCF-connex) OR add the reference directly to the VB-dll-file instead of the project reference (that will create a link to the vbproj-file). Seems like C# doesn't like it when the project link is a vbproj.

That was the problem for me. I have a React project with .NET backend, y had to temporally delete the link between projects to add the WCF connection, and then re add the link again in .csproj file
