### ISSUE TITLE
Need for WCF service for .NET Core 2.0 Projects

### ISSUE THREAD

**Issue by wsnell** [dotnet/wcf#2403] opened 2017-11-20 23:26 UTC
Need for WCF service for .NET Core 2.0 Projects (now we only have support for clients).
Today I am able to create a WCF service with the full .NET Framework (4.6), but I want to move all of my service stuff to Linux or Windows as needed so .NET Core would be awesome.

Please add the full WCF service support ASAP.
Thanks
-Wes

**Comment by zhenlan** [comment] 2017-11-21 07:19
@wsnell please share your feedback on #1200.

Duplicate of #1200

**Closed by zhenlan** 2017-11-21 07:19 UTC

**Comment by shamusfuller** [comment] 2017-11-21 08:10
they can't! Core is not .NET!
