### ISSUE TITLE
visual studio code f12 can't use

### ISSUE THREAD

**Issue by yasewang987** [dotnet/wcf#3586] opened 2019-04-28 08:14 UTC
system: linux mint
visual studio code version: 1.33.1
dotnet version: 2.2.203

step1: dotnet new webapi -n test --no-https
step2: use visual studio code open project, F12 useful
step3: dotnet-svcutil http://1.2.3.4/test.svc
step4: dotnet restore
step5: close visual studio code && reopen project, F12 unuseful

**Comment by yasewang987** [comment] 2019-04-28 08:20
system: linux mint
visual studio code version: 1.33.1
dotnet version: 2.2.203

step1: dotnet new webapi -n test --no-https
step2: use visual studio code open project, F12 useful
step3:  dotnet-svcutil http://1.2.3.4/test.svc
step4: dotnet restore
step5: close visual studio code && reopen project, F12 unuseful

**Comment by Lxiamail** [comment] 2019-05-01 21:49
@yasewang987 Can you check if OmniSharp emit any error? If it can't build, F12 won't work. In that case, please share generated code, or share the WSDL file? The other thing to try is that after Step4, can you run "dotnet build" outside VS Code.

**Comment by yasewang987** [comment] 2019-05-02 00:19
@Lxiamail OmniSharp is OK,after Step4 "dotnet build" also OK
`Microsoft (R) Build Engine version 16.0.450+ga8dc7f1d34 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 36.47 ms for /home/xxx/work/cc/microservices/TC.PayService/TC.PayService.csproj.
  TC.PayService -> /home/xxx/work/cc/microservices/TC.PayService/bin/Debug/netcoreapp2.2/TC.PayService.dll
Build succeeded.
    0 Warning(s)
    0 Error(s)
Time Elapsed 00:00:02.51`
All functions are OK,just 【F12】 can't goto define
Reference.cs Code
`//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ServiceReference
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ISZInterface")]
    public interface ISZInterface
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISZInterface/DoWork", ReplyAction="http://tempuri.org/ISZInterface/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
       ........
  }
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public interface ISZInterfaceChannel : ServiceReference.ISZInterface, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public partial class SZInterfaceClient : System.ServiceModel.ClientBase<ServiceReference.ISZInterface>, ServiceReference.ISZInterface
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SZInterfaceClient() : 
                base(SZInterfaceClient.GetDefaultBinding(), SZInterfaceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISZInterface.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
........
}
`

**Comment by dasetser** [comment] 2019-05-02 17:42
@yasewang987 Do you have a .vscode folder with a valid launch.json? If I do your repro steps (even without steps 3 and 4) then F12 doesn't work for me after reopening the folder, but shortly after I get a prompt saying "Required assets to build and debug are missing from <folder name>. Add them?" If I click yes it generates a .vscode folder with a launch.json and then F12 works as expected.

**Comment by yasewang987** [comment] 2019-05-03 03:05
@dasetser I have the launch.json, it added before use dotnet-svcutil
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/bin/Debug/netcoreapp2.2/TC.PayService.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false,
            "launchBrowser": {
                "enabled": true
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceFolder}/Views"
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ]
}`
my other projects not use dotnet-svcutil are all ok.

Test:
I delete the launch.json file want to rebuilder the debug config, the launch.json like that:
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "WARNING01": "*********************************************************************************",
            "WARNING02": "The C# extension was unable to automatically to decode projects in the current",
            "WARNING03": "workspace to create a runnable lanch.json file. A template launch.json file has",
            "WARNING04": "been created as a placeholder.",
            "WARNING05": "",
            "WARNING06": "If OmniSharp is currently unable to load your project, you can attempt to resolve",
            "WARNING07": "this by restoring any missing project dependencies (example: run 'dotnet restore')",
            "WARNING08": "and by fixing any reported errors from building the projects in your workspace.",
            "WARNING09": "If this allows OmniSharp to now load your project then --",
            "WARNING10": "  * Delete this file",
            "WARNING11": "  * Open the Visual Studio Code command palette (View->Command Palette)",
            "WARNING12": "  * run the command: '.NET: Generate Assets for Build and Debug'.",
            "WARNING13": "",
            "WARNING14": "If your project requires a more complex launch configuration, you may wish to delete",
            "WARNING15": "this configuration and pick a different template using the 'Add Configuration...'",
            "WARNING16": "button at the bottom of this file.",
            "WARNING17": "*********************************************************************************",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/bin/Debug/<insert-target-framework-here>/<insert-project-name-here>.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "stopAtEntry": false
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ]
}`

**Comment by dasetser** [comment] 2019-05-03 17:12
@yasewang987 This doesn't sound like a dotnet-svcutil bug. The tool just creates a Service Reference folder with a .cs and .json file in it, and adds some references to the csproj file. These are all valid actions to do on a project, and If the project still builds it doesn't sound like we generated anything invalid.

I would suggest following up on the VS Code Github for this issue. They would have a better idea about how to determine the root cause of this problem. If it turns out dotnet-svcutil is doing something incompatible with VSCode let us know and we can investigate further. Since it looks like it's generating everything as it should I'm closing this issue for now.

**Closed by dasetser** 2019-05-03 17:12 UTC
Labels: tooling

**Comment by yasewang987** [comment] 2019-05-05 06:21
@dasetser  ok,thank you!
