### ISSUE TITLE
Not able to consume a WCF service with CustomBinding endpoint with messageversion as Soap12

### ISSUE THREAD

**Issue by ranjitkrishnan** [dotnet/wcf#2711] opened 2018-03-23 21:08 UTC
I have to consumer a WCF service from my Core2.0 API. The WCF service has custombiding with messageVersion as Soap12.

Please find the wcf service binding configuration.

```xml   
<customBinding>
        <binding closeTimeout="00:10:00" openTimeout="00:10:00" sendTimeout="00:10:00">
          <textMessageEncoding  messageVersion ="Soap12">
            <readerQuotas maxDepth="2147483647" maxStringContentLength="2147483647" maxArrayLength="2147483647" maxBytesPerRead="2147483647" maxNameTableCharCount="2147483647" />
          </textMessageEncoding>
          <httpTransport maxReceivedMessageSize="2147483647" maxBufferSize="2147483647" useDefaultWebProxy="true" transferMode="Buffered" />
        </binding>
      </customBinding>
```
I am using System.ServiceModel.Primitives to create the CustomBinding from my .NET Core Code.

Please find the code below

```C#
           
            var binding = new CustomBinding();
TextMessageEncodingBindingElement textBindingElement = new TextMessageEncodingBindingElement
            {
                MessageVersion = MessageVersion.CreateVersion(EnvelopeVersion.Soap12, AddressingVersion.None),
                WriteEncoding = System.Text.Encoding.UTF8,
                ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max
            };

            binding.Elements.Add(textBindingElement);

            HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement
            {
                AllowCookies = false,
                MaxBufferSize = int.MaxValue,
                MaxReceivedMessageSize = int.MaxValue,
                TransferMode= TransferMode.Buffered
            };
            binding.Elements.Add(httpBindingElement);
```
I am getting the below error from this call.

>ActionNotSupportedException: The message with Action &#x27;&#x27; cannot be processed at the receiver, due to a ContractFilter mismatch at the EndpointDispatcher. This may be because of either a contract mismatch (mismatched Actions between sender and receiver) or a binding/security mismatch between the sender and the receiver.  Check that sender and receiver have the same contract and the same binding (including security requirements, e.g. Message, Transport, None)

This will work for any other message version like Soap11, Soap12WSAddressing10 which is directly present in MessageVersion class. It is not working when i am creating messageversion using CreateVersion method as there is no in-built support for Soap12 as it used to be with the framewrok dll

**Comment by Looooooka** [comment] 2018-04-04 20:30
I have the same problem. Soap11 works Soap12 throws this exception. In fact I can't even see the request going out in fiddler

**Comment by mconnew** [comment] 2018-04-23 22:09
I did some investigation and I can understand why Soap11WSAddressing10 doesn't work. The code for Soap11 [here](https://referencesource.microsoft.com/#System.ServiceModel/System/ServiceModel/Channels/HttpChannelHelpers.cs,2648) is missing on core. The issue with just Soap12 I'm not able to see what the issue is after a few minutes of digging through the code and I'll need to do more investigation.

**Comment by Lxiamail** [comment] 2018-05-11 18:35
@mconnew Need open test issue for write tests for Soap11WSAddressing10 and  Soap12, include details needed.

**Comment by Lxiamail** [comment] 2018-08-03 18:58
@StephenBonikowsky Can we have test for this?

**Comment by StephenBonikowsky** [comment] 2018-09-18 17:40
I have added tests that reproduce the error, #3132
I have updated the issue that had been opened to track adding the tests with the details, #2864

**Comment by swiftarrow101** [comment] 2018-10-23 14:48
Hello,
I am seeing the same issue in .Net Core 2.0
Has this been fixed in 2.1?
Thanks

**Comment by Lxiamail** [comment] 2018-10-24 21:31
@swiftarrow101 This hasn't been fixed yet, however, it is in our pipe to work on.

**Comment by gekiss** [comment] 2018-11-01 16:39
Soap12 without Addressing lost the _action_ attribute in the _ContentType_ header.

The quicker solution is move lines from
https://github.com/dotnet/wcf/blob/1e49a79926b74ef51478a65c6bdfb68c0be06566/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs#L1178-L1182
to 
https://github.com/dotnet/wcf/blob/1e49a79926b74ef51478a65c6bdfb68c0be06566/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/MessageContent.cs#L53

**Comment by bdrupieski** [comment] 2019-01-19 17:16
Is there a workaround for this issue until it's fixed in a future release?

**Comment by bdrupieski** [comment] 2019-01-20 18:59
I think I came up with a workaround. After looking through the source I saw that if I try to add a "SOAPAction" header, it will be added as a Content-Type header parameter. 

This seems to work:

```
private static T AddSoapActionHeader<T>(Expression<Func<T>> expression)
{
    var method = ((MethodCallExpression)expression.Body).Method;
    var operationContract = method.DeclaringType.GetInterfaces()
        .Select(interfaceType => interfaceType.GetMethods())
        .SelectMany(interfaceMethods => interfaceMethods)
        .Where(interfaceMethod => interfaceMethod.Name == method.Name)
        .Select(interfaceMethod => interfaceMethod.GetCustomAttribute<OperationContractAttribute>())
        .FirstOrDefault(attr => attr != null);

    using (new OperationContextScope(_client.InnerChannel))
    {
        if (!string.IsNullOrEmpty(operationContract?.Action))
        {
            OperationContext.Current.OutgoingMessageProperties[HttpRequestMessageProperty.Name] = new HttpRequestMessageProperty
            {
                Headers =
                {
                    { "SOAPAction", $"\"{operationContract.Action}\"" },
                }
            };
        }

        var func = expression.Compile();
        return func();
    }
}
```
I have to wrap every method call with it, so this:
```
var products = _client.getProductList(id);
```
becomes:
```
var products = AddSoapActionHeader(() => _client.getProductList(id));
```

**Closed** 2019-03-04 19:00 UTC
Labels: 3 - Ready For Review, Servicing-Consider-2.1, bug
