### ISSUE TITLE
Unable to Add Microsoft WCF Web Service Reference in Assembly with conditional references

### ISSUE THREAD

**Issue by lemoinem** [dotnet/wcf#3681] opened 2019-06-10 17:27 UTC
VS2019 (16.1.2)

Reproduction steps:

1. Create new Library Project
2. In csproj:
   1. Set `<TargetFrameworks>netstandard2.0;net461</TargetFrameworks>`
   2. Add `<ItemGroup Condition="'$(TargetFramework)'=='net461'"><Reference Include="System.Web" /></ItemGroup>`
3. Try adding a WCF Connected Service

Error:
> The Connected Services component 'Microsft WCF Web Service Reference Provider' failed: (HRESULT:0x80131500) The project reference specification 'System.Web' does not have a file path.

Expected Behavior:
I should be able to add a WCF Connecter Service Reference without issue.

Use case:
I am trying to migrate an old library, that needs to target both old ASP.Net and ASP.Net Core. This is why I have a conditional reference to `System.Web`.

Workaround:
1. Comment the conditional reference to `System.Web`
2. Add WCF Reference
3. Restore conditional reference

**Comment by StephenBonikowsky** [comment] 2019-06-13 01:43
Thanks for reporting the issue @lemoinem 
I was able to reproduce the issue easily, we'll do some investigation.

**Comment by dasetser** [comment] 2019-06-13 18:59
@lemoinem This looks like a bug in our reference detection logic. We'll look into what would be required to fix this.

Out of curiosity, if this is a library project why can't you target just .NET Standard which can be referenced by both .NET Core and .NET Framework projects? Does the full framework version of the library do something additional that isn't supported on .NET Standard?

**Comment by lemoinem** [comment] 2019-06-13 19:12
The library has references to ASP.Net (including System.Web), but the .Net Core references ASP.Net Core.
The library is used by several ASP.Net (and Console/Windows GUI) .Net Frameworks apps.
We are currently in the process of migrating some of these to .Net Core and ASP.Net Core.
We need our Utils libraries (this being one of them) to keep working as-is when built for .Net Framework and to be usable by the migrated .Net Core app at the same time.
While keeping code modifications to a minimum.

So we're basically using multiple targeting, conditional references, and `#ifdef`s to generate the same API  but built on top of either environment.

I don't think that's something we can do while targeting .Net Standard only. 
Moreover, there are some features that are available in both .Net Framework 4.6.1 and .Net Core 2.2, but not in .Net Standard 2.0 (such as `TypeLibTypeAttribute`). So targeting .Net Standard wouldn't fit our needs anyway.

**Comment by dasetser** [comment] 2019-07-29 19:13
This is fixed in dotnet-svcutil 2.0.1, which is now available. It's not fixed in the UI tool (WCF Web Service Reference Provider) yet, but we plan to update it in VS 2019 16.3.

**Closed by dasetser** 2019-07-29 19:13 UTC
Labels: DotNet-SvcUtil 2.0.1, tooling
