### ISSUE TITLE
Cant generate proxy using a local wsdl file , getting error  - the service at following uri does not have a valid endpoint

### ISSUE THREAD

**Issue by rajput81** [dotnet/wcf#2254] opened 2017-08-30 09:02 UTC
None of these wsdls work, the location of the wsdl files is [here](https://support.travelport.com/webhelp/uapi/Content/Resources/uAPI_WSDLschema_Release-V17.3.0.35.zip)

**Comment by hongdai** [comment] 2017-08-30 18:18
@rajput81  The below information will be helpful to identify the root cause:
 Any wsdl work for "Adding Service Reference" or svcutil.exe? i.e. It can generate client code and the client code can successfully make calls to the service.

Thanks,
Hong Dai

**Comment by rajput81** [comment] 2017-08-30 23:43
Hi Hong Dai - Yes all their wsdls work and generate a working proxy via the Add service Ref wizard as well as svcutil. This is delaying our plans to move to .net core..

**Comment by rajput81** [comment] 2017-08-30 23:45
Just to confirm Add new service reference only worked in .Net framework projects.

**Comment by hongdai** [comment] 2017-08-30 23:49
Yes. It's expected Add new service reference only works in .Net framework projects. We will try to repro locally and investigate the root cause.

Thanks,
Hong Dai

**Comment by hongdai** [comment] 2017-08-30 23:53
@rajput81 Could you tell me which WSDL file worked for svcutil.exe? I've tried several of them without the luck.

**Comment by rajput81** [comment] 2017-09-04 06:48
Hi Hong Dai  Yes Can confirm it didnt worked for me with svcutil also..but it definitely worked using "Add service reference"...who do i go to now? :)

**Comment by hongdai** [comment] 2017-09-05 15:15
@rajput81 could you tell me which WSDL works for the "Add service reference"? I've also tried without any luck.

**Comment by rajput81** [comment] 2017-09-06 00:35
Hi Hong Dai..This is the first one I tried and it worked:

![image](https://user-images.githubusercontent.com/31430610/30089222-dcd060d2-92ee-11e7-91f1-bb1fd014d5dc.png)

The wsdl path would be : Release-V17.3.0.35-V17.3\uprofile_v37_0\UProfile.wsdl

All schemas are [here](https://support.travelport.com/webhelp/uapi/Content/Resources/uAPI_WSDLschema_Release-V17.3.0.35.zip)

**Comment by rajput81** [comment] 2017-09-14 03:07
Any update Hong Dai?

**Comment by hongdai** [comment] 2017-09-14 05:59
@rajput81 I'm able to use "Add Service Reference" successfully with the Release-V17.3.0.35-V17.3\uprofile_v37_0\UProfile.wsdl. There could be various reasons why the Net Core connected service tool does not support it. We will further investigate and let you know the root cause.

Thanks,
Hong Dai

**Comment by hongdai** [comment] 2017-09-15 23:47
@rajput81 This is because the NET Core WCF service reference tool does not support schema files NOT in the same directory currently. We will evaluate the support.
@mlacouture

**Comment by rajput81** [comment] 2017-09-16 05:39
Thanks for the update Hong Dai.. Is there a workaround available till it gets supported? ie putting everything under same folder, editing the wsdl etc..an example will be great.

________________________________

**Comment by hongdai** [comment] 2017-09-18 16:49
@rajput81 Putting everything under the same folder will not work in your case as many different schema files under different folders share the same name. 

The workaround I can think of is to use dotnet-svcutil.dll directly by:
1) Open a command line.
2) find the location of dotnet-svcutil.dll and use below command:
`dotnet dotnet-svcutil.dll  C:\Temp\issue2254\uAPI_WSDLschema_Release-V17.3.0.35\WSDL_XSD_Release-V17.3.0.35-V17.3\Release-V17.3.0.35-V17.3\common_v37_0\* C:\Temp\issue2254\uAPI_WSDLschema_Release-V17.3.0.35\WSDL_XSD_Release-V17.3.0.35-V17.3\Release-V17.3.0.35-V17.3\uprofile_v37_0\* /tf:netcoreapp1.0`

Note that you need to specify all directories that contain the required schema file.

Thanks,
Hong Dai

**Comment by hongdai** [comment] 2017-10-10 18:20
This issue is fixed in the pending release.

**Comment by hongdai** [comment] 2017-10-13 22:05
The fix is released in the VS 15.5.0 Preview 1. 
You can download it from https://www.visualstudio.com/en-us/news/releasenotes/vs2017-preview-relnotes.

**Closed by hongdai** 2017-10-13 22:05 UTC
Labels: bug, Community, tooling

**Comment by rajput81** [comment] 2017-10-22 23:23
Hi Hong Dai 

Thank you very much for this fix. I was hoping that I could just upgrade  NET Core WCF service reference tool and start using it for this development. Is that not possible? We are reluctant to use any Preview version of visual studio for our development activities..

Thanks
SR

**Comment by hongdai** [comment] 2017-10-23 03:46
It is not possible . We are now only shipping with Visual Studio.

 I understand your concern, but I would suggest you try the preview as I have personally extensively used it and found it is high quality.

Thanks,
Hong Dai

**Comment by zhenlan** [comment] 2017-10-24 05:28
Hi @rajput81, the preview release of VS 15.5 can be installed side by side with the stable version of VS you are currently using, so you can continue to use the stable version of VS for the most of your development activities but use the preview version of VS for the WCF service reference. If you run into any issues, please do let us know so we can address them in future VS releases.
