### ISSUE TITLE
Problem Sending XML as String

### ISSUE THREAD

**Issue by fpanaccia** [dotnet/wcf#3138] opened 2018-08-29 02:56 UTC
Hi, i am consuming a Soap service of Argentina's "IRS", when i was doing it using the full Framework, this was the code,

![image](https://user-images.githubusercontent.com/5436904/44761876-3e26d880-ab1b-11e8-8e07-f2fd74545aea.png)

In Net Core, this is the code

![image](https://user-images.githubusercontent.com/5436904/44761895-5860b680-ab1b-11e8-85b4-d3dfc7858ad1.png)

As you can see, they are both very similar, the problem is, that in Net Core the service responds that he can parse that string, using fiddler i discover that the "Full Framework" is sending the package like this

![image](https://user-images.githubusercontent.com/5436904/44761635-37e42c80-ab1a-11e8-8160-ded49978a0c3.png)

And Using de Net Core Version

![image](https://user-images.githubusercontent.com/5436904/44761683-74178d00-ab1a-11e8-944b-dcfabc7c8d61.png)

As you can see the result is diferent, as workarround i have to change the Net Core version to something like this

![image](https://user-images.githubusercontent.com/5436904/44761866-2bac9f00-ab1b-11e8-910b-2f64dc56b991.png)

Visual Studio Version: 15.8.1 Enterprise
Net Core: 2.1.1
The "Full Framework" Version: 4.5.2

**Comment by StephenBonikowsky** [comment] 2019-05-29 22:15
This issue is the same root cause as #2889.
Will use #2889 as the primary issue and close this one.

**Closed by StephenBonikowsky** 2019-05-29 22:15 UTC
Labels: Net Core 3.0, bug, serialization
