### ISSUE TITLE
Configure WCF Web Service Reference doesn't re-use assemblies.

### ISSUE THREAD

**Issue by Dark-Bond** [dotnet/wcf#2929] opened 2018-06-06 17:37 UTC
I've check the 'Reuse types in reference assemblies' button (actually, I just left the default).  I have an assembly 'DarkBond.ClientModel' (which shows up in the 'Reuse types in specific referenced assemblies' list.  The library 'DarkBond.ClientModel' is used by the web service to generate faults that are recognized by both sides of the conversation.  When I generate a web service reference, the resulting reference.cs has the faults defined (created) in it, which causes the obvious conflict.
We had this problem many years ago when Web Reference were still new.  This is an ugly bit of deja-vu.

**Comment by mlacouture** [comment] 2018-06-07 22:35
Hi @Dark-Bond 
thank you for reporting this issue.  did you ensure the types in the DarkBond.ClientModel are the same used by the service? this includes namespaces.  we'll investigate ...

**Comment by Dark-Bond** [comment] 2018-06-07 22:45
I've got a fair amount of exposure to how this is supposed to work.  I've been using WSDL since it was first introduced into .NET.  #1, the namespaces don't need to be the same in the traditional Service Reference, just the base type names.  #2, yes, I tried forcing the namespaces to be the same.  It didn't work.
This brings up another issue.  In the traditional WSDL tool (Create/Update Service Reference), the dialog asks you for the name for the reference.  If you type in 'Import', the old version would take the default namespace and add it to 'Import' (resulting in the internal namespace MyCompany.MyNamespace.Import in the generated file).  With the .NET Core tool, you are forced to provide a complete namespace in the dialog for the name of the web service interface (that is, if you were to type in 'Import', you get the namespace 'Import' in the generated file).

**Comment by mlacouture** [comment] 2018-06-07 23:05
Thank you @Dark-Bond for the additional details and feedback, we will take a look at this as soon as we have a chance.

**Comment by HesamKashefi** [comment] 2018-06-11 17:04
same issue here, this tool does not work for reusing types! I tried hard to get WCF working on .NET Core but finally I ended up switching back to traditional ASP.NET for my project.
this tool and the fallowing exception (and exceptions exactly like this one saying "Could not load file or assembly xxx") after using ChannelBase<> in my project stopped me to use wcf for .net core
`Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.2.0.0`
anyway I could still use wcf for .net core by not reusing my types and also ignoring errors when the tool is generating the assemblies for me .
I don't know what is with the error (Could not load file or assembly xxx) cause I saw this many many times when I was working with this WCF client libraries

**Comment by mlacouture** [comment] 2018-06-15 23:16
Hi @Dark-Bond 
I finally had a chance to look into this issue but I haven't been able to reproduce it.  Would it be possible for you to create a small project illustrating the issue? 

thank you!

**Comment by mlacouture** [comment] 2018-06-15 23:17
@Dark-Bond BTW: regarding the option to name the service reference, can you create a separate issue so we can consider/track it separately?

thank you!

**Comment by mlacouture** [comment] 2018-07-09 19:55
Hi @Dark-Bond! any chance you can provide a project showing the issue? thanks,

**Comment by mlacouture** [comment] 2018-07-17 21:15
Please let us know if you are able to provide a sample app that reproduces this problem as we are not able to reproduce it in-house.  thank you for using this tool, closing for now.

**Closed by mlacouture** 2018-07-17 21:15 UTC
Labels: needs more info, tooling
