### ISSUE TITLE
Time out exception while calling long running WCF service from .net core

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/wcf#2588] opened 2018-02-21 23:38 UTC
@sshaikh1 commented on [Wed Dec 27 2017](https://github.com/dotnet/core/issues/1185)

Time out exception while calling long running WCF service from .net core

Getting a System.Net.Http.WinHttpException (0x80072EE2): The operation timed out... exception is occurring when calling a long running WCF service from .net core 2 web api / console application. Service operation takes around a minute to execute and return a response. Is there away I can set the higher operation timeout, so that it doesn't times out.

Same service operation works fine with .net framework 4.5 console app.

at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at XXXXXXXXXXXXXXX
in D:\XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   .cs:line 28

Inner Exception :

InnerException = {System.Net.Http.WinHttpException (0x80072EE2): The operation timed out
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
at System.Net.Http.WinHttpHandler.<StartRequest...

Thanks.

---

@rahul-raut commented on [Tue Jan 09 2018](https://github.com/dotnet/core/issues/1185#issuecomment-356216535)

I am also facing the same issue.

**Comment by zhenlan** [comment] 2018-02-22 01:52
Likely the same issue as https://github.com/dotnet/wcf/issues/2368.

**Comment by zhenlan** [comment] 2018-02-23 19:37
Duplicate of #2368

**Closed by zhenlan** 2018-02-23 19:37 UTC
