### ISSUE TITLE
svcutil fails (Value cannot be null)

### ISSUE THREAD

**Issue by steveb999** [dotnet/wcf#2993] opened 2018-06-29 21:22 UTC
Microsoft (R) WCF Service Model Proxy Generation Tool for .Net Core platform
[dotnet-svcutil, Version 1.0.0]
Copyright (c) Microsoft Corporation.  All rights reserved.

Error: Value cannot be null.
Parameter name: format

**Comment by mlacouture** [comment] 2018-06-29 21:30
Hi @steveb999 
Thank you for reporting this issue.  Can you provide more details about the problem so we can reproduce it? thanks,

**Comment by steveb999** [comment] 2018-06-29 21:35
Im completely new to c# and dotnet core. I want to add an api to my project. Ive followed the helloservice guide but didnt see the need to create a new project so added the step to mine. 
This
dotnet svcutil https://www.pc2paper.co.uk/lettercustomerapi.svc?wsdl
or this
dotnet svcutil https://www.pc2paper.co.uk/lettercustomerapi.svc?wsdl
gives the error

**Comment by mlacouture** [comment] 2018-06-29 22:05
hmm, just tried it and could not reproduce it.  Can you provide some details about your project that could help us reproduce the problem? thanks,

**Comment by nielosz** [comment] 2018-07-09 16:09
Same here with core 2.1 and svcutil 1.0.1 and http://www.mymagento-1dot9dot3-domain.com/shop/index.php/api/v2_soap/?wsdl

**Comment by mlacouture** [comment] 2018-07-09 19:52
Hi @nielosz 

The provided service address doesn't seem to be accessible, can you double check? also, can you try downloading the WSDL files and trying to reproduce the problem passing the wsdl files instead? If you are able to reproduce the problem with the wsdl files, can you provide these files to us?

thank you for helping find this problem!

**Comment by nielosz** [comment] 2018-07-09 20:29
Hi  @mlacouture,

I have obfuscated the address of our webshop. It's standard magento 1.9.3 wsdl service description.  Downloaded wsdl is
[magento-1.9.3-soap.wsdl.txt](https://github.com/dotnet/wcf/files/2177885/magento-1.9.3-soap.wsdl.txt)

**Comment by mstavrev** [comment] 2018-07-16 11:45
Same for me. I try with ONVIF device WSDL: http://www.onvif.org/ver10/device/wsdl

**Comment by mlacouture** [comment] 2018-07-17 08:00
Hi all!  would it be possible for one of you to create a small project that reproduce the issue for us to investigate? we haven't been able to reproduce the problem in-house.  Thank you!

**Comment by mlacouture** [comment] 2018-08-07 17:41
Hi all!

We just released [dotnet-svcutil v1.0.2](https://www.nuget.org/packages/dotnet-svcutil/1.0.2).  This version comes with the `debug` verbosity option which may help diagnose this problem. To capture the output you can run the tool with a command that looks like the following:

`dotnet svcutil <url> --Verbosity debug  > out.log`

Can you collect logs and share them with us? please ensure to obfuscate or remove any sensitive information in the logs.

We have made several improvements to the tool and the exception may be handled and the output may look different, but hopefully we can pinpoint the problem.

thank you!

**Comment by nielosz** [comment] 2018-08-14 14:17
Sorry for delay, been on vacations. This update fixed my issue – so nothing to post.

**Comment by mlacouture** [comment] 2018-08-14 17:55
Thank you @nielosz for reporting back.  How about the others hitting this issue? thank you!

**Comment by mlacouture** [comment] 2018-08-20 22:39
I'm closing this issue as it seems it has been fixed.  Please let me know if you need any further assistance.

**Closed by mlacouture** 2018-08-20 22:39 UTC
Labels: needs more info, tooling
